module/attribute-date/src/Domain/Entity/DateAttribute.php, module/attribute-date/src/Domain/Factory/DateAttributeFactory.php, module/attribute-image/src/Domain/Entity/ImageAttribute.php, module/attribute-image/src/Domain/Factory/ImageAttributeFactory.php, module/attribute-price/src/Domain/Entity/PriceAttribute.php, module/attribute-price/src/Domain/Factory/PriceAttributeFactory.php, module/attribute-unit/src/Domain/Entity/UnitAttribute.php, module/attribute-unit/src/Domain/Factory/UnitAttributeFactory.php, module/attribute/migrations/Version20180625083834.php, module/attribute/src/Domain/Command/CreateAttributeCommand.php, module/attribute/src/Domain/Entity/AbstractAttribute.php, module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php, module/attribute/src/Domain/Event/Attribute/AttributeCreatedEvent.php, module/attribute/src/Domain/Event/Attribute/AttributeSystemChangedEvent.php, module/attribute/src/Domain/Factory/MultiSelectAttributeFactory.php, module/attribute/src/Domain/Factory/NumericAttributeFactory.php, module/attribute/src/Domain/Factory/SelectAttributeFactory.php, module/attribute/src/Domain/Factory/TextAttributeFactory.php, module/attribute/src/Domain/Factory/TextareaAttributeFactory.php, module/attribute/src/Persistence/Dbal/Projector/AttributeCreatedEventProjector.php, module/attribute/src/Persistence/Dbal/Projector/AttributeSystemChangedEventProjector.php, module/attribute/src/Persistence/Dbal/Query/DbalAttributeGridQuery.php, module/attribute/src/Persistence/Dbal/Query/DbalAttributeQuery.php, module/fixture/src/Resources/fixtures/develop/attributes.yaml, module/fixture/src/Resources/fixtures/develop/translation.yaml, module/fixture/src/Resources/fixtures/fixture.yaml, module/grid/src/Column/LabelColumn.php, module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php, module/workflow/src/Infrastructure/Grid/StatusGrid.php
=> System attribute (hotfix)

module/api/src/Application/EventListener/RequestBodyListener.php, module/api/src/Application/EventListener/ResponseFormatterListener.php, module/api/src/Application/Exception/FormValidationHttpException.php, module/api/src/Application/Exception/ViolationsHttpException.php, module/api/src/Application/Mapper/ExceptionMapper.php, module/api/src/Infrastructure/JMS/Serializer/Handler/ExceptionHandler.php, module/api/src/Infrastructure/JMS/Serializer/Handler/FormErrorHandler.php, module/api/src/Infrastructure/JMS/Serializer/Handler/FormValidationExceptionHandler.php, module/api/src/Infrastructure/JMS/Serializer/Handler/ViolationsExceptionHandler.php, module/api/src/Infrastructure/Normalizer/ExceptionDebugNormalizer.php, module/api/src/Infrastructure/Normalizer/ExceptionNormalizer.php
=> Update api module to PHP 7.4

.github/PULL_REQUEST_TEMPLATE.md
=> feature(core): add PR Template

.github/PULL_REQUEST_TEMPLATE.md, module/attribute/src/Domain/Query/OptionQueryInterface.php, module/attribute/src/Infrastructure/Provider/Strategy/OptionAttributeValueConstraintStrategy.php, module/attribute/src/Persistence/Dbal/Query/DbalOptionQuery.php, module/attribute/tests/Infrastructure/Provider/Strategy/DateAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/ImageAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/NumericAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/OptionAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/TextAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/TextareaAttributeValueConstraintStrategyTest.php, module/attribute/tests/Infrastructure/Provider/Strategy/UnitAttributeValueConstraintStrategyTest.php
updating feature/tile-view-grid
Issue #
=> updating feature/tile-view-grid

module/attribute/src/Application/Form/Model/Option/SimpleOptionModel.php
=> bugfix(attributes) option

module/account/features/account.feature, module/account/src/Application/Controller/Api/Account/UserChangeAction.php, module/account/src/Application/Controller/Api/Account/UserCreateAction.php, module/account/src/Application/Form/CreateUserForm.php, module/account/src/Application/Form/Model/CreateUserFormModel.php, module/account/src/Application/Form/UpdateUserForm.php, module/account/src/Domain/Command/User/CreateUserCommand.php, module/account/src/Infrastructure/Handler/CreateUserCommandHandler.php, module/account/tests/Domain/Command/User/CreateUserCommandTest.php
Removing language privileges collection from user creation
=> removing language privileges collection from user creation

module/designer/src/Infrastructure/Grid/TemplateGrid.php, module/designer/src/Persistence/Dbal/Query/DbalTemplateQuery.php
=> Tile view grid

module/account/src/Infrastructure/Grid/AccountGrid.php, module/account/src/Infrastructure/Grid/LogGrid.php, module/account/src/Infrastructure/Grid/RoleGrid.php, module/attribute/src/Infrastructure/Grid/AttributeGrid.php, module/attribute/src/Infrastructure/Grid/OptionGrid.php, module/category/src/Infrastructure/Grid/CategoryGrid.php, module/comment/src/Infrastructure/Grid/CommentGrid.php, module/condition/src/Infrastructure/Grid/ConditionSetGrid.php, module/grid/features/gridSchema.json, module/grid/src/AbstractGrid.php, module/grid/src/GridConfigurationInterface.php, module/grid/src/Renderer/ColumnRenderer.php, module/grid/src/Renderer/GridRenderer.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionElementGrid.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionGrid.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionTypeGrid.php, module/product/src/Infrastructure/Grid/ProductGrid.php, module/product/src/Infrastructure/Grid/ProductHistoryGrid.php, module/product/src/Infrastructure/Grid/ProductProductCollectionGrid.php, module/segment/src/Infrastructure/Grid/SegmentGrid.php, module/segment/src/Infrastructure/Grid/SegmentProductsGrid.php, module/workflow/src/Infrastructure/Grid/StatusGrid.php, module/workflow/src/Infrastructure/Grid/TransitionGrid.php
Removing configuration from grid
=> removing configuration from grid

module/condition/src/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategy.php, module/editor/features/draft-image-attribute-manipulation.feature, module/editor/features/draft-multi-select-attribute-manipulation.feature, module/editor/features/draft-numeric-attribute-manipulation.feature, module/editor/features/draft-price-attribute-manipulation.feature, module/editor/features/draft-select-attribute-manipulation.feature, module/editor/features/draft-text-attribute-manipulation.feature, module/editor/features/draft-textarea-attribute-manipulation.feature, module/editor/features/draft-unit-attribute-manipulation.feature, module/editor/src/Domain/Entity/ProductDraft.php, module/editor/src/Infrastructure/Handler/AbstractValueCommandHandler.php, module/editor/src/Infrastructure/Handler/RemoveProductAttributeValueCommandHandler.php, module/editor/src/Persistence/Projector/ProductDraftValueAddedEventProjector.php, module/editor/src/Persistence/Projector/ProductDraftValueChangedEventProjector.php, module/product/src/Infrastructure/Calculator/TranslationInheritanceCalculator.php, module/product/src/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Persistence/Dbal/Projector/ProductValueAddedEventProjector.php, module/product/src/Persistence/Dbal/Projector/ProductValueChangedEventProjector.php, module/value/src/Domain/Resolver/ValueResolver.php, module/value/src/Domain/Service/Strategy/StringCollectionValueUpdateStrategy.php, module/value/src/Domain/ValueObject/StringCollectionValue.php, module/value/src/Domain/ValueObject/TranslatableStringValue.php, module/value/tests/Domain/ValueObject/StringCollectionValueTest.php, module/value/tests/Domain/ValueObject/StringValueTest.php, module/value/tests/Domain/ValueObject/TranslatableStringValueTest.php, module/value/tests/Infrastructure/JMS/Serializer/Handler/ValueInterfaceHandlerTest.php
Add possibility to work with inherence language for multiselect values
Issue #504
add support for language code for StrongCollectionValue
=> feature(product) add posibility for multiselect value to work with language tree

module/account/features/account.feature, module/account/src/Persistence/Dbal/Query/DbalProfileQuery.php
=> feature(profile) add language privilege

module/account/src/Application/Security/Voter/LanguageVoter.php, module/account/src/Application/Security/Voter/UserRoleVoter.php, module/account/tests/Application/Security/Voter/LanguageVoterTest.php, module/account/tests/Application/Security/Voter/UserRoleVoterTest.php, module/editor/features/draft-manipulation-privileges.feature, module/editor/src/Application/Controller/Api/ProductDraftController.php
Prevent access to draft value edit when user haven correct language privileges
Issue #504
Add LanguageVote for check that user have read or edit access to given language
Use voter on change and remove value on draft object
=> feature(security) add user language access voter

module/completeness/src/Domain/Calculator/Strategy/AttributeTemplateElementCompletenessStrategy.php, module/completeness/src/Domain/ReadModel/CompletenessElementReadModel.php, module/completeness/tests/Domain/ReadModel/CompletenessElementReadModelTest.php, module/designer/src/Domain/Builder/Strategy/AttributeViewTemplateElementStrategy.php, module/product/src/Infrastructure/Calculator/TranslationInheritanceCalculator.php, module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php
Add missing Scope information in draft response
Issue  #504
=> fix(attribute) add missing information to endpoint

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1ProductProcessor.php, module/product/src/Persistence/Dbal/Projector/ProductCreatedEventProjector.php
Fix multiselect incorrect import
Issue #504
=> bugfix(import) fix incomparable import of multiselect

module/designer/src/Infrastructure/Grid/TemplateGrid.php
Fixing links in template grids
=> fix(template) fixing template grid links

config/packages/nelmio_api_doc.yaml
Removing unnecessary properties from nelmio_api_doc.yaml
Issue #
=> fix(account): removing unnecessary properties from nelmio_api_doc.yaml

module/attribute/features/attribute-validate.feature, module/attribute/src/Application/Controller/Api/Attribute/AttributeCreateAction.php, module/attribute/src/Application/Form/AttributeTypeForm.php, module/attribute/src/Application/Model/AttributeTypeFormModel.php
Fix exception when create attribute.
=> fix(attribute)create validation type

module/core/src/Domain/Query/LanguageQueryInterface.php, module/core/src/Persistence/Dbal/Query/DbalLanguageQuery.php, module/editor/src/Application/Controller/Api/ProductDraftController.php, module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php, module/product/src/Persistence/Dbal/Projector/ProductValueAddedEventProjector.php, module/product/src/Persistence/Dbal/Projector/ProductValueChangedEventProjector.php
Fix bags in language inheritance
=> Language inheritance

module/core/migrations/Version20200429064721.php, module/product/src/Infrastructure/Grid/Builder/Query/AbstractAttributeDataSetBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Strategy/ProductAttributeLanguageResolver.php, module/product/tests/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/ImageAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/SelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextareaAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Strategy/ProductAttributeLanguageResolverTest.php
=> Language inheritance grid root

module/exporter/features/export-profile-grid.feature, module/exporter/migrations/Version20200122064958.php, module/exporter/src/Application/Controller/Api/ExportProfile/ExportProfileChangeAction.php, module/exporter/src/Application/Controller/Api/ExportProfile/ExportProfileCreateAction.php, module/exporter/src/Application/Controller/Api/ExportProfile/ExportProfileDeleteAction.php, module/exporter/src/Application/Controller/Api/ExportProfile/ExportProfileGridAction.php, module/exporter/src/Application/Controller/Api/ExportProfile/ExportProfileReadAction.php, module/exporter/src/Domain/Query/ExportProfileQueryInterface.php, module/exporter/src/Infrastructure/Grid/ExportProfileGrid.php, module/exporter/src/Persistence/Dbal/Projector/Product/ProductCreatedEventProjector.php, module/exporter/src/Persistence/Dbal/Projector/Product/ProductRemovedFromCategoryEventProjector.php, module/exporter/src/Persistence/Dbal/Query/DbalExportProfileQuery.php, module/exporter/src/Persistence/Dbal/Repository/DbalExportProfileRepository.php, module/exporter/src/Persistence/Dbal/Repository/Factory/ExportProfileFactory.php, module/exporter/tests/Infrastructure/Grid/ExportProfileGridTest.php
Need have possibility to see list of available export profiles in system
Issue #374
Add export profile grid endpoint
=> feature(exporter) add export profile grid

composer.lock, module/channel/src/Application/Controller/Api/ChannelCreateAction.php, module/channel/src/Application/Controller/Api/Export/ChannelExportCreateAction.php, module/channel/src/Application/Controller/Api/Export/ChannelExportGridAction.php, module/channel/src/Domain/Query/ExportQueryInterface.php, module/channel/src/Infrastructure/Grid/ExportGrid.php, module/channel/src/Persistence/Dbal/Query/DbalExportQuery.php, module/channel/src/Resources/config/routes.yml, module/channel/src/Resources/config/services.yml, module/channel/tests/Infrastructure/Grid/ChannelGridTest.php, module/channel/tests/Infrastructure/Grid/ExportGridTest.php, module/exporter-file/features/export-profile-file.feature
Ned to have possibility to list exports for given channel. 
Issue #374
Add export grid endpoint for specific channel with standard grid response
```GET api/v1/{language}/channels/{channel}/exports```
=> feature(exporter) add export grid endpoint for given channel

module/channel/src/Application/Controller/Api/Export/ChannelExportAction.php, module/channel/src/Application/Controller/Api/Export/ChannelExportCreateAction.php, module/core/src/Domain/ValueObject/TranslatableString.php, module/exporter-file/features/export-profile-file.feature, module/exporter/src/Application/Request/ParamConverter/ExportParamConverter.php, module/exporter/src/Application/Request/ParamConverter/ExportProfileParamConverter.php, module/exporter/src/Infrastructure/JMS/Serializer/Handler/ExportStatusHandler.php, module/exporter/tests/Application/Request/ParamConverter/ExportParamConverterTest.php, module/exporter/tests/Application/Request/ParamConverter/ExportProfileParamConverterTest.php, module/fixture/src/Infrastructure/Faker/StringCollectionValueFaker.php, module/fixture/src/Infrastructure/Faker/TranslatableStringValueFaker.php, module/product/src/Domain/Event/ProductCreatedEvent.php, src/Resources/fixtures/develop/attributes.yaml, src/Resources/fixtures/develop/products.yaml
Need to have possibility show information about specific export 
Issue #374
Add new  endpoint to fetch export information:
``` GET api/v1/{language}/channels/{channel}/exports/{export} ```
Fix develop fixtures generation
=> feature(exporter) add export information endpoint

module/product/features/grouping-product.feature, module/product/features/variable-product.feature, module/product/src/Application/Model/Product/GroupingProductFormModel.php, module/product/src/Application/Model/Product/SimpleProductFormModel.php, module/product/src/Application/Model/Product/VariableProductFormModel.php
Template validation for updating product is missing
Issue #517
Add missing assertions
=> fix(product) fix update product form validation

composer.json, composer.lock, config/bundles.php, config/packages/flysystem.yaml, module/exporter-file/src/Infrastructure/Processor/FileExportProcessor.php, module/exporter-file/src/Infrastructure/Processor/Process/EndFileExportProcess.php, module/exporter-file/src/Infrastructure/Processor/Process/ProcessFileExportProcess.php, module/exporter-file/src/Infrastructure/Processor/Process/StartFileExportProcess.php, module/exporter-file/tests/Infrastructure/Processor/Process/EndFileExportProcessTest.php, module/exporter-file/tests/Infrastructure/Processor/Process/ProcessFileExportProcessTest.php, module/exporter-file/tests/Infrastructure/Processor/Process/StartFileExportProcessTest.php, module/exporter/src/Infrastructure/Handler/Export/EndExportCommandHandler.php, module/exporter/src/Infrastructure/Handler/Export/ProcessExportCommandHandler.php, module/exporter/src/Infrastructure/Handler/Export/StartExportCommandHandler.php, module/exporter/src/Infrastructure/Processor/ExportProcessorInterface.php, symfony.lock
Need have possibility to use different  filesystem storages not only local.
Issue  #374
Add flyfilesystem bundle to project
=> feature(exporter) add flyfilesystem

module/channel/features/notification.feature, module/channel/src/Application/Controller/Api/Notification/ExportNotificationAction.php, module/channel/src/Domain/Query/ExportQueryInterface.php, module/channel/src/Infrastructure/Handler/StartExportChannelCommandHandler.php, module/channel/src/Persistence/Dbal/Projector/ChannelDeletedEventProjector.php, module/channel/src/Persistence/Dbal/Query/DbalExportQuery.php, module/channel/src/Persistence/Dbal/Repository/DbalChannelRepository.php, module/channel/src/Resources/config/routes.yml, module/exporter/migrations/Version20200122064958.php, module/exporter/src/Domain/Entity/Export.php, module/exporter/src/Domain/Entity/ExportLine.php, module/exporter/src/Domain/Repository/ExportLineRepositoryInterface.php, module/exporter/src/Infrastructure/Handler/Export/ProcessExportCommandHandler.php, module/exporter/src/Persistence/Dbal/Repository/DbalExportLineRepository.php, module/exporter/src/Persistence/Dbal/Repository/DbalExportRepository.php, module/exporter/src/Persistence/Dbal/Repository/Factory/ExportLineFactory.php, module/exporter/src/Persistence/Dbal/Repository/Mapper/ExportLineMapper.php, module/exporter/src/Persistence/Dbal/Repository/Mapper/ExportMapper.php, module/exporter/tests/Domain/Command/Export/EndExportCommandTest.php, module/exporter/tests/Domain/Command/Export/ProcessExportCommandTest.php, module/exporter/tests/Domain/Command/Export/StartExportCommandTest.php, module/exporter/tests/Domain/Entity/ExportLineTest.php, module/exporter/tests/Domain/Entity/ExportTest.php, module/exporter/tests/Domain/ValueObject/ExportStatusTest.php, module/exporter/tests/Infrastructure/Grid/ExportProfileGridTest.php, module/exporter/tests/Infrastructure/JMS/Serializer/Handler/ExportStatusHandlerTest.php, module/importer/src/Domain/Repository/ImportLineRepositoryInterface.php, module/importer/src/Persistence/Dbal/Repository/DbalImportLineRepository.php
Need have possibility to show export status.
Issue #374
Add profile export information endpoint
```api/v1/{language}/profile/exports```
=> feature(exporter) Add profile notification support

config/packages/nelmio_api_doc.yaml, module/channel/src/Application/Controller/Api/Export/ChannelExportErrorGridAction.php, module/channel/src/Application/Controller/Api/Notification/ExportNotificationAction.php, module/channel/src/Domain/Query/ExportQueryInterface.php, module/channel/src/Infrastructure/Grid/ExportErrorsGrid.php, module/channel/src/Persistence/Dbal/Query/DbalExportQuery.php, module/channel/tests/Infrastructure/Grid/ExportErrorsGridTest.php, module/core/features/api-doc.feature, module/exporter-file/features/export-profile-file.feature, module/exporter-file/src/Infrastructure/Processor/FileExportProcessor.php, module/exporter-file/src/Infrastructure/Processor/Process/ProcessFileExportProcess.php, module/exporter/src/Infrastructure/Exception/ExportException.php, module/exporter/src/Infrastructure/Handler/Export/ProcessExportCommandHandler.php, module/exporter/src/Infrastructure/Processor/ExportProcessorInterface.php, module/product/src/Application/Controller/Api/Bindings/ProductAddBindingAction.php, module/product/src/Application/Controller/Api/Relations/ProductAddChildAction.php, module/product/src/Application/Controller/Api/Relations/ProductRemoveChildAction.php
Need possibility to list export errors
Issue #374
1. add export exception and processing handling of them
2. add add export grid for given export
=> feature(exporter) add error grid and export exception

depfile.yml, module/attribute/src/Domain/Query/AttributeQueryInterface.php, module/attribute/src/Infrastructure/Relation/AttributeMultimediaRelation.php, module/attribute/src/Persistence/Dbal/Query/DbalAttributeQuery.php, module/attribute/src/Persistence/Dbal/Query/Decorator/CacheAttributeQueryDecorator.php, module/attribute/src/Resources/translations/attribute.en.yaml, module/attribute/src/Resources/translations/attribute.pl.yaml, module/designer/features/designer.feature, module/designer/src/Domain/Query/TemplateQueryInterface.php, module/designer/src/Infrastructure/Relation/TemplateMultimediaRelation.php, module/designer/src/Persistence/Dbal/Query/DbalTemplateQuery.php, module/designer/src/Resources/translations/template.en.yaml, module/designer/src/Resources/translations/template.pl.yaml, module/multimedia/features/multimedia-relation.feature, module/multimedia/src/Application/Controller/Api/Multimedia/GetMultimediaRelationAction.php, module/multimedia/src/Application/DependencyInjection/CompilerPass/MultimediaRelationCompilerPass.php, module/multimedia/src/Application/DependencyInjection/ErgonodeMultimediaExtension.php, module/multimedia/src/ErgonodeMultimediaBundle.php, module/multimedia/src/Infrastructure/Provider/MultimediaRelationInterface.php, module/multimedia/src/Infrastructure/Provider/MultimediaRelationProvider.php, module/multimedia/tests/Domain/Entity/AbstractMultimediaTest.php, module/multimedia/tests/Infrastructure/Provider/MultimediaRelationProviderTest.php, module/product/features/variable-product.feature, module/product/src/Application/Controller/Api/Bindings/ProductAddBindingAction.php, module/product/src/Domain/Query/ProductQueryInterface.php, module/product/src/Infrastructure/Relation/ProductMultimediaRelation.php, module/product/src/Persistence/Dbal/Query/DbalProductQuery.php, module/product/src/Persistence/Dbal/Query/Decorator/CacheProductQueryDecorator.php, module/product/src/Resources/translations/product.en.yaml, module/product/src/Resources/translations/product.pl.yaml
#Description
Add service to gather information about relation for given multimedia resource.
Add endpoint with relation information:
``` GET v1/api/{language}/multimedia/{multimedia}/relation```
Relation service can be extended by adding class that implement interface:
```Ergonode\Multimedia\Infrastructure\Provider\MultimediaRelationInterface```
Issue  #576
=>  feature(multimedia) add multimedia relation information service,endpoint

.travis.yml, composer.json
=> configuration(travis) added imagick suppoort to travis.yml

module/designer/src/Persistence/Dbal/Query/DbalTemplateQuery.php
=> feature(grid) fixes after testing

module/core/src/Persistence/Dbal/Query/Builder/DbalDefaultImageQueryBuilder.php, module/core/src/Persistence/Dbal/Query/Builder/DbalDefaultLabelQueryBuilder.php, module/product-collection/src/Persistence/Dbal/Query/DbalProductCollectionElementQuery.php, module/product/src/Infrastructure/Grid/ProductChildrenGrid.php, module/product/src/Persistence/Dbal/Query/DbalProductChildrenQuery.php, src/Resources/fixtures/develop/attributes.yaml, src/Resources/fixtures/develop/products.yaml
Adding tile view gird functionality to variable products.
Issue #566
=> feature(grid) Implementing tile view grid to variable products

module/attribute/features/attribute-text-area.feature, module/attribute/src/Application/Form/Attribute/Configuration/TextareaAttributeConfigurationForm.php, module/attribute/src/Application/Form/Attribute/TextareaAttributeForm.php, module/attribute/src/Application/Model/Attribute/Property/TextareaAttributePropertyModel.php, module/attribute/src/Application/Model/Attribute/TextareaAttributeFormModel.php, module/attribute/src/Domain/Command/Attribute/Create/CreateTextareaAttributeCommand.php, module/attribute/src/Domain/Command/Attribute/Update/UpdateTextareaAttributeCommand.php, module/attribute/src/Domain/Entity/Attribute/AbstractTextareaAttribute.php, module/attribute/src/Infrastructure/Factory/Command/Create/CreateTextareaAttributeCommandFactory.php, module/attribute/src/Infrastructure/Factory/Command/Update/UpdateTextareaAttributeCommandFactory.php, module/attribute/src/Infrastructure/Handler/Attribute/Create/CreateTextareaAttributeCommandHandler.php, module/attribute/src/Infrastructure/Handler/Attribute/Update/UpdateTextareaAttributeCommandHandler.php, module/attribute/src/Persistence/Dbal/Projector/Attribute/AttributeCreatedEventProjector.php, module/attribute/tests/Application/Form/Attribute/TextareaAttributeFormTest.php, module/attribute/tests/Domain/Entity/Attribute/TextareaAttributeTest.php, module/editor/features/draft-global-textarea-attribute-manipulation.feature, module/editor/features/draft-local-textarea-attribute-manipulation.feature, module/importer/src/Infrastructure/Action/Process/Attribute/TextareaAttributeImportProcessorStrategy.php, module/product/features/product-edit.feature, src/Resources/fixtures/develop/attributes.yaml
Extending textarea attribute for rich text editor
Issue #
=> feature(attribute) extending textarea attribute for rich text editor

module/api/src/Application/Response/FileContentResponse.php, module/multimedia/features/multimedia.feature, module/multimedia/src/Application/Controller/Api/Multimedia/GetMultimediaAction.php
=> feature(grid) Adding new type of response (FileContentResponse)

module/attribute/features/attribute-text-area.feature, module/attribute/src/Application/Form/Attribute/Configuration/TextareaAttributeConfigurationForm.php, module/attribute/src/Application/Model/Attribute/Property/TextareaAttributePropertyModel.php, module/attribute/src/Domain/Command/Attribute/Create/CreateTextareaAttributeCommand.php, module/attribute/src/Domain/Command/Attribute/Update/UpdateTextareaAttributeCommand.php, module/attribute/src/Domain/Entity/Attribute/AbstractTextareaAttribute.php, module/attribute/src/Infrastructure/Factory/Command/Create/CreateTextareaAttributeCommandFactory.php, module/attribute/src/Infrastructure/Factory/Command/Update/UpdateTextareaAttributeCommandFactory.php, module/attribute/src/Infrastructure/Handler/Attribute/Create/CreateTextareaAttributeCommandHandler.php, module/attribute/src/Infrastructure/Handler/Attribute/Update/UpdateTextareaAttributeCommandHandler.php, module/attribute/tests/Application/Form/Attribute/TextareaAttributeFormTest.php, module/attribute/tests/Domain/Entity/Attribute/TextareaAttributeTest.php, module/editor/features/draft-local-textarea-attribute-manipulation.feature, module/importer/src/Infrastructure/Action/Process/Attribute/TextareaAttributeImportProcessorStrategy.php, module/product/features/product-edit.feature
=> feature(attribute) Renaming textarea attribute parameter

src/Resources/fixtures/develop/products.yaml
=> Variants fixes

module/core/src/Domain/ValueObject/TranslatableString.php, module/editor/features/draft-global-numeric-attribute-manipulation.feature, module/editor/features/draft-global-price-attribute-manipulation.feature, module/editor/features/draft-global-unit-attribute-manipulation.feature, module/editor/src/Infrastructure/Handler/AbstractValueCommandHandler.php
=> bug(draft) Fixing null draft error

src/Resources/fixtures/develop/products.yaml
Fixing problem with multiselects value in fixtures
=> bug(fixtures) Fixing problem with multiselects value in fixtures

module/product/src/Infrastructure/Grid/ProductChildrenGrid.php, module/product/src/Persistence/Dbal/Query/DbalProductChildrenQuery.php
Adding delete link to child grid
=> bug(products) Adding delete link to child grid

module/attribute/features/attribute-grid.feature, module/attribute/features/attribute-group.feature, module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/grid/src/AbstractDbalDataSet.php, module/product/features/product-grid.feature
Fix dbal query for grid filter
Issue  #517
=> bugfix(grid) fix filter query for null or empty results

module/editor/features/draft-atribute-relation.feature, module/editor/src/Domain/Query/DraftQueryInterface.php, module/editor/src/Infrastructure/Strategy/Relationship/ProductDraftAttributeRelationshipStrategy.php, module/editor/src/Persistence/Query/DbalDraftQuery.php
Add relation resolve in draft value.
=> bugfix(draft) relation to atttribute

module/attribute/features/attribute-text-area.feature, module/attribute/src/Persistence/Dbal/Projector/Attribute/AbstractAttributeParameterChangeEventProjector.php
Fixing bug with changing textarea rich edit
=> bug(attributes) Fixing bug with changing textarea rich edit

module/designer/migrations/Version20180719132703.php
Adding attributes template types
=> bug(attribute) Adding attribute types to template

module/attribute/src/Resources/translations/attribute.en.yaml, module/attribute/src/Resources/translations/attribute.pl.yaml, module/designer/migrations/Version20180719132703.php
=> Fixing bugs

module/category/src/Application/Model/Tree/CategoryTreeCreateFormModel.php, module/category/tests/Application/Form/Tree/CategoryTreeCreateFormTest.php, module/category/tests/Application/Form/Tree/CategoryTreeUpdateFormTest.php, module/category/tests/Application/Provider/CategoryFormProviderTest.php, module/category/tests/Application/Provider/CategoryTypeProviderTest.php, module/category/tests/Domain/Entity/AbstractCategoryTest.php, module/category/tests/Domain/Entity/Attribute/CategorySystemAttributeTest.php, module/category/tests/Domain/Entity/CategoryTreeTest.php, module/category/tests/Domain/Event/CategoryCreatedEventTest.php, module/category/tests/Infrastructure/Factory/Command/CreateCategoryCommandFactoryTest.php, module/category/tests/Infrastructure/Factory/Command/UpdateCategoryCommandFactoryTest.php, module/category/tests/Infrastructure/Handler/Tree/CreateTreeCommandHandlerTest.php, module/category/tests/Infrastructure/Handler/Tree/DeleteTreeCommandHandlerTest.php, module/category/tests/Infrastructure/Handler/Tree/UpdateTreeCommandHandlerTest.php, module/category/tests/Infrastructure/Provider/CreateCategoryCommandFactoryProviderTest.php, module/category/tests/Infrastructure/Provider/UpdateCategoryCommandFactoryProviderTest.php, module/category/tests/Infrastructure/Validator/CategoryTreeExistsValidatorTest.php, module/category/tests/Infrastructure/Validator/UniqueCategoryTreeCodeValidatorTest.php
Unit tests for category module
=> tests(category) Unit tests for category module

module/fixture/src/Infrastructure/Faker/FileFaker.php, module/multimedia/src/Infrastructure/Grid/MultimediaGrid.php, module/multimedia/src/Infrastructure/Handler/AddMultimediaCommandHandler.php
=> bugfix(multimedia) Fixing bugs

module/exporter-shopware-6/src/Infrastructure/Client/Shopware6PropertyGroupClient.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/PropertyGroup/PostPropertyGroupAction.php, module/exporter-shopware-6/src/Infrastructure/Synchronizer/CategorySynchronizer.php, module/exporter-shopware-6/src/Infrastructure/Synchronizer/PropertyGroupSynchronizer.php
Refactoring inserting property group.
Issue #659
=> feature(export) Refactoring inserting property group

module/attribute/tests/Application/Form/Transformer/AttributeGroupCodeDataTransformerTest.php, module/attribute/tests/Application/Form/Transformer/AttributeTypeDataTransformerTest.php, module/attribute/tests/Application/Form/Transformer/OptionKeyDataTransformerTest.php, module/core/tests/Domain/ValueObject/LanguageNodeTest.php, module/core/tests/Infrastructure/Builder/LanguageTree/NestedSetTreeTest.php, module/core/tests/Infrastructure/Mapper/LanguageTreeMapperTest.php, module/core/tests/Infrastructure/Validator/LanguageCodeActiveValidatorTest.php, module/importer-magento-1/features/magento-1-import.feature, module/importer-magento-1/src/Application/Form/Type/StoreViewType.php, module/value/tests/Infrastructure/JMS/Serializer/Handler/ValueInterfaceHandlerTest.php
Repairing a mistake after changing the language code standard.
Issue #664
=> bugfix(core) lannguage code

module/channel/src/Application/Controller/Api/ChannelCreateAction.php, module/channel/src/Application/Form/ChannelTypeForm.php, module/channel/src/Application/Form/Model/ChannelTypeFormModel.php, module/channel/src/Application/Form/Model/Type/ChannelTypeType.php, module/channel/src/Domain/Entity/AbstractChannel.php, module/channel/src/Infrastructure/Grid/ChannelGrid.php, module/channel/src/Infrastructure/Grid/ExportGrid.php, module/channel/src/Persistence/Dbal/Query/DbalChannelQuery.php, module/channel/src/Persistence/Dbal/Query/DbalExportQuery.php, module/channel/tests/Infrastructure/Grid/ChannelGridTest.php, module/exporter-file/src/Application/Model/ExporterFileConfigurationModel.php, module/exporter-file/src/Infrastructure/Builder/Command/CreateFileExportChannelCommandBuilder.php, module/exporter-magento-2/src/Resources/config/services.yml, module/exporter-magento-2/src/Resources/translations/channel.en.yaml, module/exporter-magento-2/src/Resources/translations/channel.pl.yaml
Change validation and add new filed on grid. 
Issue #650
=> feature(export) add field on grid and fix channel validation

module/multimedia/features/multimedia-privilege.feature, module/multimedia/features/multimedia.feature, module/multimedia/migrations/Version20180807065948.php, module/multimedia/src/Application/Controller/Api/Multimedia/DownloadMultimediaAction.php, module/multimedia/src/Application/Controller/Api/Multimedia/DownloadThumbnailMultimediaAction.php, module/multimedia/src/Application/Controller/Api/Multimedia/GetMultimediaRelationAction.php, module/multimedia/src/Application/Controller/Api/Multimedia/UpdateMultimediaAction.php, module/multimedia/src/Application/Form/MultimediaForm.php, module/multimedia/src/Application/Model/MultimediaModel.php, module/multimedia/src/Domain/Command/UpdateMultimediaCommand.php, module/multimedia/src/Domain/Entity/AbstractMultimedia.php, module/multimedia/src/Domain/Event/MultimediaNameChangedEvent.php, module/multimedia/src/Infrastructure/Grid/MultimediaGrid.php, module/multimedia/src/Infrastructure/Handler/UpdateMultimediaCommandHandler.php, module/multimedia/src/Persistence/Dbal/Projector/MultimediaNameChangedEventProjector.php, module/multimedia/tests/Domain/Command/UpdateMultimediaCommandTest.php, module/multimedia/tests/Domain/Event/MultimediaNameChangedEventTest.php
Add multimedia update endpoint
Issue #576
=> feature(multimedia) Add multimedia edit endpoint

module/importer-magento-1/features/magento-1-import.feature, module/importer/src/Application/Controller/Api/Import/ImportErrorGridAction.php, module/importer/src/Domain/Query/ImportQueryInterface.php, module/importer/src/Infrastructure/Grid/ImportErrorsGrid.php, module/importer/src/Persistence/Dbal/Query/DbalImportQuery.php, module/importer/tests/Infrastructure/Grid/ImportErrorsGridTest.php
=> feature(import) error grid

module/channel/src/Application/Controller/Api/ChannelReadAction.php, module/multimedia/features/multimedia-grid.feature, module/multimedia/src/Persistence/Dbal/Query/DbalMultimediaQuery.php
Bug fix grid filter in multimedia module.
Issue #
=> bugfix(multimedia) grid filter

module/comment/src/Infrastructure/Grid/CommentGrid.php, module/comment/src/Persistence/Dbal/Query/DbalCommentQuery.php, module/notification/src/Persistence/Dbal/Query/DbalNotificationQuery.php
Adding avatar_filename to grids
Issue #612
=> fixes(avatar,multimedia) Adding avatar_filename to grids

module/account/src/Domain/Command/Role/CreateRoleCommand.php, module/account/src/Domain/Factory/RoleFactory.php, module/account/src/Infrastructure/Handler/Role/CreateRoleCommandHandler.php, module/exporter/migrations/Version20200122064958.php
=> bugfix(account) hidden role

module/editor/src/Application/Controller/Api/ProductDraftController.php
Security at the entrance.
Change from '' to null at the draft input .
Issue #
=> bugfix(grid) draft input data

module/channel/migrations/Version20181120151840.php, module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php, module/exporter/migrations/Version20200122064958.php, module/importer/migrations/Version20180618134343.php, module/importer/src/Application/Controller/Api/Import/ImportDeleteAction.php, module/importer/src/Application/Controller/Api/Source/SourceDeleteAction.php, module/importer/src/Domain/Command/DeleteSourceCommand.php, module/importer/src/Domain/Command/Import/DeleteImportCommand.php, module/importer/src/Domain/Entity/Import.php, module/importer/src/Domain/Repository/ImportRepositoryInterface.php, module/importer/src/Domain/Repository/SourceRepositoryInterface.php, module/importer/src/Infrastructure/Handler/DeleteSourceCommandHandler.php, module/importer/src/Infrastructure/Handler/Import/DeleteImportCommandHandler.php, module/importer/src/Persistence/Dbal/Repository/DbalImportRepository.php, module/importer/src/Persistence/Dbal/Repository/DbalSourceRepository.php, module/importer/tests/Domain/Command/DeleteSourceCommandTest.php, module/importer/tests/Domain/Command/Import/DeleteImportCommandTest.php
Implements source delete command action 
Issue #
=> feature(import) source delete

module/exporter-shopware-6/features/export-profile-shopware6-api.feature, module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php, module/exporter-shopware-6/src/Application/Form/Type/CustomFieldAttributeMapType.php, module/exporter-shopware-6/src/Application/Form/Type/PropertyGroupAttributeMapType.php, module/exporter-shopware-6/src/Application/Model/Shopware6ChannelFormModel.php, module/exporter-shopware-6/src/Application/Model/Type/CustomFieldAttributeModel.php, module/exporter-shopware-6/src/Application/Model/Type/PropertyGroupAttributeModel.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Product/GetProductList.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductActiveMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductPriceMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductStockMapper.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Product.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6ProductPrice.php
Change on the form and repair mapping
Issue #654
=> feature(export) shopware6 mapping and form changes

module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php, module/exporter-shopware-6/src/Application/Model/Shopware6ChannelFormModel.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6CreateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6UpdateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Command/CreateShopware6ChannelCommand.php, module/exporter-shopware-6/src/Domain/Command/UpdateShopware6ChannelCommand.php, module/exporter-shopware-6/src/Domain/Entity/Shopware6Channel.php, module/exporter-shopware-6/src/Infrastructure/Client/Shopware6ProductClient.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Product/Properties/DeleteProperties.php, module/exporter-shopware-6/src/Infrastructure/Handler/CreateShopware6ChannelCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Handler/ProcessExportCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Handler/UpdateShopware6ChannelCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Product.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6ProductConfiguratorSettings.php, module/exporter-shopware-6/src/Infrastructure/Processor/Shopware6ExportStepProcessInterface.php, module/exporter-shopware-6/src/Infrastructure/Processor/Step/Shopware6SimpleProductStep.php, module/exporter-shopware-6/src/Infrastructure/Processor/Step/Shopware6VariableProductStep.php, module/exporter-shopware-6/tests/Domain/Builder/Shopware6CreateChannelCommandBuilderTest.php, module/exporter-shopware-6/tests/Domain/Builder/Shopware6UpdateChannelCommandBuilderTest.php, module/exporter-shopware-6/tests/Domain/Command/CreateShopware6ChannelCommandTest.php, module/exporter-shopware-6/tests/Domain/Command/UpdateShopware6ChannelCommandTest.php, module/exporter-shopware-6/tests/Domain/Entity/Shopware6ChannelTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6ProductConfiguratorSettingsTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6ProductPriceTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6ProductTest.php, module/segment/src/Domain/Query/SegmentProductsQueryInterface.php, module/segment/src/Domain/Query/SegmentQueryInterface.php, module/segment/src/Persistence/Dbal/Query/DbalSegmentProductsQuery.php, module/segment/src/Persistence/Dbal/Query/DbalSegmentQuery.php
Improvements to the properties and add segment to shopware6 
Issue #528
=> feature(exporter) shopware6 segment and properties 

module/multimedia/src/Infrastructure/Grid/MultimediaGrid.php
All sizes in multimedia grid are in kb so mb changed to kb.
=> bug(multimedia) Changing size suffix

config/packages/messenger.yaml
Add command to asynchronous messenger
=> bugfix(export) messenger add command

module/core/src/Infrastructure/EventListener/ConnectionWorkerEventSubscriber.php
Messenger worker reset subscriber. 
Issue #
=> bugfix(core) messenger worker kill

module/channel/src/Application/Controller/Api/Scheduler/SchedulerChangeAction.php, module/channel/src/Application/Form/Model/SchedulerModel.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/exporter-file/features/scheduler.feature
Fixing scheduler validation once it is not active
Issue #528
=> bug(export) Fixing scheduler validation

module/account/features/account-privileges.feature, module/account/features/account-roles.feature, module/account/src/Application/Security/Voter/UserRoleVoter.php, module/account/tests/Application/Security/Voter/UserRoleVoterTest.php
Fixing not working privileges on backend
=> bug(account) Fixing not working privileges on backend

module/event-sourcing/src/Infrastructure/Manager/EventStoreManager.php, module/event-sourcing/src/Infrastructure/Snapshot/AggregateSnapshotInterface.php, module/event-sourcing/src/Infrastructure/Snapshot/DbalAggregateSnapshot.php
Delete snapshot after remove aggregate object. Release of space in the base.
Issue #
=> bugfix(event store) delete snapshot after remove aggregate object

module/core/src/Application/Controller/Api/LanguageTree/LanguageTreeReadAction.php
Fixing bug with language tree privileges
=> bug(language tree) fixing bug with langauge tree privileges

module/exporter-file/features/export-channel-file.feature, module/importer-magento-1/features/magento-1-import.feature, module/importer-magento-1/src/Infrastructure/Source/Magento1ImportSourceService.php, module/importer-magento-2/src/Infrastructure/Source/Magento2ImportSourceService.php, module/importer/src/Application/Controller/Api/Source/SourceCreateAction.php, module/importer/src/Application/DependencyInjection/CompilerPass/AttributeActionProcessorCompilerPass.php, module/importer/src/Application/DependencyInjection/CompilerPass/SourceTypeCompilerPass.php, module/importer/src/Application/DependencyInjection/ErgonodeImporterExtension.php, module/importer/src/Application/Form/SourceTypeForm.php, module/importer/src/Application/Model/Form/SourceTypeFormModel.php, module/importer/src/Application/Model/Form/Type/SourceTypeType.php, module/importer/src/ErgonodeImporterBundle.php, module/importer/src/Infrastructure/Provider/ImportSourceInterface.php, module/importer/src/Infrastructure/Provider/SourceTypeDictionaryProvider.php, module/importer/src/Infrastructure/Provider/SourceTypeProvider.php
=> bug(import) fixing Imports validation

module/channel/src/Application/DependencyInjection/CompilerPass/ChannelTypeCompilerPass.php, module/channel/src/Application/Provider/ChannelTypeProvider.php, module/channel/src/Domain/Entity/AbstractChannel.php, module/channel/src/Domain/Entity/ChannelInterface.php, module/channel/tests/Domain/Entity/ChannelTest.php, module/exporter-file/src/Domain/Entity/FileExportChannel.php, module/exporter-magento-2/src/Domain/Entity/Magento2CsvChannel.php, module/exporter-shopware-6/src/Domain/Entity/Shopware6Channel.php
Changing way of providing Channel type
=> bug(designer) changing way of providing Channel type

module/workflow/src/Application/Controller/Api/Dashboard/WidgetStatusCountAction.php, module/workflow/src/Domain/Query/StatusQueryInterface.php, module/workflow/src/Persistence/Dbal/Query/DbalStatusQuery.php, module/workflow/src/Resources/config/routes.yml, module/workflow/tests/Application/Controller/Api/Dashboard/WidgetStatusCountActionTest.php, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
Add dashboard product status endpoint.
Issue #672
=> feat(dashboard) Added dashboard widget with status count

module/attribute/features/attribute-autocomplete.feature, module/attribute/features/attribute.json, module/attribute/src/Application/Controller/Api/Attribute/AttributeAutocompleteAction.php, module/attribute/src/Domain/Query/AttributeQueryInterface.php, module/attribute/src/Persistence/Dbal/Query/DbalAttributeQuery.php, module/attribute/src/Persistence/Dbal/Query/Decorator/CacheAttributeQueryDecorator.php, module/core/src/Application/Controller/Api/Language/LanguageAutocompleteAction.php
Adding attribute autocomplete endpoint
Issue #730
=> feature(attribute) Adding attribute autocomplete endpoint

module/category/features/category-autocomplete.feature, module/category/features/category.json, module/category/src/Application/Controller/Api/CategoryAutocompleteAction.php, module/category/src/Domain/Query/CategoryQueryInterface.php, module/category/src/Persistence/Dbal/Query/DbalCategoryQuery.php
Adding category autocomplete endpoint
Issue #730
=> feature(category) Adding category autocomplete endpoint

composer.lock, module/designer/src/Domain/Entity/Template.php
Fixed invalid phpstan/phpstan version
=> bugfix Fixed invalid phpstan/phpstan version

module/product/features/product-autocomplete.feature, module/product/features/product.json, module/product/src/Application/Controller/Api/ProductAutocompleteAction.php, module/product/src/Domain/Query/ProductQueryInterface.php, module/product/src/Persistence/Dbal/Query/DbalProductQuery.php, module/product/src/Persistence/Dbal/Query/Decorator/CacheProductQueryDecorator.php
Adding product autocomplete endpoint
Issue #730
=> feature(product) Adding product autocomplete endpoint

module/attribute/features/attribute-autocomplete.feature, module/attribute/features/attribute-groups-autocomplete.feature, module/attribute/src/Application/Controller/Api/AttributeGroup/AttributeGroupAutocompleteAction.php, module/attribute/src/Domain/Query/AttributeGroupQueryInterface.php, module/attribute/src/Persistence/Dbal/Query/DbalAttributeGroupQuery.php
Adding attribute groups autocomplete endpoint
Issue #730
=> feature(attribute) Adding attribute groups autocomplete endpoint

module/designer/features/designer-autocomplete.feature, module/designer/features/template.json, module/designer/src/Application/Controller/Api/Template/TemplateAutocompleteAction.php, module/designer/src/Domain/Query/TemplateQueryInterface.php, module/designer/src/Persistence/Dbal/Query/DbalTemplateQuery.php
Adding template autocomplete endpoint.
Issue #730
=> feature(designer) Adding template autocomplete endpoint

module/account/features/role-autocomplete.feature, module/account/features/role.json, module/account/src/Application/Controller/Api/Role/RoleAutocompleteAction.php, module/account/src/Domain/Query/RoleQueryInterface.php, module/account/src/Persistence/Dbal/Query/DbalRoleQuery.php
Adding role autocomplete endpoint
Issue #730
=> feature(account) Adding role autocomplete endpoint

build.xml, phpunit.xml.dist
Fixed Phing PHPUnit targets:
* removed coverage on simple unit target
* defined coverage target explicitly
* removed hardcoded configuration file
=> feature(testing) Fixed Phing PHPUnit targets

.gitignore
Overridable configuration files for customizable local testing
=> feature(testing) Overridable configuration files

.env.test, .travis.yml
Improving CI performance with disabling of xdebug and debug environment for the project. Time down from ~10 mins to ~5mins
=> feature(core) Travis optimization

composer.lock, config/packages/messenger.yaml, module/core/src/Application/Model/LanguageCollectionFormModel.php, module/designer/src/Application/Model/Form/TemplateFormModel.php, symfony.lock
Bumped Symfony packages.
Issues:
* duplicated Messanger bus middleware(https://github.com/symfony/symfony/pull/37569/files)
* invalid usage od validator constraint
=> feature(core) Bumped Symfony packages

.travis.yml, composer.json, composer.lock
Added composer validation for maintaining lock consistency
=> feature(testing) Composer validation

module/account/src/Infrastructure/Persistence/Projector/Role/DbalRoleCreatedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/Role/DbalRoleDeletedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/Role/DbalRoleDescriptionChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/Role/DbalRoleNameChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/Role/DbalRolePrivilegesChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserActivatedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserAvatarChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserAvatarDeletedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserCreatedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserDeactivatedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserFirstNameChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserLanguageChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserLanguagePrivilegesCollectionChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserLastNameChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserPasswordChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Projector/User/DbalUserRoleChangedEventProjector.php, module/account/src/Infrastructure/Persistence/Query/DbalAccountQuery.php, module/account/src/Infrastructure/Persistence/Query/DbalLogQuery.php, module/account/src/Infrastructure/Persistence/Query/DbalPrivilegeQuery.php, module/account/src/Infrastructure/Persistence/Query/DbalProfileQuery.php, module/account/src/Infrastructure/Persistence/Query/DbalRoleQuery.php, module/account/src/Infrastructure/Persistence/Query/DbalUserQuery.php, module/account/src/Infrastructure/Persistence/Repository/DbalRoleRepository.php, module/account/src/Infrastructure/Persistence/Repository/DbalUserRepository.php, module/account/src/Resources/config/services.yml
=> refactor(account): Moved persistense directory into infrastructure

module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6CategoryQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6CustomFiledQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6LanguageQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6MultimediaQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6PropertyGroupQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6CategoryRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6CurrencyRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6CustomFieldRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6LanguageRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6MultimediaRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6ProductRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6PropertyGroupOptionsRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6PropertyGroupRepository.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6TaxRepository.php, module/exporter-shopware-6/src/Resources/config/services.yml
=> refactor(shopware): Moved persistense directory into infrastructure

module/editor/src/Infrastructure/Persistence/Projector/DbalProductCreatedEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDeleteEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDraftAppliedEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDraftCreatedEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDraftValueAddedEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDraftValueChangedEventProjector.php, module/editor/src/Infrastructure/Persistence/Projector/DbalProductDraftValueRemovedEventProjector.php, module/editor/src/Infrastructure/Persistence/Query/DbalDraftQuery.php, module/editor/src/Infrastructure/Persistence/Repository/DbalProductDraftRepository.php, module/editor/src/Resources/config/services.yml
=> refactor(editor): Moved persistense directory into infrastructure

module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateCreatedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultImageAddedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultImageChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultImageRemovedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultLabelRemovedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultTextAddedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateDefaultTextChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateElementAddedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateElementChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateElementRemovedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateGroupChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateImageAddedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateImageChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateImageRemovedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateNameChangedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/DbalTemplateRemovedEventProjector.php, module/designer/src/Infrastructure/Persistence/Projector/Group/DbalTemplateGroupCreatedEventProjector.php, module/designer/src/Infrastructure/Persistence/Query/DbalTemplateElementQuery.php, module/designer/src/Infrastructure/Persistence/Query/DbalTemplateGroupQuery.php, module/designer/src/Infrastructure/Persistence/Query/DbalTemplateQuery.php, module/designer/src/Infrastructure/Persistence/Repository/DbalTemplateGroupRepository.php, module/designer/src/Infrastructure/Persistence/Repository/DbalTemplateRepository.php, module/designer/src/Infrastructure/Persistence/Repository/Decorator/CacheTemplateRepositoryDecorator.php, module/designer/src/Resources/config/services.yml
=> refactor(designer): Moved persistense directory into infrastructure

module/product-collection/features/product-collections.feature, module/product/features/product.feature, module/product/features/variable-product-available-children-grid.feature, module/product/src/Application/Controller/Api/Relations/VariableProductAvailableChildrenAction.php, module/product/src/Application/Request/ParamConverter/AbstractProductParamConverter.php, module/product/src/Domain/Query/ProductChildrenQueryInterface.php, module/product/src/Infrastructure/Grid/VariableProductAvailableChildrenGrid.php, module/product/src/Persistence/Dbal/Query/DbalProductChildrenQuery.php, module/product/tests/Application/Request/ParamConverter/AbstractProductParamConverterTest.php
Adding grid with children and available products for variable products.
Issue #766
=> feature(product) Adding grid with children and available products for variable products

module/workflow/src/Infrastructure/Persistence/Projector/DbalStatusColorChangedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/DbalStatusCreatedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/DbalStatusDeletedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/DbalStatusDescriptionChangedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/DbalStatusNameChangedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowCreatedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowDefaultStatusSetEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowDeletedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowStatusAddedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowTransitionAddedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowTransitionRemovedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionQuery.php, module/workflow/src/Infrastructure/Persistence/Query/DbalWorkflowQuery.php, module/workflow/src/Infrastructure/Persistence/Repository/DbalStatusRepository.php, module/workflow/src/Infrastructure/Persistence/Repository/DbalWorkflowRepository.php, module/workflow/src/Resources/config/services.yml, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
=> refactor(workflow): Moved persistense directory into infrastructure

module/value/src/Infrastructure/Persistence/Projector/DbalValueAddedEventProjector.php, module/value/src/Infrastructure/Persistence/Projector/DbalValueChangedEventProjector.php, module/value/src/Infrastructure/Persistence/Projector/DbalValueRemovedEventProjector.php
=> refactor(value): Moved persistense directory into infrastructure

module/transformer/src/Infrastructure/Persistence/Projector/DbalTransformerCreatedEventProjector.php, module/transformer/src/Infrastructure/Persistence/Projector/DbalTransformerDeletedEventProjector.php, module/transformer/src/Infrastructure/Persistence/Repository/DbalTransformerRepository.php, module/transformer/src/Resources/config/services.yml
=> refactor(transformer): Moved persistense directory into infrastructure

module/workflow/src/Domain/Entity/Workflow.php, module/workflow/tests/Domain/Entity/WorkflowTest.php
Fixed workflow transition sorting
=> bug(workflow) Fixed workflow transition sorting

module/product/src/Domain/Entity/Attribute/CreatedBySystemAttribute.php, module/product/src/Domain/Entity/Attribute/EditedBySystemAttribute.php, module/product/src/Infrastructure/Grid/Builder/Query/CreatedBySystemAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/EditedBySystemAttributeDataSetQueryBuilder.php
Addition of missing filters to the product grid.
Issue #
=> bug(product) filter created by and edited by

module/core/features/core.feature, module/core/features/language.json, module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php
Changing structure of language autocomplete endpoint to unify it with all other autocomplete endpoints.
Issue #730
=> bug(core) unifying language autocomplete with rest autocompletes

module/product/src/Infrastructure/Handler/Create/CreateVariableProductCommandHandler.php
=> bug(product) Fixing develop merge

module/account/features/role-autocomplete.feature, module/account/src/Infrastructure/Persistence/Query/DbalRoleQuery.php, module/core/features/core.feature, module/core/src/Application/Controller/Api/Language/LanguageAutocompleteAction.php, module/designer/features/designer-autocomplete.feature, module/designer/src/Infrastructure/Persistence/Query/DbalTemplateQuery.php, module/product/features/product-autocomplete.feature, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php
Fixing autocomplete responses
Issue #730
=> bug(product) Fixing autocomplete responses

module/product/features/associated-product-available-children-grid.feature, module/product/src/Application/Controller/Api/Relations/AssociatedProductAvailableChildrenAction.php, module/product/src/Domain/Query/ProductChildrenQueryInterface.php, module/product/src/Infrastructure/Grid/AssociatedProductAvailableChildrenGrid.php, module/product/src/Infrastructure/Persistence/Query/DbalProductChildrenQuery.php
Fixing variable grid children grid
=> Fixing variable grid children grid

module/completeness/features/completeness-widget.feature, module/completeness/src/Application/Controller/Api/Dashboard/WidgetCompletenessCountAction.php, module/completeness/src/Domain/Query/CompletenessQueryInterface.php, module/completeness/src/Domain/ReadModel/CompletenessWidgetModel.php, module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php, module/completeness/tests/Domain/ReadModel/CompletenessWidgetModelTest.php
Add completeness widget endpoint 
Issue #672
=> feature(dashboard) add completeness widget endpoint

module/condition/src/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategy.php, module/condition/tests/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategyTest.php, module/segment/features/segment.feature
Fixed option condition for segments
=> bugfix(condition) Fixed option condition

module/core/src/Infrastructure/Strategy/RelationshipStrategyInterface.php, module/designer/src/Infrastructure/Strategy/Relationship/TemplateMultimediaRelationshipStrategy.php, module/multimedia/features/multimedia-relation.feature, module/multimedia/migrations/Version20180807065948.php, module/multimedia/src/Application/Controller/Api/Multimedia/DeleteMultimediaAction.php, module/multimedia/src/Domain/Command/DeleteMultimediaCommand.php, module/multimedia/src/Infrastructure/Grid/MultimediaGrid.php, module/multimedia/src/Infrastructure/Handler/DeleteMultimediaCommandHandler.php, module/multimedia/src/Infrastructure/Persistence/Projector/DbalMultimediaDeletedEventProjector.php, module/multimedia/src/Infrastructure/Persistence/Query/DbalMultimediaQuery.php, module/multimedia/tests/Domain/Command/DeleteMultimediaCommandTest.php, module/multimedia/tests/Infrastructure/Handler/DeleteMultimediaCommandHandlerTest.php, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php, module/product/src/Infrastructure/Strategy/Relationship/ProductMultimediaRelationshipStrategy.php
Add new endpoint to delete multimedia
Issue #
=> feature(multimiedia) delete action

module/core/src/Application/Request/ParamConverter/LanguageParamConverter.php, module/workflow/src/Application/Controller/Api/Dashboard/WidgetStatusCountAction.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Domain/Query/StatusQueryInterface.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/tests/Application/Controller/Api/Dashboard/WidgetStatusCountActionTest.php, module/workflow/tests/Domain/Entity/AbstractWorkflowTest.php, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
Extended status count with the possibility to differentiate workflow by language
=> feature(workflow) Extended status count with possibility to differentiate workflow by language

module/multimedia/src/Application/Model/MultimediaModel.php, module/multimedia/src/Application/Model/MultimediaUploadModel.php, module/multimedia/src/Application/Validator/Constraint/MultimediaName.php, module/multimedia/src/Application/Validator/Constraint/MultimediaNameValidator.php, module/multimedia/tests/Application/Validator/Constraint/MultimediaNameValidatorTest.php
Add validator to upload file name and change name to 128 sign.
=> feature(multimedia) change filename limit and add validator

module/account/src/Resources/translations/log.en.yaml
=> bugfix(account) Translation typo

module/mailer/src/Infrastructure/Sender/Strategy/SymfonyMailerStrategy.php, module/product/features/associated-product-available-children-grid.feature, module/product/src/Application/Controller/Api/Relations/AssociatedProductAvailableChildrenAction.php, module/product/src/Domain/Query/ProductChildrenQueryInterface.php, module/product/src/Infrastructure/Grid/AssociatedProductAvailableChildrenGrid.php, module/product/src/Infrastructure/Persistence/Query/DbalProductChildrenQuery.php
Adding binding collumns to available products grid and fixing filtering
Issue #766
=> Adding binding collumns to available products grid and fixing filtering

module/category/src/Application/Form/Type/CategoryCodeType.php, module/category/src/Application/Model/CategoryFormModel.php
fixes category code validate message
Issue #
=> bug(category) fixes category code validate message

module/completeness/src/Domain/ReadModel/CompletenessWidgetModel.php, module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php
Fix incorrect procentage product completenes calculation for widget
=> bugfix(completeness) fix incorrect widget calcaulation

module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Decorator/Shopware6NewProductActiveMapperDecorator.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Decorator/Shopware6NewProductPriceMapperDecorator.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Decorator/Shopware6NewProductStockMapperDecorator.php, module/exporter-shopware-6/src/Resources/config/services.yml, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/CategoryRemoveShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/CategoryShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/CustomFieldShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/EndShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/ProductShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/PropertyGroupShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Handler/Export/StartShopware6ExportCommandHandlerTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6MediaDefaultFolderTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6MediaTest.php
=> feature(exporter) shopware6 mapper

module/product/src/Application/Controller/Api/ProductChangeAction.php, module/product/src/Application/Controller/Api/ProductCreateAction.php, module/product/src/Application/DependencyInjection/ErgonodeProductExtension.php, module/product/src/Application/Form/Product/GroupingProductForm.php, module/product/src/Application/Form/Product/ProductFormInterface.php, module/product/src/Application/Form/Product/ProductTypeForm.php, module/product/src/Application/Form/Product/SimpleProductForm.php, module/product/src/Application/Form/Product/VariableProductForm.php, module/product/src/Application/Model/Product/GroupingProductFormModel.php, module/product/src/Application/Model/Product/ProductTypeFormModel.php, module/product/src/Application/Model/Product/SimpleProductFormModel.php, module/product/src/Application/Model/Product/VariableProductFormModel.php, module/product/src/Application/Provider/ProductFormProvider.php, module/product/src/Application/Provider/ProductSupportProviderInterface.php, module/product/src/Infrastructure/Validator/AvailableProductType.php, module/product/src/Infrastructure/Validator/AvailableProductTypeValidator.php, module/product/tests/Application/Provider/ProductFormProviderTest.php
=> feature(product) Product form unification

module/exporter-shopware-6/src/Resources/config/services.yml, module/multimedia/src/Application/Validator/Constraint/MultimediaName.php
Update the validation message.
=> fix(media) validator message

module/channel/src/Infrastructure/Grid/ExportGrid.php, module/importer/src/Infrastructure/Grid/ImportErrorsGrid.php, module/multimedia/src/Infrastructure/Grid/MultimediaGrid.php
Changing Date columns and filters in grids
=> bug(grids) Changing Date columns and filters in grids

module/product/src/Infrastructure/Grid/AssociatedProductAvailableChildrenGrid.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php
Adding color to status count endpoint
=> bug(workflow) Adding color to status count endpoint

module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php, module/product/src/Domain/Query/ProductQueryInterface.php, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php, module/product/src/Infrastructure/Persistence/Query/Decorator/CacheProductQueryDecorator.php
Fix completeness widget calculation
=> bugfix(completeness) fix completeness calculation

module/product/src/Infrastructure/Persistence/Projector/AbstractProductValueProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueAddedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueChangedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueRemovedEventProjector.php
Separation of abstract class for attribute value projection for adding, changing and deleting values
=> refactor(product) Separation of abstract class for attribute value projection

module/designer/src/Application/Model/Form/Type/Property/SegmentElementPropertyTypeModel.php
Changing character limit for section
Issue #
=> bug(designer) Changing character limit for section

module/account/src/Application/Form/Model/CreateUserFormModel.php, module/account/src/Application/Form/Model/RoleFormModel.php, module/account/src/Application/Form/Model/UpdateUserFormModel.php, module/attribute/src/Application/Form/Model/CreateAttributeGroupFormModel.php, module/attribute/src/Application/Form/Model/Option/SimpleOptionModel.php, module/attribute/src/Application/Form/Model/UpdateAttributeGroupFormModel.php, module/attribute/src/Application/Model/Attribute/AttributeFormModel.php, module/category/src/Application/Model/CategoryFormModel.php, module/category/src/Application/Model/Tree/CategoryTreeCreateFormModel.php, module/category/src/Application/Model/Tree/CategoryTreeUpdateFormModel.php, module/core/src/Application/Model/UnitFormModel.php, module/product-collection/src/Application/Model/ProductCollectionCreateFormModel.php, module/product-collection/src/Application/Model/ProductCollectionTypeCreateFormModel.php, module/product-collection/src/Application/Model/ProductCollectionTypeUpdateFormModel.php, module/product-collection/src/Application/Model/ProductCollectionUpdateFormModel.php, module/workflow/src/Application/Form/Model/StatusChangeFormModel.php, module/workflow/src/Application/Form/Model/StatusCreateFormModel.php, module/workflow/src/Application/Form/Model/TransitionChangeFormModel.php, module/workflow/src/Application/Form/Model/TransitionCreateFormModel.php, module/workflow/src/Application/Form/Model/Workflow/WorkflowFormModel.php
Update some message validation. 
Issue #
=> feature(all) validator too long message

module/attribute/migrations/Version20180401083834.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeCreatedEventProjector.php
=> bug(attribute) Removing value table from db

module/account/src/Application/Command/CreateUserCommand.php
User create command always return error code 1 even if is successful. 
- [*] Bug fix (non-breaking change which fixes an issue)
=> fix user create

module/importer-magento-1/src/Infrastructure/Processor/StartMagento1ImportProcess.php
Add magneto 1 process log import errors
=> feature(importer) add StartMagento1Process import logs

module/category/src/Domain/ValueObject/CategoryCode.php, module/importer-magento-1/src/Infrastructure/Processor/StartMagento1ImportProcess.php
Extend CategoryCode VO error message
=> Add importer logs

module/attribute/src/Infrastructure/Grid/AttributeGrid.php, module/attribute/src/Infrastructure/Grid/AttributeGroupGrid.php, module/category/src/Infrastructure/Grid/CategoryGrid.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionGrid.php, module/segment/src/Application/Form/Model/CreateSegmentFormModel.php, module/segment/src/Infrastructure/Grid/SegmentGrid.php, module/workflow/src/Infrastructure/Grid/StatusGrid.php
Changing names from code to system name
=> bug(all) Changing names from code to system name

module/importer/src/Infrastructure/Exception/ImportBindingAttributeNotFoundException.php, module/importer/src/Infrastructure/Exception/ImportIncorrectBindingAttributeException.php
Fixed conflicting changes for empty comments
=> bugfix(core) Fixed conflicting changes for empty comments

phpcs.xml.dist
Added missing code sniffer annotation rules
=> bugfix(core) Added missing code sniffer annotation rules

module/channel/migrations/Version20191120151840.php, module/mailer/src/Domain/Mail.php, module/product-collection/migrations/Version20200127083123.php, phpcs.xml.dist, src/Kernel.php
Added missing license annotation in files
=> feature(core) Added missing license annotation in files

config/packages/security.yaml, module/account/migrations/Version20180401062601.php, module/account/src/Domain/ValueObject/Password.php, module/account/tests/Domain/ValueObject/PasswordTest.php, src/Resources/fixtures/develop/user.yaml, src/Resources/fixtures/fixture.yaml
Changing endcoding user password
=> bug(account) Changing endcoding user password

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1ConfigurableProductProcessor.php, module/importer-magento-1/src/Infrastructure/Reader/Magento1CsvReader.php, module/product/src/Domain/Entity/AbstractAssociatedProduct.php
Change the way of gathering variable product children information
=> refactoring(importer) change variable product chldren import

module/importer-magento-1/src/Infrastructure/Processor/Step/AbstractProductProcessor.php, module/importer/src/Infrastructure/Action/Process/Product/ImportProductAttributeBuilder.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductAttributeStrategyInterface.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductImageAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductMultiSelectAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductSelectAttributeStrategy.php, module/importer/src/Resources/config/services.yml, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductImageAttributeStrategyTest.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductMultiSelectAttributeStrategyTest.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductSelectAttributeStrategyTest.php
Fix missing attribute mapping in import process
=> refactor(importer) fix missing attribute strategy configuration

module/importer/migrations/Version20180618134343.php, module/importer/src/Domain/Command/Import/StopImportCommand.php, module/importer/src/Domain/Repository/ImportRepositoryInterface.php, module/importer/src/Infrastructure/Exception/ImportBindingAttributeNotFoundException.php, module/importer/src/Infrastructure/Exception/ImportIncorrectBindingAttributeException.php, module/importer/src/Infrastructure/Exception/ImportRelatedProductIncorrectTypeException.php, module/importer/src/Infrastructure/Exception/ImportRelatedProductNotFoundException.php, module/importer/src/Infrastructure/Grid/ImportErrorsGrid.php, module/importer/src/Infrastructure/Handler/Import/StopImportCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportCategoryCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportGroupingProductCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportMultimediaFromUrlCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportOptionCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportSimpleProductCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportTemplateCommandHandler.php, module/importer/src/Infrastructure/Handler/ImportVariableProductCommandHandler.php, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php, module/importer/src/Infrastructure/Persistence/Repository/DbalImportRepository.php
Add translated import error mesages
=> feature(importer) add transalted error messages

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1BundleProductProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1CategoryProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1ConfigurableProductProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1GroupedProductProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1MultimediaProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1OptionProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1SimpleProductProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1TemplateProcessor.php, module/importer-magento-1/src/Infrastructure/Reader/Magento1CsvReader.php, module/importer/src/Domain/Entity/Import.php, module/importer/src/Infrastructure/Handler/Import/StartImportCommandHandler.php
fix showing sum of processed objects in given import
=> bug(import) fix sum of records/objects in import process

module/account/src/Infrastructure/Persistence/Query/DbalRoleQuery.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Media/PostUploadFile.php
Fix Autocomplete shows an unpublished role.
Change v1 to v2 in one endpoint. 
Issue #
=> fix(role) autocomplite hidden role

module/exporter-shopware-6/src/Application/Model/Shopware6ChannelFormModel.php, module/exporter-shopware-6/src/Infrastructure/Connector/Shopware6Connector.php, module/generator/src/Printer/ErgoPrinter.php, phpcs.xml.dist
=> feature(core) Forced properties types

module/api/src/Infrastructure/Normalizer/ExceptionNormalizer.php, module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php, phpcs.xml.dist
=> feature(core) Removed useless variables

module/mailer/composer.json, module/mailer/tests/Domain/TemplateTest.php, module/mailer/tests/Infrastructure/Sender/Strategy/SymfonyMailerStrategyTest.php
=> configuration(mailer) change package

module/condition/src/Infrastructure/Condition/Calculator/LanguageCompletenessConditionCalculatorStrategy.php, module/condition/src/Infrastructure/Condition/Calculator/ProductCompletenessConditionCalculatorStrategy.php
=> bugfix(condition) calculate completanse strategy

module/product/features/product.feature, module/product/migrations/Version20201102084000.php
fix to short length on database product sku column (128->255)
=> fix(product) fix sku database column length

module/segment/features/segment.feature, module/segment/src/Application/Form/Model/CreateSegmentFormModel.php
Change response about segment validation
Issue #
=> feature(segment) segment create valiadator

module/workflow/features/product-status-attribute.feature, module/workflow/src/Application/Controller/Api/Product/ProductWorkflowAction.php, module/workflow/src/Domain/Provider/ProductStatusProvider.php, module/workflow/src/Infrastructure/Grid/Column/Strategy/StatusAttributeColumnStrategy.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/src/Infrastructure/Query/ProductWorkflowQuery.php
Fix 500 error when fetch workflow status for new language after adding language to language tree
=> fix(workflow) fix 500 errro when fetch stats for new language

module/account/features/account.feature, module/account/src/Application/Form/Model/CreateUserFormModel.php
Change response about user validation 
Issue #
=> feature(account) user valiadator

module/product/src/Infrastructure/Grid/AssociatedProductAvailableChildrenGrid.php, module/product/src/Infrastructure/Persistence/Query/DbalProductChildrenQuery.php
Fixing template field in grid of associated products
=> bug(product) Fixing template field in grid of associated products

config/packages/messenger.yaml, module/exporter-shopware-6/src/Infrastructure/Mapper/CustomField/Shopware6CustomFieldConfigUnitMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/CustomField/Shopware6ProductCustomFieldSetUnitMapper.php, module/exporter-shopware-6/src/Resources/config/services.yml
Update shopware6 mapper. Add attribute unit mapper.
Issue #
=> feature(exporter) shopware6 add unit mapper

module/attribute/features/attribute-autocomplete.feature, module/attribute/src/Application/Controller/Api/Attribute/AttributeAutocompleteAction.php, module/attribute/src/Domain/Query/AttributeQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php, module/attribute/src/Infrastructure/Persistence/Query/Decorator/CacheAttributeQueryDecorator.php
Adding type filter to attribute autocomplete endpoint
=> bug(attribute) Adding type filter to attribute autocomplete endpoint

module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Product.php, module/exporter-shopware-6/src/Resources/config/services.yml
Repairing custom field in product mapping
=> bugfix(exporter) Shopware6 customfield map to product

module/account/migrations/Version20201103070049.php, module/account/src/Domain/Command/User/GenerateUserResetPasswordTokenCommand.php, module/account/src/Domain/Entity/UserResetPasswordToken.php, module/account/src/Domain/Repository/UserResetPasswordTokenRepositoryInterface.php, module/account/src/Domain/ValueObject/ResetToken.php, module/account/src/Infrastructure/Generator/DefaultResetTokenGenerator.php, module/account/src/Infrastructure/Generator/ResetTokenGeneratorInterface.php, module/account/src/Infrastructure/Handler/User/GenerateUserResetPasswordTokenCommandHandler.php, module/account/src/Infrastructure/Persistence/Repository/DbalUserResetPasswordTokenRepository.php, module/account/src/Infrastructure/Persistence/Repository/Mapper/DbalUserResetPasswordTokenMapper.php, module/account/tests/Domain/Command/User/GenerateUserResetPasswordTokenCommandTest.php, module/account/tests/Domain/Entity/UserResetPasswordTokenTest.php, module/account/tests/Domain/ValueObject/ResetTokenTest.php, module/account/tests/Infrastructure/Generator/DefaultResetTokenGeneratorTest.php
Generate reset user password token function.
Issue #911
=> feature(account)add reset token

module/exporter-shopware-6/src/Infrastructure/Connector/Action/Product/Media/GetProductMedia.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductGalleryMapper.php, module/exporter-shopware-6/src/Infrastructure/Model/Product/Shopware6ProductMedia.php, module/exporter-shopware-6/tests/Infrastructure/Model/Product/Shopware6ProductMediaTest.php
Shopware6 media set strong position.
Issue #
=> feature(export)shopware 6 set strong position

module/batch-action/features/batch-action.feature, module/batch-action/migrations/Version20201102124000.php, module/batch-action/src/Application/Controller/Api/GetBatchAction.php, module/batch-action/src/Application/DependencyInjection/ErgonodeBatchActionExtension.php, module/batch-action/src/Application/Request/ParamConverter/BatchActionParamConverter.php, module/batch-action/src/Domain/Model/BatchActionEntryModel.php, module/batch-action/src/Domain/Model/BatchActionInformationModel.php, module/batch-action/src/Domain/Query/BatchActionQueryInterface.php, module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php, module/batch-action/src/Infrastructure/Persistence/Repository/DbalBatchActionRepository.php, module/batch-action/src/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapper.php, module/batch-action/src/Resources/config/nelmio_api_doc.yaml, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapperTest.php, module/product/features/product-batch-action-delete.feature, module/product/src/Infrastructure/Processor/BatchAction/ProductDeleteBatchActionProcessor.php
Add batch action GET information endpoint
sample response:
```
{
"id": "7326be5f-6581-4359-92e7-01a6a255419e",
"type": "product_delete",
"processed_entries": 1,
"all_entries": 1,
"created_at": "2020-11-05T14:42:05+01:00",
"ended_at": "2020-11-05T14:42:05+01:00",
"entries": [
{
"id": "31b75388-41ed-418e-8bf5-7df6b2bd8546",
"messages": [
"Product not found"
]
}
]
}
```
Issue  #902
=> feature(batch action) add get batch action endpoint

.travis.yml
Change composer to version 1.x 
Issue #
=> fix(configuration) travis composer set version

module/product/composer.json
=> fix(product) package json

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1OptionProcessor.php
Fix OptionKey type cast in magento 1 import option step
=> bug(importer-magento-1) fix KeyOption value type cast

module/category/src/Domain/Command/CategoryCommandInterface.php, module/category/src/Domain/Command/CreateCategoryCommand.php, module/category/src/Domain/Command/CreateCategoryCommandInterface.php, module/category/src/Domain/Command/DeleteCategoryCommand.php, module/category/src/Domain/Command/Tree/CreateTreeCommand.php, module/category/src/Domain/Command/Tree/DeleteTreeCommand.php, module/category/src/Domain/Command/Tree/UpdateTreeCommand.php, module/category/src/Domain/Command/UpdateCategoryCommand.php, module/category/src/Infrastructure/Factory/Command/CreateCategoryCommandFactory.php, module/category/src/Infrastructure/Factory/Command/CreateCategoryCommandFactoryInterface.php, module/category/src/Infrastructure/Factory/Command/UpdateCategoryCommandFactory.php, module/category/src/Infrastructure/Factory/Command/UpdateCategoryCommandFactoryInterface.php
Refactoring category command interfaces
=> bug(category) Refactoring category command interfaces

module/channel/src/Application/Provider/CreateChannelCommandBuilderInterface.php, module/channel/src/Application/Provider/UpdateChannelCommandBuilderInterface.php, module/channel/src/Domain/Command/ChannelCommandInterface.php, module/channel/src/Domain/Command/CreateChannelCommandInterface.php, module/channel/src/Domain/Command/DeleteChannelCommand.php, module/channel/src/Domain/Command/ExportChannelCommand.php, module/channel/src/Domain/Command/Schedule/ScheduleCommand.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/exporter-file/src/Domain/Command/CreateFileExportChannelCommand.php, module/exporter-file/src/Domain/Command/UpdateFileExportChannelCommand.php, module/exporter-file/src/Infrastructure/Builder/Command/CreateFileExportChannelCommandBuilder.php, module/exporter-file/src/Infrastructure/Builder/Command/UpdateFileExportChannelCommandBuilder.php, module/exporter-magento-2/src/Domain/Builder/Magento2CreateExportChannelCommandBuilder.php, module/exporter-magento-2/src/Domain/Builder/Magento2UpdateExportChannelCommandBuilder.php, module/exporter-magento-2/src/Domain/Command/CreateMagento2ExportChannelCommand.php, module/exporter-magento-2/src/Domain/Command/UpdateMagento2ExportChannelCommand.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6CreateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6UpdateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Command/CreateShopware6ChannelCommand.php, module/exporter-shopware-6/src/Domain/Command/UpdateShopware6ChannelCommand.php
Refactoring channel command interfaces
=> refactoring(channel) Refactoring channel command interfaces

module/completeness/src/Domain/Command/CompletenessCommandInterface.php, module/completeness/src/Domain/Command/ProductCompletenessCalculateCommand.php, module/condition/src/Domain/Command/ConditionCommandInterface.php, module/condition/src/Domain/Command/CreateConditionSetCommand.php, module/condition/src/Domain/Command/DeleteConditionSetCommand.php, module/condition/src/Domain/Command/UpdateConditionSetCommand.php
Refactoring condition and completeness command interfaces
=> refactoring(completeness, condition)  Refactoring condition and completeness command interfaces

module/comment/src/Domain/Command/CommentCommandInterface.php, module/comment/src/Domain/Command/CreateCommentCommand.php, module/comment/src/Domain/Command/DeleteCommentCommand.php, module/comment/src/Domain/Command/UpdateCommentCommand.php
Refactoring comment command interfaces
=> refactoring(comment) Refactoring comment command interfaces

module/core/src/Domain/Command/CoreCommandInterface.php, module/core/src/Domain/Command/CreateUnitCommand.php, module/core/src/Domain/Command/DeleteUnitCommand.php, module/core/src/Domain/Command/LanguageTree/CreateLanguageTreeCommand.php, module/core/src/Domain/Command/LanguageTree/UpdateLanguageTreeCommand.php, module/core/src/Domain/Command/UpdateLanguageCommand.php, module/core/src/Domain/Command/UpdateUnitCommand.php
Refactoring core command interfaces
=> refactoring(core) Refactoring core command interfaces

module/designer/src/Domain/Command/CreateTemplateCommand.php, module/designer/src/Domain/Command/DeleteTemplateCommand.php, module/designer/src/Domain/Command/TemplateCommandInterface.php, module/designer/src/Domain/Command/UpdateTemplateCommand.php
Refactoring designer command interface
=> refactoring(designer) Refactoring designer command interfaces

module/editor/src/Domain/Command/ChangeProductAttributeValueCommand.php, module/editor/src/Domain/Command/EditorCommandInterface.php, module/editor/src/Domain/Command/PersistProductDraftCommand.php, module/editor/src/Domain/Command/RemoveProductAttributeValueCommand.php
Refactoring editor command interfaces
=> refactoring(editor) Refactoring editor command interfaces

module/exporter-file/src/Domain/Command/Export/EndFileExportCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessAttributeCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessCategoryCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessMultimediaCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessOptionCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessProductCommand.php, module/exporter-file/src/Domain/Command/Export/ProcessTemplateCommand.php, module/exporter-file/src/Domain/Command/Export/StartFileExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/CategoryRemoveShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/CategoryShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/CustomFieldShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/EndShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/ProductShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/PropertyGroupShopware6ExportCommand.php, module/exporter-shopware-6/src/Domain/Command/Export/StartShopware6ExportCommand.php, module/exporter/src/Domain/Command/Export/ProcessExportCommand.php, module/exporter/src/Domain/Command/ExporterCommandInterface.php
Refactoring export command interfaces
=> refactoring(export) Refactoring export command interfaces

module/product-collection/src/Domain/Command/AddProductCollectionElementCommand.php, module/product-collection/src/Domain/Command/AddProductCollectionElementsCommand.php, module/product-collection/src/Domain/Command/CreateProductCollectionCommand.php, module/product-collection/src/Domain/Command/CreateProductCollectionTypeCommand.php, module/product-collection/src/Domain/Command/DeleteProductCollectionCommand.php, module/product-collection/src/Domain/Command/DeleteProductCollectionElementCommand.php, module/product-collection/src/Domain/Command/DeleteProductCollectionTypeCommand.php, module/product-collection/src/Domain/Command/ProductCollectionCommandInterface.php, module/product-collection/src/Domain/Command/UpdateProductCollectionCommand.php, module/product-collection/src/Domain/Command/UpdateProductCollectionElementCommand.php, module/product-collection/src/Domain/Command/UpdateProductCollectionTypeCommand.php
Refactoring product collection command interface
=> refactoring(product collection) Refactoring product collection command interface

module/attribute/src/Infrastructure/Factory/Command/CreateAttributeCommandFactoryInterface.php, module/segment/src/Domain/Command/CalculateProductCommand.php, module/segment/src/Domain/Command/CalculateProductInSegmentCommand.php, module/segment/src/Domain/Command/CalculateSegmentCommand.php, module/segment/src/Domain/Command/CreateSegmentCommand.php, module/segment/src/Domain/Command/DeleteSegmentCommand.php, module/segment/src/Domain/Command/GenerateSegmentCommand.php, module/segment/src/Domain/Command/SegmentCommandInterface.php, module/segment/src/Domain/Command/UpdateSegmentCommand.php
Refactoring segment command interface
=> refactoring(segment) Refactoring segment command interface

module/importer-magento-1/src/Domain/Builder/Magento1CsvCreateSourceCommandBuilder.php, module/importer-magento-1/src/Domain/Builder/Magento1CsvUpdateSourceCommandBuilder.php, module/importer-magento-1/src/Domain/Command/CreateMagento1CsvSourceCommand.php, module/importer-magento-1/src/Domain/Command/UpdateMagento1CsvSourceCommand.php, module/importer/src/Application/Provider/CreateSourceCommandBuilderInterface.php, module/importer/src/Application/Provider/UpdateSourceCommandBuilderInterface.php, module/importer/src/Domain/Command/CreateSourceCommandInterface.php, module/importer/src/Domain/Command/DeleteSourceCommand.php, module/importer/src/Domain/Command/Import/DeleteImportCommand.php, module/importer/src/Domain/Command/Import/EndImportCommand.php, module/importer/src/Domain/Command/Import/ImportCategoryCommand.php, module/importer/src/Domain/Command/Import/ImportGroupingProductCommand.php, module/importer/src/Domain/Command/Import/ImportMultimediaFromWebCommand.php, module/importer/src/Domain/Command/Import/ImportOptionCommand.php, module/importer/src/Domain/Command/Import/ImportSimpleProductCommand.php, module/importer/src/Domain/Command/Import/ImportTemplateCommand.php, module/importer/src/Domain/Command/Import/ImportVariableProductCommand.php, module/importer/src/Domain/Command/Import/StartImportCommand.php, module/importer/src/Domain/Command/Import/StopImportCommand.php, module/importer/src/Domain/Command/Import/UploadFileCommand.php, module/importer/src/Domain/Command/ImporterCommandInterface.php, module/importer/src/Domain/Command/UpdateSourceCommandInterface.php
Refactoring importer command interfaces
=> refactoring(importer) Refactoring importer command interfaces

module/notification/src/Domain/Command/MarkNotificationCommand.php, module/notification/src/Domain/Command/NotificationCommandInterface.php, module/notification/src/Domain/Command/SendNotificationCommand.php, module/transformer/src/Domain/Command/CreateTransformerCommand.php, module/transformer/src/Domain/Command/DeleteTransformerCommand.php, module/transformer/src/Domain/Command/GenerateTransformerCommand.php, module/transformer/src/Domain/Command/TransformerCommandInterface.php
Refactoring notification and transformer command interface
=> refactoring(notification,transformer) Refactoring notification and transformer command interface

module/mailer/src/Domain/Command/MailerCommandInterface.php, module/mailer/src/Domain/Command/SendMailCommand.php, module/multimedia/src/Domain/Command/AddMultimediaCommand.php, module/multimedia/src/Domain/Command/DeleteMultimediaCommand.php, module/multimedia/src/Domain/Command/MultimediaCommandInterface.php, module/multimedia/src/Domain/Command/UpdateMultimediaCommand.php
Refactoring mailer and multmedia command interface.
=> refactoring(mailer,multimedia) Refactoring mailer and multmedia command interface

module/workflow/src/Domain/Provider/ProductStatusProvider.php, module/workflow/tests/Domain/Provider/ProductStatusProviderTest.php
fix generation default status for imported product on edit page
=> bug(workflow) fix create status for imported product on edit page

README.md
=> bugfix(core) Readme typo

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1CategoryProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1MultimediaProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1OptionProcessor.php, module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1TemplateProcessor.php
Fix incorrect records count calculation in magneto 1 import process
=> bugfix(importer) fix record calculation in import process

module/channel/src/Infrastructure/Grid/ExportErrorsGrid.php, module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php, module/exporter-shopware-6/src/Infrastructure/Client/Shopware6ProductMediaClient.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterMultimediaException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterNoMapperException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterNumericAttributeException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterOptionValueException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterProductAttributeException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Shopware6DefaultFolderException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Shopware6ExporterException.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/CustomField/Shopware6ProductCustomFieldSetMultimediaMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/CustomField/Shopware6ProductCustomFieldSetSelectMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Decorator/Shopware6NewProductPriceMapperDecorator.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductNameMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductPriceMapper.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/CustomFiledShopware6ExportProcess.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/ProductShopware6ExportProcess.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/PropertyGroupShopware6ExportProcess.php, module/exporter-shopware-6/tests/Infrastructure/Mapper/Product/Shopware6ProductNameMapperTest.php, module/exporter/migrations/Version20201116083650.php, module/exporter/src/Domain/Entity/ExportLine.php, module/exporter/src/Infrastructure/Persistence/Repository/DbalExportLineRepository.php, module/exporter/src/Infrastructure/Persistence/Repository/Factory/DbalExportLineFactory.php, module/exporter/src/Infrastructure/Persistence/Repository/Mapper/DbalExportLineMapper.php
=> feature(exporter) shopware6 error list

module/completeness/src/Application/Controller/Api/CompletenessReadAction.php, module/completeness/src/Domain/Calculator/CompletenessCalculator.php, module/completeness/src/Domain/Calculator/Strategy/AttributeTemplateElementCompletenessStrategy.php, module/completeness/src/Domain/Calculator/Strategy/TemplateElementCompletenessStrategyInterface.php, module/completeness/src/Domain/Calculator/Strategy/UiTemplateElementCompletenessStrategy.php, module/completeness/src/Infrastructure/Handler/Command/ProductCompletenessCalculateCommandHandler.php, module/completeness/tests/Domain/Calculator/CompletenessCalculatorTest.php, module/completeness/tests/Domain/Calculator/Strategy/AttributeTemplateElementCompletenessStrategyTest.php, module/completeness/tests/Domain/Calculator/Strategy/UiTemplateElementCompletenessStrategyTest.php
Remove using draft in completeness process
Issue #171
=> feature(completeness) remove draft from completeness calculation

module/account/src/Resources/config/services.yml, module/mailer/src/Resources/config/services.yml
=> bug(account, mailer) Fixing Transaltor service

module/condition/src/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategy.php, module/condition/src/Infrastructure/Condition/Configuration/ProductBelongCategoryTreeConditionConfigurationStrategy.php, module/condition/tests/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategyTest.php
Fixing product has status condition.
=> bug(condition) Fixing product has status condition

module/exporter-shopware-6/src/Infrastructure/Calculator/AttributeTranslationInheritanceCalculator.php
Bug fix to empty root value in export Shopware6
=> bugfix(exporter) empty root value

module/exporter-shopware-6/src/Domain/Query/Shopware6CurrencyQueryInterface.php, module/exporter-shopware-6/src/Domain/Query/Shopware6TaxQueryInterface.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/Shopware6ProductVariantChildMapper.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6CurrencyQuery.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalShopware6TaxQuery.php, module/exporter-shopware-6/src/Infrastructure/Synchronizer/CurrencySynchronizer.php, module/exporter-shopware-6/src/Infrastructure/Synchronizer/TaxSynchronizer.php
Shopware 6 bugfix synchronize tax and currency. Clear old data.
=> bugfix(exporter) clear old data currency and tax in db

module/importer/composer.json
=> transformer drop

composer.json, composer.lock, module/core/composer.json
=> bugfix(core)config polyfill

module/segment/src/Infrastructure/Handler/Command/CalculateProductCommandHandler.php, module/segment/src/Infrastructure/Handler/Command/CalculateSegmentCommandHandler.php, module/segment/src/Infrastructure/Service/SegmentProductService.php
=> improvment(segment) Add mass product

composer.lock, symfony.lock
=> feature(core) Update Symfony packages

module/exporter-shopware-6/src/Domain/Repository/Shopware6MultimediaRepositoryInterface.php, module/exporter-shopware-6/src/Infrastructure/Client/Shopware6ProductMediaClient.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Media/DeleteMedia.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Media/GetMedia.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Media/PostCreateMediaAction.php, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Media/PostUploadFile.php, module/exporter-shopware-6/src/Infrastructure/Exception/Shopware6InstanceOfException.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Media.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Repository/DbalShopware6MultimediaRepository.php, module/exporter-shopware-6/tests/Infrastructure/Model/Shopware6MediaTest.php
Export Shopware6 solving problems with a duplicate file name 
Issue #
=> bugfix(exporter) Shopware6 multimedia create/duplicate name problem

module/condition/src/Domain/Query/ConditionSetQueryInterface.php, module/condition/src/Infrastructure/Persistence/Query/DbalConditionSetQuery.php, module/condition/src/Infrastructure/Strategy/Relationship/ProductAttributeRelationshipStrategy.php
Fixing ProductAttribute Relationshop streategy
=> bug(condition) Fixing ProductAttribute Relationshop streategy

module/grid/src/Column/Renderer/DateColumnRenderer.php, module/grid/src/Resources/config/services.yaml
Standardized date formatting on grid
=> refactor(grid) Standardized date formatting on grid

module/product/features/product-attribute-update.feature, module/product/src/Application/Controller/Api/Attribute/DeleteProductsAttributesAction.php, module/product/src/Application/Controller/Api/Attribute/UpdateProductsAttributesAction.php, module/product/src/Application/Factory/Command/ChangeProductAttributeCommandFactory.php, module/product/src/Application/Factory/Command/RemoveProductAttributeCommandFactory.php, module/product/src/Application/Form/Product/Attribute/Delete/DeleteAttributeValueForm.php, module/product/src/Application/Form/Product/Attribute/Delete/DeleteProductAttributeCollectionForm.php, module/product/src/Application/Form/Product/Attribute/Delete/DeleteProductAttributeForm.php, module/product/src/Application/Form/Product/Attribute/Update/UpdateAttributeValueForm.php, module/product/src/Application/Form/Product/Attribute/Update/UpdateAttributeValueTranslationForm.php, module/product/src/Application/Form/Product/Attribute/Update/UpdateProductAttributeCollectionForm.php, module/product/src/Application/Form/Product/Attribute/Update/UpdateProductAttributeForm.php, module/product/src/Application/Model/Product/Attribute/Delete/DeleteAttributeValueFormModel.php, module/product/src/Application/Model/Product/Attribute/Delete/DeleteProductAttributeCollectionFormModel.php, module/product/src/Application/Model/Product/Attribute/Delete/DeleteProductAttributeFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateAttributeValueFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateAttributeValueTranslationFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateProductAttributeCollectionFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateProductAttributeFormModel.php, module/product/src/Domain/Command/Attribute/RemoveProductAttributesCommand.php, module/product/src/Domain/Updater/ProductAttributeUpdater.php, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributesCommandHandler.php
Add delete attribute from product endpoint
=> feature(product) add delete endpoint

composer.json, composer.lock, module/api/composer.json, module/mailer/composer.json
=> feature(core) Update nelmio cors-bundle

config/packages/egronode_workflow.yaml
Remove unnecessary "has status" condition from workflow transition list
=> bug(workflow) remove unnecesery "has status" condition from workflow

module/workflow/migrations/Version20201125114500.php, module/workflow/src/Infrastructure/Persistence/Projector/Product/DbalProductDeletedEventProjector.php
Fix missing DeleteProductEvent projector for workflow product status
=> bug(workflow) add missing DeleteProductEventProjector

module/product/features/product-attribute-update.feature, module/product/src/Application/Model/Product/Attribute/Delete/DeleteAttributeValueFormModel.php, module/product/src/Application/Model/Product/Attribute/Delete/DeleteProductAttributeFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateAttributeValueFormModel.php, module/product/src/Application/Model/Product/Attribute/Update/UpdateProductAttributeFormModel.php
Add missing validators for product exist  and attribute exists
=> feature(products) add missing validators

module/exporter-shopware-6/src/Infrastructure/Mapper/CustomField/Shopware6CustomFieldLabelMapper.php, module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomFieldConfig.php, module/exporter-shopware-6/src/Infrastructure/Model/Basic/Shopware6CustomFieldConfig.php, module/exporter-shopware-6/tests/Infrastructure/Model/AbstractShopware6CustomFieldConfigTest.php, module/exporter-shopware-6/tests/Infrastructure/Model/Basic/Shopware6CustomFieldConfigTest.php
Fix update translation CustomFiled in Shopware6.
- [] Unit Tests
=> bugfix(exporter)Shopware6 Customfield Translate

module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php
Fix completeness calculation query
=> bugfix(completeness) fix completnes query

module/condition/migrations/Version20201119103017.php, module/condition/migrations/Version20201130110000.php
Fix missing segment migrations
- [x ] New and existing unit tests pass locally with my changes
=> bugfix(conditions) fix migration

module/product/src/Infrastructure/Handler/AbstractCreateProductHandler.php
Removed redundant token storage injection
=> bugfix(product) Removed redundant token storage injection

module/channel/src/Infrastructure/Grid/ExportGrid.php, module/grid/src/Renderer/GridRenderer.php, module/importer/src/Infrastructure/Grid/ImportGrid.php
Fix default sort for import and export  history grids suld be from newest to oldest
=> bugfix(import) fix default grid sort

behat.yml.dist, config/packages/lexik_jwt_authentication.yaml, config/packages/nelmio_api_doc.yaml, config/packages/nelmio_cors.yaml, config/services_test.yaml, depfile.yaml, module/authentication/src/Test/Behat/Service/RequestAuthenticator.php, module/core/src/Resources/config/services.yml, module/core/src/Test/Behat/Context/ApiAuthContext.php, module/core/src/Test/Behat/Context/ResolveVarsContext.php, module/core/src/Test/Behat/Context/StoreRestResponseParamContext.php, module/core/src/Test/Behat/Context/UserContext.php, module/core/src/Test/Behat/Service/RequestAuthenticatorInterface.php
Resolved authentication and core modules dependencies
=> bugfix(core) Resolved authentication and core modules dependencies

module/event-sourcing/src/Infrastructure/DomainEventStorageInterface.php, module/event-sourcing/src/Infrastructure/DomainEventStoreInterface.php, module/event-sourcing/src/Infrastructure/Manager/EventStoreManager.php, module/event-sourcing/src/Infrastructure/Snapshot/AggregateSnapshotInterface.php, module/event-sourcing/src/Infrastructure/Snapshot/DbalAggregateSnapshot.php, module/event-sourcing/src/Infrastructure/Storage/CacheDomainEventStorage.php, module/event-sourcing/src/Infrastructure/Storage/DbalDomainEventStorage.php, module/event-sourcing/src/Infrastructure/Store/DbalDomainEventStore.php, module/event-sourcing/tests/Infrastructure/Manager/EventStoreManagerTest.php
Calculation of event sequence on DB
=> feature(event-sourcing) Calculation of event sequence on DB

depfile.yaml, module/account/composer.json, module/account/src/Application/Security/Checker/UserActivityChecker.php, module/account/src/Domain/Entity/User.php, module/account/src/Domain/Entity/UserInterface.php, module/authentication/src/Application/Security/User/User.php
Decoupling account module from authentication
=> bugfix(account) Decoupling account module from authentication

depfile.yaml
Removed redundant depfile entry
=> bugfix(tests) Removed redundant depfile entry

depfile.yaml, module/account/src/Application/Security/Security.php, module/account/src/Domain/Entity/User.php, module/account/src/Infrastructure/Subscriber/LocaleSubscriber.php, module/core/src/Domain/User/AggregateUserInterface.php, module/editor/src/Infrastructure/Handler/ChangeProductAttributeValueCommandHandler.php, module/editor/src/Infrastructure/Handler/RemoveProductAttributeValueCommandHandler.php, module/event-sourcing/src/Infrastructure/Storage/DbalDomainEventStorage.php, module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php, module/product/src/Infrastructure/Handler/AbstractCreateProductHandler.php, module/product/src/Infrastructure/Handler/AbstractUpdateProductHandler.php
Fixed retrieving user from security token
=> bug(core) Fixed retrieving user from security token

module/multimedia/src/Infrastructure/Persistence/Query/DbalMultimediaQuery.php
Multimedia grid relations count. 
Issue #
=> bugfix(multimedia) count relations

depfile.yaml
Improved deptrac configuration
=> feature(tests) Improved deptrac configuration

module/category/features/category-tree-autocomplete.feature, module/category/src/Application/Controller/Api/Tree/CategoryTreeAutocompleteAction.php, module/category/src/Domain/Query/CategoryQueryInterface.php, module/category/src/Domain/Query/TreeQueryInterface.php, module/category/src/Infrastructure/Persistence/Query/DbalTreeQuery.php
Category tree autocomplete endpoint
=> feature(category) Adding category tree autcomplete

module/attribute/features/attribute-autocomplete.feature, module/attribute/src/Application/Controller/Api/Attribute/AttributeAutocompleteAction.php, module/attribute/src/Domain/Query/AttributeQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php, module/attribute/src/Infrastructure/Persistence/Query/Decorator/CacheAttributeQueryDecorator.php
Adding condition so system attributes are not retrieved in autocomplete
=> bug(attribute) Adding condition

build.xml
=> feature(tests) Yaml linter for config files

module/event-sourcing/src/Infrastructure/Storage/DbalDomainEventStorage.php
Locking event_store table for a unique sequence
=> bugfix(event-sourcing) Locking event_store table for a unique sequence

module/event-sourcing/src/Infrastructure/Manager/EventStoreManager.php, module/event-sourcing/src/Infrastructure/Snapshot/AggregateSnapshotInterface.php, module/event-sourcing/src/Infrastructure/Snapshot/DbalAggregateSnapshot.php, module/event-sourcing/tests/Infrastructure/Manager/EventStoreManagerTest.php
Avoid snapshotting invalid aggregate root
=> bugfix(event-sourcing) Avoid snapshotting invalid aggregate root

.env, config/packages/ergonode_account.yaml, config/packages/security.yaml, depfile.yaml, module/account/composer.json, module/account/features/account-token.feature, module/account/src/Application/Controller/Api/PasswordToken/UserResetPasswordTokenGenerateAction.php, module/account/src/Application/Controller/Api/UserResetPasswordTokenAction.php, module/account/src/Application/DependencyInjection/Configuration.php, module/account/src/Application/DependencyInjection/ErgonodeAccountExtension.php, module/account/src/Application/Form/GenerateUserTokenForm.php, module/account/src/Application/Form/Model/GenerateUserTokenModel.php, module/account/src/Application/Validator/Constraints/AvailableHostConstraint.php, module/account/src/Application/Validator/Constraints/AvailableHostConstraintValidator.php, module/account/src/Domain/Command/User/GenerateUserResetPasswordTokenCommand.php, module/account/src/Domain/Event/User/UserResetTokenGeneratedEvent.php, module/account/src/Domain/ResetTokenMail.php, module/account/src/Infrastructure/Handler/Event/UserResetTokenGeneratedEventHandler.php, module/account/src/Infrastructure/Handler/User/GenerateUserResetPasswordTokenCommandHandler.php, module/account/src/Resources/config/nelmio_api_doc.yaml, module/account/src/Resources/config/routes.yml, module/account/src/Resources/config/services.yml, module/account/src/Resources/translations/mailer.en.yaml, module/account/src/Resources/translations/mailer.pl.yaml, module/account/src/Resources/views/message/token.html.twig, module/account/tests/Application/Validator/Constraints/AvailableHostConstraintValidatorTest.php, module/account/tests/Domain/Command/User/GenerateUserResetPasswordTokenCommandTest.php, module/account/tests/Domain/Event/User/UserResetTokenGeneratedEventTest.php
Endpint POST `accounts/token/generate`
`      {
"email": "test@ergonode.com",
"url": "http://localhost/rest?token="
}`
Issue #911
=> feature(account)Generate token endpint and send mail event

module/product/src/Application/Controller/Api/ProductReadInheritedValuesByLanguageAction.php
Adding langauge inheritance endpoint
=> Adding langauge inheritance endpoint

module/account/src/Application/Controller/Api/PasswordToken/UserRestPasswordTokenApplyAction.php, module/account/src/Application/Form/Model/UserApplyTokenModel.php, module/account/src/Application/Form/UserApplyTokenForm.php, module/account/src/Domain/Command/User/ApplyUserResetTokenCommand.php, module/account/src/Infrastructure/Handler/User/ApplyUserResetTokenCommandHandler.php, module/account/src/Resources/config/nelmio_api_doc.yaml, module/account/tests/Application/Validator/Constraints/AvailableTokenConstraintValidatorTest.php, module/account/tests/Domain/Command/User/ApplyUserResetTokenCommandTest.php, module/account/tests/Domain/Validator/TokenValidatorTest.php
Endpint `POST`
`{ "token": ";kjlkfjsdlkj", "password": "new_password", "passwordRepeat": "new_password" }`
Issue #911
Issue #
=> feature(accont) token apply

module/attribute/src/Domain/Query/OptionQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php, module/exporter-file/src/Infrastructure/Processor/ProductProcessor.php, module/exporter-file/tests/Infrastructure/Processor/ProductProcessTest.php
Identifying options with key not id on export
=> bugfix(exporter) Identifying options with key not id on export

config/packages/ergonode_translation_deepl.yaml, config/packages/translation_deepl.yml, module/translation-deepl/src/Application/DependencyInjection/Configuration.php, module/translation-deepl/src/Application/DependencyInjection/ErgonodeTranslationDeeplExtension.php, module/translation-deepl/src/Resources/config/services.yml
Module configuration for the authentication key
=> bugfix(translation deepl) Module configuration for the authentication key

module/attribute/src/Infrastructure/Mapper/Strategy/TextareaAttributeMapperStrategy.php
Adding length textarea value validation
=> Adding length textarea value validation

module/exporter-shopware-6/migrations/Version20201211072933.php, module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php, module/exporter-shopware-6/src/Application/Model/Shopware6ChannelFormModel.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6CreateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Builder/Shopware6UpdateChannelCommandBuilder.php, module/exporter-shopware-6/src/Domain/Command/CreateShopware6ChannelCommand.php, module/exporter-shopware-6/src/Domain/Command/UpdateShopware6ChannelCommand.php, module/exporter-shopware-6/src/Domain/Entity/Shopware6Channel.php, module/exporter-shopware-6/src/Infrastructure/Handler/CreateShopware6ChannelCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Handler/UpdateShopware6ChannelCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Processor/Step/ProductCrossSellingStep.php, module/exporter-shopware-6/src/Resources/config/services.yml, module/exporter-shopware-6/tests/Domain/Command/CreateShopware6ChannelCommandTest.php, module/exporter-shopware-6/tests/Domain/Command/UpdateShopware6ChannelCommandTest.php, module/exporter-shopware-6/tests/Domain/Entity/Shopware6ChannelTest.php
=> feature(exporter) Shopware6 export CrossSelling configuration

module/attribute/src/Infrastructure/Mapper/Strategy/TextareaAttributeMapperStrategy.php, module/attribute/src/Infrastructure/Provider/Strategy/TextareaAttributeValueConstraintStrategy.php
Removing characters limit for textarea attribute value
=> bug(attribute) Removing characters limit for textarea attribute value

module/account/src/Application/Form/Model/GenerateUserTokenModel.php, module/account/src/Application/Form/Model/UserApplyTokenModel.php, module/account/src/Resources/config/nelmio_api_doc.yaml
=> bugfix(account)Generate token

module/product/features/product-gallery-attribute-manipulation.feature, module/product/features/product-global-numeric-attribute-manipulation.feature, module/product/features/product-global-price-attribute-manipulation.feature, module/product/features/product-global-text-attribute-manipulation.feature, module/product/features/product-global-textarea-attribute-manipulation.feature, module/product/features/product-global-unit-attribute-manipulation.feature, module/product/features/product-local-file-attribute-manipulation.feature, module/product/features/product-local-gallery-attribute-manipulation.feature, module/product/features/product-local-image-attribute-manipulation.feature, module/product/features/product-local-multi-select-attribute-manipulation.feature, module/product/features/product-local-numeric-attribute-manipulation.feature, module/product/features/product-local-price-attribute-manipulation.feature, module/product/features/product-local-select-attribute-manipulation.feature, module/product/features/product-local-text-attribute-manipulation.feature, module/product/features/product-local-textarea-attribute-manipulation.feature, module/product/features/product-local-unit-attribute-manipulation.feature, module/product/src/Application/Controller/Api/Attribute/UpdateProductAttributeAction.php
Adding behat tests for product attribute value validation
=> feature(product) Adding behat tests for product attribute value validation

src/Resources/fixtures/develop/collections.yaml, src/Resources/fixtures/fixture.yaml
=> feature(fixtures) Adding new collection type

.env
Delete old rabbit queue configuration
Issue #
=> configuration(core) .env delete not use quque

module/product-collection/features/product-collections-from-skus.feature, module/product/src/Infrastructure/Validator/Sku.php
Fixing incorrect error message
=> bug(product) Fixing incorrect error message

module/authentication/src/Application/Security/Authenticator/FormAuthenticator.php, module/authentication/src/Application/Security/Provider/EmailUserProvider.php, module/authentication/tests/Application/Security/Authenticator/FormAuthenticatorTest.php, module/authentication/tests/Application/Security/Provider/EmailUserProviderTest.php
Fixing security gap - authentication
=> Fixing secuirty gap authentication

module/exporter-shopware-6/migrations/Version20201211072933.php
Added foregin key in Shopware6 tables. 
Issue #
=> feature(exporter) Shopware6 add foregin key

config/packages/flysystem.yaml
=> bugfix(core) Removed redundant storage

module/completeness/src/Application/Controller/Api/CompletenessReadAction.php, module/completeness/src/Domain/Query/CompletenessQueryInterface.php, module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php
Change /products/{product}/completeness endpoint to return real-time calculated information instead of return asynchronized calculated results
=> bugfix(completenes) change completenes get endpoint to return realtime data

module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php, module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/ProductToLongValueException.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/ProductSEOMetaDescriptionMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/ProductSEOMetaTitleMapper.php, module/exporter-shopware-6/tests/Infrastructure/Mapper/Product/ProductSEOMetaDescriptionMapperTest.php, module/exporter-shopware-6/tests/Infrastructure/Mapper/Product/ProductSEOMetaTitleMapperTest.php
Add Shopware6 to long value exeption in SEO attribute value.
=> feature(exporter) Shopware6 to long SEO attribute value

module/exporter-shopware-6/src/Domain/Query/ProductCrossSellingQueryInterface.php, module/exporter-shopware-6/src/Infrastructure/Handler/Export/ProductCrossSellingRemoveExportCommandHandler.php, module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalProductCrossSellingQuery.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/ProductCrossSellingExportProcess.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/ProductCrossSellingRemoveExportProcess.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/ProductCrossSellingRemoveProductExportProcess.php
Remove Cross-Selling in Shopware6 after removing in Ergonode. 
Issue #655
=> feature(exporter) remove cross-selling in shopware6

module/channel/src/Domain/Query/ChannelQueryInterface.php, module/channel/src/Infrastructure/Persistence/Query/DbalChannelQuery.php, module/exporter-shopware-6/src/Infrastructure/Strategy/Relationship/ProductCollectionShopware6ChannelRelationshipStrategy.php
Lock delete used Collection in Shopware6Channel.
Issue #
=> feature(exporter) Shopware6 lock delete CrossSell

module/exporter-shopware-6/src/Infrastructure/Persistence/Query/DbalProductCrossSellingQuery.php
Change spelling in Shopware6 Query.
Issue #
=> bugfix(exporter) shopware6 spelling in query

module/channel/src/Application/Form/Model/SchedulerModel.php, module/channel/src/Application/Form/SchedulerForm.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/channel/src/Domain/Entity/Scheduler.php, module/exporter-file/features/scheduler.feature
=> feature(channel) extend scheduler hour range

module/workflow/migrations/Version20210119140233.php, module/workflow/src/Infrastructure/Persistence/Projector/Product/DbalProductValueChangedEventProjector.php
Fixing a status change in another language.
Issue #
=> bugfix(workflow) Change status in new language

module/account/src/Infrastructure/Strategy/Relationship/RoleUserRelationshipStrategy.php, module/attribute/src/Infrastructure/Strategy/Relationship/AttributeAttributeGroupRelationshipStrategy.php, module/attribute/src/Infrastructure/Strategy/Relationship/AttributeUnitRelationshipStrategy.php, module/condition/src/Infrastructure/Strategy/Relationship/ProductAttributeRelationshipStrategy.php, module/designer/src/Infrastructure/Strategy/Relationship/ProductTemplateRelationshipStrategy.php, module/designer/src/Infrastructure/Strategy/Relationship/TemplateAttributeRelationshipStrategy.php, module/designer/src/Infrastructure/Strategy/Relationship/TemplateMultimediaRelationshipStrategy.php, module/exporter-shopware-6/src/Infrastructure/Strategy/Relationship/ProductCollectionShopware6ChannelRelationshipStrategy.php, module/product-collection/src/Infrastructure/Relationship/ProductProductCollectionRelationshipStrategy.php, module/product-collection/src/Infrastructure/Strategy/Relationship/ProductCollectionProductCollectionTypeRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ChildrenProductRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductAttributeRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductCategoryRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductMultimediaRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductOptionRelationshipStrategy.php, module/segment/src/Infrastructure/Strategy/Relationship/ConditionSetSegmentRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/DefaultStatusRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusProductRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusWorkflowRelationshipStrategy.php
Fixed relationships validations messages
=> bugfix(core) Fixed relationships validations messages

module/account/src/Domain/ResetTokenMail.php, module/account/src/Infrastructure/Handler/Event/UserResetTokenGeneratedEventHandler.php, module/account/src/Resources/translations/mailer.en.yaml, module/account/src/Resources/translations/mailer.pl.yaml, module/account/src/Resources/views/message/token.html.twig, module/mailer/src/Resources/views/layout/default.html.twig
Change mail body in reset password. 
Issue #911
=> feature(account) change rest mail body

module/account/src/Domain/Mail/ResetTokenMail.php, module/account/src/Domain/Mail/UserPasswordChangedMail.php, module/account/src/Infrastructure/Handler/Event/UserPasswordChangedEventHandler.php, module/account/src/Resources/translations/mailer.en.yaml, module/account/src/Resources/translations/mailer.pl.yaml, module/account/src/Resources/views/message/password_changed.html.twig
Send mail after the changed password.
Issue #911
=> feature(account) send mail after change pasword

module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeAttributeReader.php
Fix missing attribute import validation in ergonode zip import
=> fix(import) fix missing attribute import validations

module/batch-action/features/batch-action.feature, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Application/Form/Model/BatchActionFilterFormModel.php, module/batch-action/src/Application/Form/Model/BatchActionFilterIdsFormModel.php, module/batch-action/src/Application/Form/Model/BatchActionFormModel.php, module/batch-action/src/Application/Form/Type/BatchActionFilterIdsType.php, module/batch-action/src/Application/Form/Type/BatchActionFilterType.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Domain/Command/ProcessBatchActionEntryCommand.php, module/batch-action/src/Domain/ValueObject/BatchActionFilter.php, module/batch-action/src/Domain/ValueObject/BatchActionIds.php, module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/tests/Domain/Command/CreateBatchActionCommandTest.php, module/batch-action/tests/Domain/ValueObject/BatchActionFilterTest.php, module/batch-action/tests/Domain/ValueObject/BatchActionIdsTest.php, module/batch-action/tests/Infrastructure/Handler/CreateBatchActionCommandHandlerTest.php, module/product/features/grouping-product-batch-action-delete.feature, module/product/features/simple-product-batch-action-delete.feature, module/product/features/variable-product-batch-action-delete.feature
Extend JSON contract API in a batch action.
Issue #
=> feature(batch-action) extend json contract api

module/mailer/src/Resources/translations/mailer.en.yaml, module/mailer/src/Resources/translations/mailer.pl.yaml, module/mailer/src/Resources/views/layout/default.html.twig
=> feature(mailer)change footer in mail

module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Provider/BatchActionFilterIdsInterface.php, module/batch-action/src/Infrastructure/Provider/BatchActionFilterIdsProvider.php, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Infrastructure/Handler/CreateBatchActionCommandHandlerTest.php, module/grid/src/FilterGridConfiguration.php, module/product/src/Domain/Query/ProductQueryInterface.php, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php, module/product/src/Infrastructure/Filter/BatchAction/ProductDeleteBatchActionFilter.php, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php, module/product/src/Infrastructure/Persistence/Query/Decorator/CacheProductQueryDecorator.php, module/product/src/Resources/config/services.yml, module/product/tests/Infrastructure/Filter/BatchAction/ProductBatchActionFilterTest.php
Add provider batch action item filter.
Issue #
=> feature(batch-action) item filter provider

module/attribute/src/Infrastructure/Grid/AttributeGrid.php, module/grid/src/Column/AbstractColumn.php, module/grid/src/Column/LinkColumn.php, module/grid/src/ColumnInterface.php, module/grid/src/Renderer/RowRenderer.php
Add support for reddening grid colum in different view type
Issue #
=> feature(grid) add support for different grid view

module/mailer/src/Resources/views/layout/default.html.twig
Drop https in footer mailer. 
Issue #
=> feature(mailer) fotter https

module/batch-action/src/Resources/config/nelmio_api_doc.yaml
Change api doc in batch action
Issue #
=> feature(batch-action) change api doc

module/batch-action/src/Application/Form/Model/BatchActionFormModel.php, module/batch-action/src/Application/Form/Model/BatchActionPayloadModel.php, module/batch-action/src/Application/Form/Model/BatchActionValueTranslationModel.php, module/batch-action/src/Application/Form/Type/BatchActionPayloadType.php, module/batch-action/src/Application/Form/Type/BatchActionValueTranslationType.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Domain/Command/ProcessBatchActionEntryCommand.php, module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Handler/ProcessBatchActionEntryCommandHandler.php, module/batch-action/src/Infrastructure/Provider/BatchActionProcessorInterface.php, module/product/features/product-batch-action-change-attribute.feature, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php, module/product/src/Infrastructure/Processor/BatchAction/ProductChangeAttributeBatchActionProcessor.php, module/product/src/Infrastructure/Processor/BatchAction/ProductDeleteBatchActionProcessor.php
Edit attribute value in a product. 
Issue #
=> feature(batch-action) edit attribute value in product

module/channel/features/channel.feature, module/channel/src/Application/Controller/Api/ChannelTypeConfigurationAction.php, module/importer/features/source.feature, module/importer/src/Application/Controller/Api/Source/SourceTypeConfigurationAction.php
Add 404 response code for not exists dynamic form configuration
=> featur(export) add support for not exists import/export dynamic form configuration

module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetAttributeRelationshipStrategy.php
Fixed condition set attribute relation message
=> bugfix(condition) Fixed condition set attribute relation message

module/segment/src/Infrastructure/Handler/Command/DeleteSegmentCommandHandler.php, module/segment/tests/Infrastructure/Handler/Command/DeleteSegmentCommandHandlerTest.php
Removing condition set with segment
=> bugfix(segment) Removing condition set with segment

module/importer/src/Infrastructure/Exception/ImportException.php
Fixed invalid instantiation of ImportException
=> bugfix(import) Fixed invalid instantiation of ImportException

module/exporter-file/src/Application/Form/ExporterFileConfigurationForm.php, module/exporter-file/src/Infrastructure/Dictionary/WriterTypeDictionary.php, module/exporter-file/src/Resources/translations/channel.en.yaml, module/exporter-file/src/Resources/translations/channel.pl.yaml, module/exporter-file/src/Resources/translations/exporter.en.yaml, module/exporter-file/src/Resources/translations/exporter.pl.yaml
=> bugfix(channel) add missing translations

module/channel/src/Domain/Query/ExportQueryInterface.php, module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php, module/channel/src/Infrastructure/Strategy/Relationship/ActiveExportRelationshipStrategy.php, module/channel/src/Infrastructure/Strategy/Relationship/ChannelActiveExportRelationshipStrategy.php, module/importer/src/Domain/Query/ImportQueryInterface.php, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php, module/importer/src/Infrastructure/Strategy/Relationship/ActiveImportRelationshipStrategy.php, module/importer/src/Infrastructure/Strategy/Relationship/SourceActiveImportRelationshipStrategy.php
Add lock relation when has active processes.
Issue #
=> feature(channel/importer) lock delete when active processes

module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php, module/importer-ergonode-1/src/Infrastructure/Model/AttributeModel.php, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php
Refactor get processes query 
Issue #
=> refactor(import/export) get processes query

module/core/src/Infrastructure/EventListener/ConnectionWorkerEventSubscriber.php, module/core/tests/Infrastructure/EventListener/ConnectionWorkerEventSubscriberTest.php
Improved reconnecting to DB on lost connection
=> refactor(core) Improved reconnecting to DB on lost connection

module/exporter-file/src/Infrastructure/Handler/Export/StartProcessCommandHandler.php, module/exporter-file/src/Infrastructure/Processor/OptionProcessor.php, module/exporter-file/tests/Infrastructure/Processor/CategoryProcessorTest.php, module/exporter-file/tests/Infrastructure/Processor/OptionProcessorTest.php, module/importer-ergonode-1/src/Infrastructure/Model/OptionModel.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeOptionReader.php, module/importer/src/Domain/Command/Import/ImportOptionCommand.php, module/importer/src/Infrastructure/Handler/ImportOptionCommandHandler.php, module/importer/tests/Domain/Command/Import/ImportOptionCommandTest.php
Change export and import Option by code
Issue #
=>  feature(exporter/import) Ergonode Option by Code

module/importer/src/Resources/config/routes.yml
=> bugfix(importer) Added missing routing config

module/exporter-file/src/Infrastructure/Handler/Export/StartProcessCommandHandler.php, module/exporter-file/src/Infrastructure/Processor/AttributeProcessor.php, module/exporter-file/tests/Infrastructure/Handler/Export/StartProcessCommandHandlerTest.php, module/exporter-file/tests/Infrastructure/Processor/AttributeProcessorTest.php, module/importer-ergonode-1/src/Domain/Command/Import/ImportAttributeCommand.php, module/importer-ergonode-1/src/Infrastructure/Handler/Import/ImportAttributeCommandHandler.php, module/importer-ergonode-1/src/Infrastructure/Model/AttributeModel.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeAttributesProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeAttributeReader.php
Change export and import Attribute by code
Issue #
=> feature(exporter/import) Ergonode Attribuite by Code

module/exporter-file/src/Infrastructure/Handler/Export/StartProcessCommandHandler.php, module/exporter-file/src/Infrastructure/Processor/ProductProcessor.php, module/exporter-file/tests/Infrastructure/Processor/ProductProcessTest.php, module/importer-ergonode-1/src/Infrastructure/Model/ProductModel.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeProductReader.php
Change export and import Product by SKU
Issue #
=> feature(exporter/import) Ergonode Product by SKU

module/importer/src/Application/DependencyInjection/ErgonodeImporterExtension.php, module/importer/src/Infrastructure/Action/Process/Product/ImportProductAttributeBuilder.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductPriceAttributeStrategy.php, module/importer/src/Resources/config/services.yml, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductPriceAttributeStrategyTest.php
Validating price attribute value
=> feature(import) Validating price attribute value

module/importer/features/notification.feature, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php
Fix sql query error in import notification endpoint
=> buf(import) fix import notification endpoint

module/account/migrations/Version20180401062601.php, module/attribute/migrations/Version20180401083834.php, module/category/migrations/Version20180619083700.php, module/channel/migrations/Version20191120151840.php, module/comment/migrations/Version20191104140000.php, module/condition/migrations/Version20190910151314.php, module/core/migrations/Version20180610093112.php, module/designer/migrations/Version20180719132703.php, module/importer/migrations/Version20180617083829.php, module/importer/migrations/Version20180618134343.php, module/multimedia/migrations/Version20180807065948.php, module/product-collection/migrations/Version20200127083123.php, module/product/migrations/Version20180619083830.php, module/product/migrations/Version20201102084000.php, module/reader/migrations/Version20180619100000.php, module/segment/migrations/Version20190130104000.php, module/value/migrations/Version20180619083831.php, module/workflow/migrations/Version20190818160000.php
Fix incorrect use of connection property in migrations.
=> bugfix(migration) fix inccorect connection use

module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductNumericAttributeStrategy.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductNumericAttributeStrategyTest.php
Validating numeric attribute value
=> feature(importer) Validating numeric attribute value

module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductPriceAttributeStrategy.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductNumericAttributeStrategyTest.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductPriceAttributeStrategyTest.php
Fixed attribute price type and tests
=> bugfix(import) Fixed attribute price type and tests

module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductDateAttributeStrategy.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductDateAttributeStrategyTest.php
Validating date attribute value
=> feature(import) Validating date attribute value

module/exporter-file/src/Infrastructure/Handler/Export/StartProcessCommandHandler.php, module/exporter-file/src/Infrastructure/Processor/TemplateProcessor.php, module/exporter-file/tests/Infrastructure/Processor/TemplateProcessorTest.php, module/importer-ergonode-1/src/Domain/Command/Import/ImportTemplateCommand.php, module/importer-ergonode-1/src/Infrastructure/Handler/Import/ImportTemplateCommandHandler.php, module/importer-ergonode-1/src/Infrastructure/Model/TemplateModel.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeTemplateProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeTemplateReader.php
Change export and import Template by code
Issue #
=> feature(exporter/import) Ergonode only template code 

module/attribute/src/Infrastructure/Relation/AttributeMultimediaRelation.php, module/designer/src/Infrastructure/Relation/TemplateMultimediaRelation.php, module/product/migrations/Version20210105100800.php, module/product/src/Infrastructure/Relation/ProductMultimediaRelation.php
Changes to privileges 
Issue #
=> feature(all) change privilege system

src/Resources/fixtures/develop/templates.yaml
=> bug(fixtures) Fixing developer fixtures

module/grid/src/Resources/config/services.yaml, module/product/src/Infrastructure/Factory/DataSet/DbalQueryBuilderProductDataSetFactory.php, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php, module/product/src/Infrastructure/Persistence/DataSet/DbalQueryBuilderProductDataSet.php, module/product/src/Infrastructure/Provider/ProductIdsProvider.php, module/product/tests/Infrastructure/Filter/BatchAction/ProductBatchActionFilterTest.php
Rename class after merge #1138 
Issue #
=> feature(batch-action) get only id

src/Resources/fixtures/develop/templates.yaml
=> bug(fixtures) Fixing develop fixtures

module/grid/src/Column/AbstractColumn.php, module/grid/src/Column/LinkColumn.php, module/grid/src/ColumnInterface.php, module/grid/src/Renderer/RowRenderer.php
Add grid type support for grid rendering.
=> feature(grid) add support for different grid view (#1088)

module/importer/src/Infrastructure/Handler/Import/StartImportCommandHandler.php
Fix incorrect place of import saving in magento 1 import process.
=> bugfix(importer) fix elements count save - magento 1 import process

module/category/src/Domain/Query/TreeQueryInterface.php, module/category/src/Infrastructure/Persistence/Query/DbalTreeQuery.php, module/category/src/Infrastructure/Strategy/Relationship/CategoryInCategoryTreeRelationshipStrategy.php
Add missing delete category relation check that category is used in category tree.
=> bugfix(category) add missing delete category relation check

module/attribute/features/attribute-grid.feature, module/attribute/src/Infrastructure/Grid/AttributeGridBuilder.php
Fix missing scope column values in attribute grid
=> bugfix(attribute) fix scope grid filter values

module/channel/src/Application/Controller/Api/Scheduler/SchedulerChangeAction.php, module/channel/src/Application/Form/Model/SchedulerModel.php, module/channel/src/Application/Form/SchedulerForm.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/channel/src/Domain/Entity/Scheduler.php, module/channel/src/Infrastructure/Handler/UpdateScheduleCommandHandler.php, module/channel/src/Resources/config/nelmio_api_doc.yaml, module/channel/tests/Domain/Entity/SchedulerTest.php, module/exporter-file/features/scheduler.feature
Fixed deactivating scheduler clearing all its data
=> bugfix(channel) Fixed deactivating scheduler clearing all its data

module/exporter-shopware-6/src/Infrastructure/Connector/Action/Product/GetProductList.php
Patch for incorrect objects returned from Shopware.
Issue #
=> bugfix(exporter-shopware-6)Change GetProductList::parseContent after Shopware 6.3.5.1 SEO bug

module/event-sourcing/src/Application/DependencyInjection/CompilerPass/ProjectorCompilerPass.php
During projection, the system returns an error 
```
Deprecated: Function ReflectionType::__toString() is deprecated in /srv/app/module/event-sourcing/src/Application/DependencyInjection/CompilerPass/ProjectorCompilerPass.php on line 64
Call Stack:
0.0044     394960   1. {main}() /srv/app/vendor/behat/behat/bin/behat:0
0.1327    5971920   2. Behat\Testwork\Cli\Application->run(???, ???) /srv/app/vendor/behat/behat/bin/behat:34
0.1547    6322144   3. Behat\Testwork\Cli\Application->doRun(???, ???) /srv/app/vendor/symfony/console/Application.php:149
0.1548    6322144   4. Behat\Testwork\Cli\Application->createCommand(???, ???) /srv/app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:122
4.2778   11606704   5. Symfony\Component\DependencyInjection\ContainerBuilder->get(???, ???) …
```
=> bugfix(event-sourcing) Removed deprecated ReflectionType::__toString method usage

module/batch-action/features/batch-action-get-templates.feature, module/batch-action/src/Application/Controller/Api/GetTemplatesByBatchAction.php, module/batch-action/src/Infrastructure/JMS/Serializer/Handler/BatchActionFilterIdsFormModelHandler.php
Removing body from GET request and changing it to query parameters
=> bug(batch-action) removing body from get request

module/exporter-shopware-6/src/Infrastructure/Mapper/Product/ProductSEOMetaDescriptionMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Product/ProductSEOMetaTitleMapper.php
```
TypeError(code: 0): mb_strlen() expects parameter 1 to be string, null given at 
```
Issue #
=> bugfix(exporter-shopware-6)change null exeption in seo mapper

module/core/src/Application/Exception/DeserializationException.php, module/core/src/Application/Exception/SerializationException.php, module/core/src/Application/Exception/SerializerException.php, module/core/src/Application/Serializer/JMSSerializer.php, module/core/src/Application/Serializer/NormalizerInterface.php, module/core/src/Application/Serializer/SerializerInterface.php
Fixed serializer exceptions placement and added annotations
=> bugfix(core) Fixed serializer exceptions placement and added annotations

module/core/src/Application/Serializer/JMSSerializer.php, module/core/src/Application/Serializer/NormalizerInterface.php
Opened up normalizer to support various data
=> refactor(core) Opened up normalizer to support various data

module/core/src/Application/DependencyInjection/CompilerPass/SerializerCompilerPass.php, module/core/src/Application/Serializer/Normalizer/ObjectPropertyNormalizer.php, module/core/src/Application/Serializer/Normalizer/ScalarValueObjectNormalizer.php, module/core/src/Application/Serializer/SymfonySerializer.php, module/core/src/ErgonodeCoreBundle.php, module/core/src/Resources/config/services.yml, module/core/tests/Application/Serializer/Normalizer/Fixtures/AbstractClass.php, module/core/tests/Application/Serializer/Normalizer/Fixtures/PrivateConstructorClass.php, module/core/tests/Application/Serializer/Normalizer/ScalarValueObjectNormalizerTest.php
=> feature(core) Symfony serializer implementation

module/grid/src/Column/Renderer/LinkColumnRenderer.php, module/product/src/Infrastructure/Grid/Builder/Query/AbstractAttributeDataSetBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/FileAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/GalleryAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php
Optimise product grid query building
Add local cache to LinkColumnRendeder to decrease number of database queries
Issue #1167
=> performance(grid) optymise product grid query building

module/grid/src/Column/Renderer/LinkColumnRenderer.php
Reducing  number of queries to the database when rendering Grid with link column.
Issue #1168
th
=> performance(grid) reducing the number of queries to the database

module/channel/src/Infrastructure/Persistence/Query/DbalSchedulerQuery.php
```
Datetime field overflow: 7 ERROR:  date/time field value out of range: \"48:20\" 
```
Issue #
=> bugfix(channel) Sheduler read expected time fix

module/attribute/features/attribute-validation.feature, module/attribute/src/Application/Controller/Api/Attribute/AttributeValidationAction.php
=> feature(attribute) Validation of attribute value

module/account/src/Resources/translations/mailer.en.yaml, module/account/src/Resources/translations/mailer.pl.yaml, module/account/src/Resources/views/message/password_changed.html.twig, module/account/src/Resources/views/message/token.html.twig, module/mailer/src/Resources/translations/mailer.en.yaml, module/mailer/src/Resources/translations/mailer.pl.yaml, module/mailer/src/Resources/views/layout/default.html.twig
Change body in reset password mail. 
Issue #
=> feature(mailer)Change body reset mail

module/category/features/category-tree-grid.feature, module/category/features/category-tree-privileges.feature, module/category/features/category-tree.feature, module/category/src/Infrastructure/Persistence/Projector/Tree/DbalCategoryTreeCategoriesChangedEventProjector.php, module/category/src/Infrastructure/Persistence/Projector/Tree/DbalCategoryTreeDeletedEventProjector.php
Fix category tree projectors.
- DbalCategoryTreeDeletedEventProjector
- DbalCategoryTreeCategoriesChangedEventProjector
Issue #
=> bugfix(category tree) fix category tree projection

composer.lock
Issue # 
- [*] Bug fix (non-breaking change which fixes an issue)
=> symfony-flex update

.github/workflows/tests.yml
=> feature(tests) Allowed composer 2.0 in CI

.github/CONTRIBUTING.md
=> bugfix(documentation) Fixed contribution guidelines regarding branches

.env, config/packages/messenger.yaml
=> configuration(messenger) Add new queue for batch action

module/batch-action/src/Application/Controller/Api/GetTemplatesByBatchAction.php, module/batch-action/src/Resources/config/services.yml, module/core/src/Resources/config/services.yml
=> bugfix(batch-action) Fixed JMSSerializer usage to normalizer

config/packages/messenger.yaml, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Application/DependencyInjection/Configuration.php, module/batch-action/src/Application/DependencyInjection/ErgonodeBatchActionExtension.php, module/batch-action/src/Resources/config/messenger.yaml
=> feature(batch-action) Async mode on

module/importer/src/Domain/Command/Import/Attribute/AbstractImportAttributeCommand.php, module/importer/src/Infrastructure/Action/FileAttributeImportAction.php, module/importer/src/Infrastructure/Action/GalleryAttributeImportAction.php, module/importer/src/Infrastructure/Action/MultiSelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/SelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/TextAttributeImportAction.php
Fix incorrect attribute creation in import handlers.
=> bugfix(importer) fix attribute import actions

module/importer-ergonode-1/src/Infrastructure/Factory/Product/GroupingProductCommandFactory.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeAttributeReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeCategoryReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeOptionReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeProductReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeTemplateElementReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeTemplateReader.php
Remove of redundant settings empty property in ergonode importer csv file readers.
=> bugfix(import) fix unnecesery settings empty property

module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Infrastructure/Provider/BatchActionFilterIdsInterface.php, module/product/features/product-batch-action-delete.feature, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php
=> bugfix(batch-action) Handling no filter passed

phpunit.xml.dist
=> ci: PHPUnit fails on warnings

module/importer-ergonode-1/src/Infrastructure/Factory/Product/GroupingProductCommandFactory.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeAttributeReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeCategoryReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeOptionReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeProductReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeTemplateElementReader.php, module/importer-ergonode-1/src/Infrastructure/Reader/ErgonodeTemplateReader.php, module/importer/src/Domain/Command/Import/Attribute/AbstractImportAttributeCommand.php, module/importer/src/Infrastructure/Action/FileAttributeImportAction.php, module/importer/src/Infrastructure/Action/GalleryAttributeImportAction.php, module/importer/src/Infrastructure/Action/MultiSelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/SelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/TextAttributeImportAction.php, module/product/tests/Infrastructure/Filter/BatchAction/ProductBatchActionFilterTest.php, phpunit.xml.dist
=> Batch action tests fix

depfile.yaml, module/batch-action/composer.json, module/batch-action/features/batch-action-grid.feature, module/batch-action/src/Application/Controller/Api/GetBatchActionEntryGridAction.php, module/batch-action/src/Application/Request/ParamConverter/BatchActionParamConverter.php, module/batch-action/src/Domain/Query/BatchActionEntryGridQueryInterface.php, module/batch-action/src/Infrastructure/Grid/BatchActionEntryGridBuilder.php, module/batch-action/src/Infrastructure/Grid/Column/BatchActionMessageColumn.php, module/batch-action/src/Infrastructure/Grid/Renderer/BatchActionMessageColumnRenderer.php, module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionEntryGridQuery.php, module/batch-action/src/Resources/config/services.yml, module/product/features/product-batch-action-change-attribute.feature, module/product/features/product-batch-action-delete.feature, module/product/tests/Infrastructure/Filter/BatchAction/ProductBatchActionFilterTest.php
Add batch action entry grid endpoint`api/v1/{language}/batch-action/{action}/entries`.
- [x ] My code follows the style guidelines of this project
=> feature(batch-action) add batch action entry grid endpoint 

module/batch-action/src/Domain/Notification/BatchActionEndedNotification.php, module/batch-action/src/Infrastructure/Handler/BatchActionEndedEventHandler.php, module/batch-action/tests/Domain/Notification/BatchActionEndedNotificationTest.php, module/grid/src/Column/Renderer/TranslatableColumnRenderer.php, module/importer/src/Domain/Notification/EndImportNotification.php, module/importer/src/Domain/Notification/StartImportNotification.php, module/notification/migrations/Version20210304154000.php, module/notification/src/Application/Controller/Api/NotificationGridReadAction.php, module/notification/src/Domain/NotificationInterface.php, module/notification/src/Domain/Query/NotificationGridQueryInterface.php, module/notification/src/Infrastructure/Grid/NotificationGridBuilder.php, module/notification/src/Infrastructure/Persistence/Query/DbalNotificationGridQuery.php, module/notification/src/Infrastructure/Sender/Strategy/DbalSystemNotificationStrategy.php, module/product/features/grouping-product-batch-action-delete.feature, module/workflow/src/Domain/Notification/StatusChangedNotification.php, module/workflow/src/Infrastructure/Handler/Event/ProductValueChangedEventHandler.php, module/workflow/tests/Domain/Notification/StatusChangedNotificationTest.php
Extend notification by adding type and object id information
- [x ] New and existing unit tests pass locally with my changes
=> feature(notification) extend notification with type and object id

module/importer-ergonode-1/src/Infrastructure/Processor/ErgonodeImportProcess.php, module/importer-ergonode-1/src/Infrastructure/Processor/ErgonodeProcessorStepInterface.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeAttributesProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeCategoriesProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeOptionsProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeProductProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeTemplateProcessorStep.php
=> feature(import-ergonode-1) Handling of import aggregate types

module/importer/src/Infrastructure/Action/AbstractAttributeImportAction.php, module/importer/src/Infrastructure/Action/DateAttributeImportAction.php, module/importer/src/Infrastructure/Action/FileAttributeImportAction.php, module/importer/src/Infrastructure/Action/GalleryAttributeImportAction.php, module/importer/src/Infrastructure/Action/ImageAttributeImportAction.php, module/importer/src/Infrastructure/Action/MultiSelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/NumericAttributeImportAction.php, module/importer/src/Infrastructure/Action/PriceAttributeImportAction.php, module/importer/src/Infrastructure/Action/SelectAttributeImportAction.php, module/importer/src/Infrastructure/Action/TextAttributeImportAction.php, module/importer/src/Infrastructure/Action/TextareaAttributeImportAction.php, module/importer/src/Infrastructure/Action/UnitAttributeImportAction.php
Fix update attribute parameter on import exists attribute
=> bugfix(import) fix missing attribute parameter update

module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeGroupingProductProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeSimpleProductProcessorStep.php, module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeVariableProductProcessorStep.php, module/importer-ergonode-1/src/Resources/config/services.yml
Fix order product import in ergonode format import module
=> bugfix(import) fix product import order

module/product/migrations/Version20210303135330.php, module/product/src/Domain/Entity/AbstractProduct.php, module/product/src/Domain/Event/ProductValueChangedEvent.php, module/product/tests/Domain/Event/ProductValueChangedEventTest.php, module/workflow/src/Infrastructure/Handler/Event/ProductValueChangedEventHandler.php, module/workflow/src/Resources/config/services.yml
=> bugfix(product workflow) send notyfication status change

module/exporter-file/src/Infrastructure/Processor/Step/ProductExportProcessStep.php, module/product/src/Domain/Factory/ProductFactory.php, module/product/src/Infrastructure/Persistence/Projector/AbstractProductProjector.php, module/product/src/Infrastructure/Persistence/Projector/AbstractProductValueProjector.php, module/product/src/Infrastructure/Persistence/Projector/Binding/DbalBindAddedToProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Binding/DbalBindRemovedFromProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Child/DbalChildAddedToProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Child/DbalChildRemovedFromProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductAddedToCategoryEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductRemovedFromCategoryEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductTemplateChangedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueAddedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueChangedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueRemovedEventProjector.php
Add missing updated_at product prjections
=> bugfix(export) fix missing updated_by product projections

module/batch-action/features/batch-action-get-templates.feature, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Application/Controller/Api/GetTemplatesByBatchAction.php, module/batch-action/src/Application/Form/BatchActionForm.php, module/batch-action/src/Application/Form/Model/BatchActionFilterFormModel.php, module/batch-action/src/Application/Form/Model/BatchActionFormModel.php, module/batch-action/src/Application/Validator/AllFilterDisabled.php, module/batch-action/src/Application/Validator/AllFilterDisabledValidator.php, module/batch-action/src/Application/Validator/BatchActionFilter.php, module/batch-action/src/Application/Validator/BatchActionFilterValidator.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Domain/ValueObject/BatchActionFilter.php, module/batch-action/src/Domain/ValueObject/BatchActionFilterDisabled.php, module/batch-action/src/Domain/ValueObject/BatchActionFilterInterface.php, module/batch-action/src/Infrastructure/Filter/TemplateBatchActionFilter.php, module/batch-action/src/Infrastructure/Provider/BatchActionFilterIdsInterface.php, module/batch-action/src/Infrastructure/Provider/FilteredQueryBuilderInterface.php, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Domain/Command/CreateBatchActionCommandTest.php, module/product/features/product-batch-action-delete.feature, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php, module/product/src/Infrastructure/Provider/FilteredQueryBuilder.php
=> refactor(batch-action) Explicitly disabling filter

module/importer-ergonode-1/src/Resources/config/services.yml
Changing ergonode import service step order
=> bugfix(importer-ergonode-1) Changing service step order

module/product/src/Application/Form/Product/BatchAction/ProductEditForm.php
Change form for product edit in batch action
=> bugfix(batch action) Change product edit form

module/importer-ergonode-1/src/Infrastructure/Processor/ErgonodeImportProcess.php
=> bugfix(importer-ergonode-1) Fixed invalid ZIP file message

module/importer/src/Infrastructure/Action/GroupingProductImportAction.php, module/importer/src/Infrastructure/Action/MultimediaFromUrlImportAction.php, module/importer/src/Infrastructure/Action/OptionImportAction.php, module/importer/src/Infrastructure/Action/Process/Product/ImportProductAttributeBuilder.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductImageAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductMultiSelectAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductSelectAttributeStrategy.php, module/importer/src/Infrastructure/Action/SimpleProductImportAction.php, module/importer/src/Infrastructure/Action/VariableProductImportAction.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductImageAttributeStrategyTest.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductMultiSelectAttributeStrategyTest.php, module/importer/tests/Infrastructure/Action/Process/Product/Resolver/ImportProductSelectAttributeStrategyTest.php
=> feature(import-ergonode-1) Better logging for missing data

module/batch-action/src/Infrastructure/Grid/BatchActionEntryGridBuilder.php
=> bug(batch-action) Batch action grid fixes

module/batch-action/src/Application/Controller/Api/GetTemplatesByBatchAction.php, module/batch-action/src/Domain/ValueObject/BatchActionFilter.php, module/batch-action/tests/Domain/ValueObject/BatchActionFilterTest.php
=> feature(batch-action) Domain validation of batch action filter

module/batch-action/features/batch-action-count.feature, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Application/Controller/Api/Factory/BatchActionFilterFactory.php, module/batch-action/src/Application/Controller/Api/GetResourcesCountAction.php, module/batch-action/src/Infrastructure/Filter/CountFilter.php, module/batch-action/src/Resources/config/services.yml
=> feature(batch-action) Count by filter

CHANGELOG.md
=> docs: Batch action changelog

module/exporter-file/src/Infrastructure/Builder/Product/ExportProductMultiSelectAttributeBuilder.php, module/exporter-file/src/Infrastructure/Builder/Product/ExportProductSelectAttributeBuilder.php, module/exporter-file/src/Infrastructure/Builder/Product/ExportProductSimpleAttributeBuilder.php
Add missing exporter ergonode value builder validation and corresponded add error messages.
- [x ] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
=> bugfix(export) add missing value builder validation

CHANGELOG.md, module/grid/src/Column/Renderer/DateColumnRenderer.php
=> bugfix(grid) Fixed date format on grid

CHANGELOG.md, module/product/src/Application/Controller/Api/ProductReadInheritedValuesByLanguageAction.php
=> bugfix(product) Fixed misinterpreting numeric attribute code as int

module/account/src/Infrastructure/Grid/LogGridBuilder.php, module/batch-action/src/Infrastructure/Grid/BatchActionEntryGridBuilder.php, module/channel/src/Infrastructure/Grid/ExportErrorsGridBuilder.php, module/channel/src/Infrastructure/Grid/ExportGridBuilder.php, module/comment/src/Infrastructure/Grid/CommentGridBuilder.php, module/grid/features/gridSchema.json, module/grid/src/Column/DateTimeColumn.php, module/grid/src/Column/Renderer/DateTimeColumnRenderer.php, module/grid/src/Filter/Builder/DateTimeFilterBuilder.php, module/grid/src/Filter/DateTimeFilter.php, module/importer/src/Infrastructure/Grid/ImportErrorsGridBuilder.php, module/importer/src/Infrastructure/Grid/ImportGridBuilder.php, module/multimedia/src/Infrastructure/Grid/MultimediaGridBuilder.php, module/notification/src/Infrastructure/Grid/NotificationGridBuilder.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionElementGridBuilder.php, module/product-collection/src/Infrastructure/Grid/ProductCollectionGridBuilder.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/CreatedAtSystemAttributeColumnBuilderStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/EditedAtSystemAttributeColumnBuilderStrategy.php, module/product/src/Infrastructure/Grid/ProductHistoryGridBuilder.php, module/product/tests/Infrastructure/Grid/Column/Provider/Strategy/CreatedAtSystemAttributeColumnBuilderStrategyTest.php, module/product/tests/Infrastructure/Grid/Column/Provider/Strategy/EditedAtSystemAttributeColumnBuilderStrategyTest.php
=> feature(grid) datetime column

CHANGELOG.md
=> docs: add to changelog

module/product/features/product-batch-action-change-attribute.feature
Extend Bechat test form testing batch action `edit product`
=> test(batch-action/product) extend behat test for edit product

CHANGELOG.md, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Infrastructure/Provider/BatchActionProcessorProvider.php, module/batch-action/src/Resources/config/services.yml
=> bugfix(batch-action) Validation of Batch Action Type 

CHANGELOG.md, module/exporter-shopware-6/src/Application/Form/Shopware6ChannelForm.php
=> bugfix(exporter-shopware-6) Change configuration in form

module/exporter-shopware-6/src/Infrastructure/Exception/Mapper/Shopware6ExporterProductNoFoundException.php, module/exporter-shopware-6/src/Infrastructure/Mapper/ProductCrossSelling/ProductCrossSellingRootProductIdMapper.php
Change exception log when product not found in Shopware6 export.
=> bugfix(exporter-shopware-6) Change exception log

module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Domain/Command/StartBatchActionCommand.php, module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Handler/StartBatchActionCommandHandler.php, module/batch-action/src/Resources/config/messenger.yaml, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Domain/Command/StartBatchActionCommandTest.php, module/batch-action/tests/Infrastructure/Handler/CreateBatchActionCommandHandlerTest.php, module/batch-action/tests/Infrastructure/Handler/StartBatchActionCommandHandlerTest.php
Add missing StartBatchActionCommand and Handler
=> bugfix(batch-action) add start batch action command and handler

module/exporter-shopware-6/src/Infrastructure/Builder/PropertyGroupBuilder.php, module/exporter-shopware-6/src/Infrastructure/Builder/PropertyGroupOptionBuilder.php, module/exporter-shopware-6/src/Infrastructure/Mapper/PropertyGroup/PropertyGroupNameMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/PropertyGroupMapperInterface.php, module/exporter-shopware-6/src/Infrastructure/Mapper/PropertyGroupOption/PropertyGroupOptionNameMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/PropertyGroupOptionMapperInterface.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/PropertyGroupOptionsShopware6ExportProcess.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/PropertyGroupShopware6ExportProcess.php, module/exporter-shopware-6/src/Resources/config/services.yml
Shopware6 mapper rename to clean
=> refactor(exporter-shopware-6) Rename Property Group mapper

module/exporter-shopware-6/src/Infrastructure/Builder/CategoryBuilder.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Category/CategoryNameMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/Category/CategoryParentMapper.php, module/exporter-shopware-6/src/Infrastructure/Mapper/CategoryMapperInterface.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/CategoryShopware6ExportProcess.php, module/exporter-shopware-6/src/Resources/config/services.yml
Shopware6 mapper rename to clean
=> refactor(exporter-shopware-6) Rename Category mapper

module/exporter-shopware-6/src/Infrastructure/Builder/ProductBuilder.php, module/exporter-shopware-6/src/Infrastructure/Processor/Process/ProductShopware6ExportProcess.php, module/exporter-shopware-6/src/Resources/config/services.yml
Shopware6 mapper rename to clean code.
=> refactor(exporter-shopware-6) Rename Product builder

CHANGELOG.md, module/account/migrations/Version20210309120000.php, module/grid/src/DbalDataSet.php, module/grid/src/Factory/DbalDataSetFactory.php, module/product/src/Infrastructure/Persistence/DataSet/DbalProductDataSet.php
Fixing bug with duplication in notification grid pagination
Issue # 
#1263
=> bugfix(account, grid) Fixing duplicated entries in grid pagination

composer.json, composer.lock, module/attribute/src/Resources/config/serialization.yaml, module/condition/src/Resources/config/serialization.yaml, module/core/src/Application/PropertyInfo/Extractor/ReflectionExtractor.php, module/core/src/Application/Serializer/Normalizer/ObjectPropertyNormalizer.php, module/designer/src/Resources/config/serialization.yaml, module/importer/src/Resources/config/serialization.yaml, module/reader/src/Resources/config/serialization.yaml, module/value/src/Application/Serializer/Normalizer/TranslatableStringNormalizer.php, module/value/src/Resources/config/serialization.yaml, module/value/src/Resources/config/services.yml
=> feature(Core) Serializer discriminator map support

module/core/src/Application/Serializer/Normalizer/AggregateRootNormalizer.php
=> feature(core) Aggregate root normalization

module/core/src/Application/Serializer/Normalizer/AggregateRootNormalizer.php, module/core/tests/Application/Serializer/Normalizer/AggregateRootNormalizerTest.php
=> refactor(core) Improved aggregate root normalizer and added tests

module/core/src/Application/Serializer/Normalizer/AggregateRootNormalizer.php, module/core/src/Resources/config/services.yml, module/core/tests/Application/Serializer/Normalizer/AggregateRootNormalizerTest.php
=> feature(core) Added denormalization for aggregate roots

module/core/src/Application/Serializer/Normalizer/ObjectPropertyNormalizer.php, module/core/src/Application/Serializer/Normalizer/ScalarValueObjectNormalizer.php, module/core/src/Resources/config/services.yml
=> performance: Improved serializer performance

module/core/src/Application/Serializer/Normalizer/AggregateRootNormalizer.php
=> performance: Improved performance of aggregate root normalization

module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php
Get active language from tree
Issue #1293
=> feature(language) get actrive from tree

module/core/migrations/Version20210318100000.php
Change all language to active in DB
Issue #1293
=> feature(language) change all language to active

module/core/src/Infrastructure/Grid/LanguageGridBuilder.php, module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php
Add boolean tree column in language grid.
Issue #1293
=> feature(language) extend grid add column tree

module/condition/src/Infrastructure/Condition/Configuration/ProductHasStatusConditionConfigurationStrategy.php, module/core/src/Application/Form/Type/LanguageActiveType.php, module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php, module/exporter-magento-2/src/Application/Form/ExporterMagento2ConfigurationForm.php, module/exporter-shopware-6/features/export-profile-shopware6-api.feature, module/importer-magento-1/src/Application/Form/Type/LanguageMapType.php, module/importer-magento-1/src/Application/Form/Type/StoreViewType.php, module/translation-deepl/src/Application/Form/TranslationDeeplForm.php
Change language list to the new standard.
Issue #1293
=> feature(language) Change language list import/export

module/account/features/account.feature, module/account/src/Application/Form/Model/UpdateUserFormModel.php, module/account/src/Application/Validator/LanguageRead.php, module/account/src/Application/Validator/LanguageReadValidator.php
Add user language privilege validator. One language in reading mode is required.
Issue #1293
=> feature(account) one language read validator

module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php
Changing status names for batch action endpoint
Issue #1283
=> bugfix(batch-action) Fixing naming

module/event-sourcing/src/Infrastructure/Provider/DomainEventProvider.php
Fix event sourcing class provider cache
=> bugfix(event sourcing) fix class provider cache

module/importer/src/Infrastructure/Action/Process/Product/ImportProductAttributeBuilder.php
Fix incorrect import attribute error message creation
=> bugfix(import) fix creating exception message

CHANGELOG.md, module/product/features/variable-product.feature, module/product/src/Application/Controller/Api/Bindings/AddProductAttributeBindingsAction.php, module/product/src/Application/Controller/Api/Bindings/ProductRemoveBindingAction.php, module/product/src/Application/Model/Product/Binding/ProductBindFormModel.php, module/product/src/Application/Validator/ProductHasChildren.php, module/product/src/Application/Validator/ProductHasChildrenValidator.php, module/product/tests/Application/Form/Product/Binding/ProductBindFormTest.php, module/product/tests/Application/Validator/ProductHasChildrenValidatorTest.php
Adding validation for editing binding attributes in variable product.
Issue #1305
=> bugfix(product) Adding validation for editing binding attributes in variable product.

CHANGELOG.md, module/condition/src/Domain/Query/ConditionSetQueryInterface.php, module/condition/src/Infrastructure/Persistence/Query/DbalConditionSetQuery.php, module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetLanguageRelationshipStrategy.php, module/core/src/Application/Model/LanguageTree/LanguageTreeUpdateFormModel.php, module/core/src/Application/Validator/LanguageTreeLanguageRelation.php, module/core/src/Application/Validator/LanguageTreeLanguageRelationValidator.php, module/core/src/Domain/Query/LanguageQueryInterface.php, module/core/src/Infrastructure/Builder/LanguageTree/LanguageTreeBuilder.php, module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php, module/exporter-file/src/Infrastructure/Strategy/Relationship/LanguageErgonodeChannelRelationshipStrategy.php, module/exporter-shopware-6/src/Infrastructure/Strategy/Relationship/LanguageShopware6ChannelRelationshipStrategy.php, module/importer-magento-1/src/Infrastructure/Strategy/Relationship/LanguageImporterMagento1RelationshipStrategy.php, module/importer/src/Domain/Query/SourceQueryInterface.php, module/importer/src/Infrastructure/Persistence/Query/DbalSourceQuery.php
=> feature(language) extend relation validator

config/packages/ergonode_event_sourcing.yaml, module/event-sourcing/src/Application/DependencyInjection/Configuration.php, module/event-sourcing/src/Application/DependencyInjection/ErgonodeEventSourcingExtension.php, module/event-sourcing/src/Resources/config/cache.yaml, module/event-sourcing/src/Resources/config/services.yml
=> refactor(event-sourcing) Aggregate cache optional based on configuration

module/exporter-file/src/Application/Form/ExporterFileConfigurationForm.php
Add description to export type field in ergonode zip export. 
- [x ] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
=> feature(export) add export type description

module/attribute/src/Domain/ValueObject/OptionInterface.php, module/attribute/src/Domain/ValueObject/OptionValue/MultilingualOption.php, module/attribute/src/Domain/ValueObject/OptionValue/StringOption.php, module/attribute/tests/Domain/ValueObject/OptionValue/MultilingualOptionTest.php, module/attribute/tests/Domain/ValueObject/OptionValue/StringOptionTest.php, module/event-sourcing/src/Domain/AbstractAggregateRoot.php, module/event-sourcing/src/Domain/AbstractEntity.php
=> refactor: Removed redundant jms annotations

module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php
Fixing query for batch action state endpoint
Issue # 
#1283
=> bugfix(batch-action) Fixing query for batch action state endpoint

module/workflow/src/Infrastructure/Grid/StatusGridBuilder.php
=> bugfix(workflow) Fixing codes in status grid

module/workflow/migrations/Version20201125121920.php
Moving migration to correct module
=> bugfix(workflow) Moving migration to correct module

module/attribute/src/Application/Serializer/Normalizer/AttributeNormalizer.php, module/attribute/src/Domain/Entity/AbstractAttribute.php, module/attribute/src/Resources/config/services.yml, module/attribute/tests/Application/Serializer/Normalizer/AttributeNormalizerTest.php, module/core/src/Resources/config/services.yml
=> feature(attribute) Attribute normalization

CHANGELOG.md, module/exporter-shopware-6/src/Infrastructure/Connector/Action/Currency/PostCurrencyCreate.php
=> bugfix(exporter-shopware-6) Fixed API usage to v2

module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php
=> bugfix(batch-action) Fixed profile query

module/completeness/src/Application/Serializer/Normalizer/CompletenessCalculatorLineNormalizer.php, module/completeness/src/Application/Serializer/Normalizer/CompletenessElementReadModelNormalizer.php, module/completeness/src/Application/Serializer/Normalizer/CompletenessReadModelNormalizer.php, module/completeness/src/Domain/Calculator/CompletenessCalculatorLine.php, module/completeness/src/Domain/ReadModel/CompletenessElementReadModel.php, module/completeness/src/Domain/ReadModel/CompletenessReadModel.php, module/completeness/src/Resources/config/services.yml, module/completeness/tests/Application/Serializer/Normalizer/CompletenessCalculatorLineNormalizerTest.php, module/completeness/tests/Application/Serializer/Normalizer/CompletenessElementReadModelNormalizerTest.php, module/completeness/tests/Application/Serializer/Normalizer/CompletenessReadModelNormalizerTest.php
=> feature(completeness) Mapped completeness models for SF serializer

CHANGELOG.md, module/completeness/features/completeness-widget.feature, module/completeness/features/product-completness.feature
=> feature(completeness) Adding behat tests for completeness endpoint

CHANGELOG.md, config/packages/dev/monolog.yaml, module/channel/src/Application/DependencyInjection/ErgonodeChannelExtension.php, module/channel/src/Resources/config/monolog.yaml, module/importer/src/Application/DependencyInjection/ErgonodeImporterExtension.php, module/importer/src/Resources/config/monolog.yaml
=> feature(channel) Add logger channel/importer

module/exporter-shopware-6/src/Infrastructure/Model/AbstractProductCrossSelling.php, module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomField.php, module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomFieldConfig.php, module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomFieldSet.php, module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomFieldSetConfig.php, module/exporter-shopware-6/src/Infrastructure/Model/Basic/Shopware6CustomFieldConfig.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Category.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6Product.php, module/exporter-shopware-6/src/Infrastructure/Model/Shopware6PropertyGroupOption.php
=> bugfix(exporter-shopware-6) Serialize int param in product

module/product/src/Infrastructure/Calculator/TranslationInheritanceCalculator.php
Fix redundant db query in value calculation prcoess
=> bugfix(core) fix value calculation redundant db query

config/packages/monolog.yaml
=> feature: Monolog process id processor

module/importer/src/Domain/Command/Import/ImportGroupingProductCommand.php, module/importer/src/Domain/Command/Import/ImportVariableProductCommand.php
Fix incorrect php doc annotations used for serialization in import commands
=> bugfix(import) fix incorrect php docs types for serialization

module/notification/src/Application/Controller/Api/NotificationMarkUpdateAction.php
Adding uuid validation for notifications
=> feature(notification) Adding uuid validation for notifications

.env
=> bugfix: Cleanup outdated DSNs

module/importer-magento-1/src/Infrastructure/Processor/Step/Magento1OptionProcessor.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductMultiSelectAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductSelectAttributeStrategy.php, module/importer/src/Infrastructure/Exception/ImportMissingOptionException.php
Fix incorrect importer missing option error message generation
=> bugfix(import) fix import option error message generation

module/exporter-shopware-6/src/Infrastructure/Connector/Shopware6Connector.php, module/exporter-shopware-6/src/Infrastructure/Exception/Shopware6AuthenticationException.php, module/exporter-shopware-6/src/Infrastructure/Exception/Shopware6UnauthorizedException.php, module/exporter-shopware-6/src/Infrastructure/Handler/ProcessExportCommandHandler.php, module/exporter-shopware-6/src/Resources/config/messenger.yaml
Add invalid auth log api Shopware6
=> feature(exporter-shopware-6) add invalid auth log

module/importer/src/Infrastructure/Exception/ImportException.php, module/importer/tests/Infrastructure/Exception/ImportExceptionTest.php
=> feature(import) Casting exception parameters to string

build.xml
=> build: Cleanup of cache clearing command in builds

config/packages/test/framework.yaml
=> bugfix: Disable session on test environment

composer.json, composer.lock, config/bundles.php, symfony.lock
Remove depicated symfony web server bundle
=> feature remove deprecated symfony web server

config/packages/messenger.yaml, module/account/src/Infrastructure/Subscriber/LocaleSubscriber.php, module/authentication/src/Resources/config/services.yml, module/batch-action/src/Infrastructure/Handler/BatchActionEndedEventHandler.php, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Infrastructure/Handler/BatchActionEndedEventHandlerTest.php, module/core/src/Application/DependencyInjection/ErgonodeCoreExtension.php, module/core/src/Application/Messenger/Middleware/AuthenticationMiddleware.php, module/core/src/Application/Messenger/Middleware/GetUserMiddleware.php, module/core/src/Application/Messenger/Stamp/UserStamp.php, module/core/src/Application/Security/Security.php, module/core/src/Application/Security/Token/UserToken.php, module/core/src/Application/Security/User/CachedUser.php, module/core/src/Infrastructure/Provider/LanguageTreeProvider.php, module/core/src/Resources/config/messenger.yaml, module/core/tests/Application/Messenger/Middleware/AuthenticationMiddlewareTest.php, module/core/tests/Application/Messenger/Middleware/GetUserMiddlewareTest.php, module/core/tests/Application/Messenger/Stamp/UserStampTest.php, module/product/src/Domain/Factory/ProductFactory.php, module/product/src/Infrastructure/Grid/ProductGridBuilder.php, module/product/src/Infrastructure/Handler/AbstractUpdateProductHandler.php, module/product/src/Infrastructure/Handler/Attribute/ChangeProductAttributeCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/ChangeProductAttributesCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributeCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributesCommandHandler.php
=> refactor: Simplified relations with core services

module/account/src/Application/Validator/LanguageRead.php, module/account/src/Application/Validator/LanguageReadValidator.php, module/account/src/Domain/Query/AccountQueryInterface.php, module/account/src/Infrastructure/Handler/Event/Application/LanguageTreeUpdatedEventHandler.php, module/account/src/Infrastructure/Persistence/Query/DbalAccountQuery.php, module/attribute/src/Application/Controller/Api/Attribute/AttributeValidationAction.php, module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetLanguageRelationshipStrategy.php, module/core/migrations/Version20210318100000.php, module/core/src/Application/Event/LanguageTreeUpdatedEvent.php, module/core/src/Application/Validator/LanguageTreeLanguageRelation.php, module/core/src/Application/Validator/LanguageTreeLanguageRelationValidator.php, module/core/src/Domain/Query/LanguageQueryInterface.php, module/core/src/Infrastructure/Persistence/Query/DbalLanguageQuery.php, module/core/src/Infrastructure/Persistence/Repository/DbalLanguageTreeRepository.php, module/exporter-file/src/Infrastructure/Strategy/Relationship/LanguageErgonodeChannelRelationshipStrategy.php, module/exporter-shopware-6/src/Infrastructure/Strategy/Relationship/LanguageShopware6ChannelRelationshipStrategy.php, module/importer-magento-1/src/Infrastructure/Strategy/Relationship/LanguageImporterMagento1RelationshipStrategy.php, module/importer/src/Domain/Query/SourceQueryInterface.php, module/importer/src/Infrastructure/Persistence/Query/DbalSourceQuery.php
=> bugfix(core)Lannguage Privilege delete after change tree

.env.test, config/services_test.yaml, module/batch-action/src/Application/Serializer/Normalizer/PayloadCommandNormalizer.php, module/batch-action/src/Domain/Command/AbstractPayloadCommand.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Domain/Command/ProcessBatchActionEntryCommand.php, module/batch-action/src/Domain/Command/StartBatchActionCommand.php, module/batch-action/src/Resources/config/serialization.yaml, module/batch-action/src/Resources/config/services.yml, module/core/src/Application/Serializer/Normalizer/ObjectPropertyNormalizer.php, module/core/src/Test/Fixtures/Messenger/Transport/TestTransport.php, module/core/src/Test/Fixtures/Messenger/Transport/TestTransportFactory.php
=> bugfix(batch-action) Fixed commands serialization and added test messenger serialization

module/account/src/Application/Security/Voter/LanguageVoter.php, module/account/src/Application/Security/Voter/UserActivityVoter.php, module/account/src/Application/Security/Voter/UserRoleVoter.php
=> bugfix(account) Cleanup unused logger

module/attribute/src/Infrastructure/Mapper/Strategy/FileAttributeMapperStrategy.php, module/attribute/src/Infrastructure/Mapper/Strategy/GalleryAttributeMapperStrategy.php, module/attribute/src/Infrastructure/Mapper/Strategy/MultiSelectAttributeMapperStrategy.php, module/attribute/tests/Infrastructure/Mapper/Strategy/FileAttributeMapperStrategyTest.php, module/attribute/tests/Infrastructure/Mapper/Strategy/GalleryAttributeMapperStrategyTest.php, module/attribute/tests/Infrastructure/Mapper/Strategy/MultiSelectAttributeMapperStrategyTest.php, module/product/features/product-local-file-attribute-manipulation.feature, module/product/features/product-local-gallery-attribute-manipulation.feature, module/product/features/product-local-multi-select-attribute-manipulation.feature, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributeCommandHandler.php
Fix error when removing gallery, file and multiselect attribute value from product.
=>  bugfix(product) fix error on removeing attribute values

module/product/src/Infrastructure/Grid/ProductGridBuilder.php
Fix user auth on the product grid.
=> bugfix(product) Fixed fetching user privileges on Grid

config/services_test.yaml, module/core/src/Test/Fixtures/Messenger/Transport/TestTransport.php, module/core/src/Test/Fixtures/Messenger/Transport/TestTransportFactory.php
=> tests(core) Clearing user token on test transport

src/Resources/fixtures/e2e/templates.yaml
=> bugfix(fixtures) Fixing e2e fixtures

CHANGELOG.md, module/segment/migrations/Version20210324103000.php
Fix incorrect LEFT JOIN in Version20210324103000 migration file in segment module
Issue: #1371
=> bugfix(segment) fix migration Version20210324103000

composer.json, composer.lock, symfony.lock
=> build: Removed webonyx/graphql-php dependency

composer.json, composer.lock, module/account/src/Infrastructure/Handler/Event/UserPasswordChangedEventHandler.php, module/core/composer.json, module/mailer/src/Resources/config/serialization.yml
Set async mode to send mail when user change password.
=> bugfix(account)Set async mode to send mail

CHANGELOG.md, module/importer/src/Infrastructure/Action/AbstractProductImportAction.php, module/importer/src/Infrastructure/Action/GroupingProductImportAction.php, module/importer/src/Infrastructure/Action/SimpleProductImportAction.php, module/importer/src/Infrastructure/Action/VariableProductImportAction.php, module/product/src/Domain/Entity/AbstractProduct.php
Fixing removing system attributes during import
Issue #1376 
-  #[x] New and existing unit tests pass locally with my changes
=> feature(product) Fixing removing system attributes during import

module/reader/migrations/Version20210416123000.php
Remove legacy reader privilege database entry
=> bugfix(importer) remove legacy reader privilege

module/product/src/Domain/ValueObject/Sku.php, module/product/tests/Domain/ValueObject/SkuTest.php
=> bugfix(product) Missing minimal Sku length validation

module/designer/migrations/Version20210421113000.php
Add template element entry for support new attribute type: product_relation
=> Feature(template) attribute relation template entry

module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php, module/core/src/Domain/ValueObject/TranslatableString.php, module/core/tests/Domain/ValueObject/TranslatableStringTest.php, module/designer/src/Domain/Builder/Strategy/AttributeViewTemplateElementStrategy.php
=> bugfix(core) Fixed TranslatableString has

CHANGELOG.md, UPGRADE-1.1.md, module/attribute/src/Application/DependencyInjection/ErgonodeAttributeExtension.php, module/attribute/src/Infrastructure/Mapper/AttributeValueMapper.php, module/attribute/src/Resources/config/services.yml, module/attribute/tests/Infrastructure/Mapper/AttributeValueMapperTest.php
Add tag configuration support for ```Ergonode\Attribute\Infrastructure\Mapper\AttributeValueMapper```.
Tag used: ```attribute.attribute_mapper_strategy```
Issue #1390
=>  feature(attribute) extend AttributeValueMapper configuration with tag support

CHANGELOG.md
=> bugfix: Missing changelog entry

CHANGELOG.md, module/core/src/Domain/Repository/UnitRepositoryInterface.php, module/core/src/Infrastructure/Persistence/Repository/EventStoreUnitRepository.php
=> bugfix(core) Fixed UnitRepository type hinting

module/product/features/product-product-relation-attribute-manipulation.feature, module/product/src/Domain/Query/ProductRelationAttributeQueryInterface.php, module/product/src/Infrastructure/Persistence/Query/DbalProductRelationAttributeQuery.php, module/product/src/Infrastructure/Strategy/Relationship/ProductRelationAttributeRelationshipStrategy.php
Add product removing validation strategy for product in relation to another one.
=>  feature(product) add removing validation strategy for releted products

module/product/features/product-product-relation-attribute-manipulation.feature, module/product/src/Application/Controller/Api/Attribute/ProductRelatedProductByAttributeAction.php, module/product/src/Application/Controller/Api/Relations/AssociatedProductAvailableChildrenAction.php, module/product/src/Domain/Query/ProductRelationAttributeGridQueryInterface.php, module/product/src/Infrastructure/Grid/ProductRelationGridBuilder.php, module/product/src/Infrastructure/Persistence/Query/DbalProductRelationAttributeGridQuery.php, module/product/tests/Infrastructure/Grid/ProductRelationGridBuilderTest.php
Add endpoint for showing products related to given one . Relation base on given product and attribute attribute
Issue #
=> feature(product) add attribute relation prduct grid

CHANGELOG.md
=> docs: Fixed changelog

module/product/migrations/Version20210426110000.php, module/product/src/Application/Controller/Api/Attribute/ProductRelatedProductByAttributeAction.php
Add relation grid endpoint privileges
Issue #
=> feature(product) add grid relation privilege

CHANGELOG.md, config/packages/ergonode_core.yaml, module/core/src/Application/DependencyInjection/Configuration.php, module/core/src/Application/DependencyInjection/ErgonodeCoreExtension.php, module/core/src/Resources/config/services.yml
=> bugfix(core) Removed dependency on env

module/value/src/Resources/config/services.yml
=> bugfix(value) Removed invalid services definitions

bin/console, phpstan.neon.dist
=> bugfix: Cleaned up JMS leftovers

module/product/features/attribute-product-relation.feature, module/product/src/Resources/translations/attribute.en.yaml, module/product/src/Resources/translations/attribute.pl.yaml
Fix translation for relation attribute
=> bugfix(product) fix product-relation translations

composer.lock
Update Shopware6 main module for the test to dev-main.
=> configuration: shopware composer up main

module/exporter-file/src/Infrastructure/Builder/Product/ExportProductRelationAttributeBuilder.php
Adding to ergonode export product relation attribute
Issue: #1422
=> Adding to ergonode export product relation attribute

module/product/src/Infrastructure/Grid/Column/ProductRelationColumn.php, module/product/src/Infrastructure/Grid/Filter/Builder/RelationFilterBuilder.php, module/product/src/Infrastructure/Grid/Filter/RelationFilter.php, module/product/tests/Infrastructure/Grid/Column/ProductRelationColumnTest.php, module/product/tests/Infrastructure/Grid/Filter/RelationFilterTest.php
Add custom column filter for support filtering on text value for relation attribute grid column.
Issue #1384
=> feature(product) add support for relation filter to product relation grid column

composer.lock
=> config: shopware up

composer.json, composer.lock, module/category/composer.json, module/channel/composer.json, module/core/composer.json, module/importer-ergonode-1/composer.json, module/importer/composer.json
update limenius/liform-bundle 0.15->0.17
=> configuration: update limenius/liform-bundle 0.15->0.17

composer.json, composer.lock, symfony.lock
=> config: Doctrine update to ^2.13.0

module/importer/src/Infrastructure/Handler/ImportSimpleProductCommandHandler.php
Adding product relation attribute to ergo importer.
Issue # 
#1384
=> Dispatch async fix

composer.json, composer.lock, symfony.lock
Update doctrine bundle to test
=> config: Doctrine bundle update  to ^2.3

CHANGELOG.md, module/fixture/src/Application/Command/ErgonodeFixtureCommand.php, module/fixture/src/Infrastructure/Loader/FixtureLoader.php, module/fixture/src/Infrastructure/Process/FixtureProcess.php
Extend fixture loader to file parametr.
=> feature(fixture) add file parametr to fixture loader

CHANGELOG.md, UPGRADE-1.1.md, module/product/src/Application/Controller/Api/Bindings/AddProductAttributeBindingsAction.php, module/product/src/Application/Controller/Api/Bindings/ProductRemoveBindingAction.php, module/product/src/Application/Controller/Api/Relations/ProductAddChildAction.php, module/product/src/Application/Controller/Api/Relations/ProductAddChildFromSegmentsAction.php, module/product/src/Application/Controller/Api/Relations/ProductAddChildFromSkusAction.php, module/product/src/Application/Controller/Api/Relations/ProductRemoveChildAction.php, module/product/src/Domain/Command/Bindings/AddProductBindingCommand.php, module/product/src/Domain/Command/Bindings/RemoveProductBindingCommand.php, module/product/src/Domain/Command/Relations/AddProductChildCommand.php, module/product/src/Domain/Command/Relations/AddProductChildrenBySegmentsCommand.php, module/product/src/Domain/Command/Relations/AddProductChildrenCommand.php, module/product/src/Domain/Command/Relations/RemoveProductChildCommand.php, module/product/tests/Domain/Command/Bindings/AddProductBindingCommandTest.php, module/product/tests/Domain/Command/Bindings/RemoveProductBindingCommandTest.php, module/product/tests/Domain/Command/Relations/AddProductChildCommandTest.php, module/product/tests/Domain/Command/Relations/AddProductChildrenBySegmentsCommandTest.php, module/product/tests/Domain/Command/Relations/AddProductChildrenCommandTest.php
=> refactor(product) Commands take aggregates objects instead of id object

CHANGELOG.md, module/workflow/migrations/Version20210518083000.php, module/workflow/src/Infrastructure/Grid/TransitionGridBuilder.php, module/workflow/src/Infrastructure/Persistence/Projector/Transition/TransitionConditionSetChangedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Transition/TransitionRolesIdsChangedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Projector/Workflow/DbalWorkflowTransitionAddedEventProjector.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionGridQuery.php
Add two new columns to transition grid:
Multiselect column with relented roles and hidden text column with condtition_set_id
Issue #1442
=> feature(workflow) extend transition grid with roles and consition set columns

CHANGELOG.md, module/workflow/features/product-status-attribute.feature, module/workflow/src/Domain/Query/ProductStatusQueryInterface.php, module/workflow/src/Infrastructure/Persistence/Query/DbalProductStatusQuery.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusProductRelationshipStrategy.php
Fix incorrect Query that check status attribute relation in products
Issue  #1436
- [x ] My code follows the style guidelines of this project
=> bugfix(workflow) fix incorrect db query for status to product relation

src/Resources/fixtures/develop/categories.yaml, src/Resources/fixtures/e2e/categories.yaml
=> bugfix: Fixed CategoryTree fixtures

CHANGELOG.md, module/product-collection/src/Infrastructure/Grid/Builder/Query/ProductCollectionSystemAttributeDataSetQueryBuilder.php
Fix performance of Database Query in product grid builder for product collection system attribute 
Issue #1450
=> bugfix(product collection) fix product collection grid builder query

README.md
=> configuration(release) add release 1.0.1 configuration

module/condition/src/Application/Validator/ConditionSetExists.php, module/condition/src/Application/Validator/ConditionSetExistsValidator.php, module/condition/tests/Application/Validator/ConditionSetExistsValidatorTest.php, module/workflow/features/workflow.feature, module/workflow/src/Application/Form/Model/TransitionFormModel.php, module/workflow/src/Application/Form/Model/Workflow/WorkflowFormModel.php, module/workflow/src/Application/Form/TransitionForm.php, module/workflow/src/Application/Validator/TransitionValid.php, module/workflow/src/Application/Validator/TransitionValidValidator.php, module/workflow/src/Domain/Command/Workflow/UpdateWorkflowCommand.php, module/workflow/src/Infrastructure/Factory/Command/Update/UpdateWorkflowCommandFactory.php, module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowCommandHandler.php, module/workflow/tests/Application/Validator/TransitionValidValidatorTest.php
Extending update workflow endpoint
Issue #1452
=> feature(workflow, condition) - Extending update workflow endpoint

composer.json, composer.lock
=> build: JWT refresh token bundle Symfony compatibility

module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php
=> bugfix(condition) Get options value

module/product/src/Application/Validator/NotTheSameProduct.php, module/product/src/Application/Validator/NotTheSameProductValidator.php, module/product/tests/Application/Validator/NotTheSameProductValidatorTest.php
Change validator message
Issue #
=> bugfix(product) - Change validator message

module/segment/features/segment-delete-condition-set.feature, module/segment/migrations/Version20210601102541.php, module/segment/src/Infrastructure/Handler/Command/DeleteSegmentCommandHandler.php, module/workflow/features/transitions-delete-condition-set.feature, module/workflow/src/Domain/Query/TransitionConditionSetQueryInterface.php, module/workflow/src/Infrastructure/Handler/Workflow/DeleteWorkflowTransitionCommandHandler.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionQuery.php, module/workflow/src/Infrastructure/Strategy/Relationship/ConditionSetWorkflowTransitionRelationshipStrategy.php, module/workflow/src/Resources/config/services.yml
Bugfix delete condition set after delete object workflow transition or segment.
=> bugfix(segment,workflow) delete condition set after delete object

CHANGELOG.md, module/grid/src/Column/IdColumn.php, module/grid/src/Filter/Builder/InFilterBuilder.php, module/grid/src/Filter/InFilter.php, module/grid/tests/Filter/InFilterTest.php, module/product/features/product-grid-post.feature, module/product/features/product-grid.feature
Extend grid filter
Issue #1472
=> feature(grid, product) Add filter in and not in

module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowCommandHandler.php, module/workflow/tests/Infrastructure/Handler/Workflow/UpdateWorkflowCommandHandlerTest.php
=> bugfix(workflow) Delete condition set after remove transition

CHANGELOG.md, module/account/src/Application/DependencyInjection/ErgonodeAccountExtension.php, module/channel/src/Application/DependencyInjection/Configuration.php, module/channel/src/Application/DependencyInjection/ErgonodeChannelExtension.php, module/importer/src/Application/DependencyInjection/Configuration.php, module/importer/src/Application/DependencyInjection/ErgonodeImporterExtension.php, module/multimedia/src/Application/DependencyInjection/Configuration.php, module/multimedia/src/Application/DependencyInjection/ErgonodeMultimediaExtension.php
=> bugfix: Allowed disabling default local storages for overriding

module/grid/src/PostGridConfiguration.php
Fix incorrect POST grid configuration key generation
Issue #1384
=> bugfix(product) fix key generation for post grid configuration class

module/product/src/Infrastructure/Provider/Strategy/ProductRelationAttributeValueConstraintStrategy.php
Add max validation for maximal relation count in product relation attribute
Issue #1384
=> feature(product) add max relations validation to product relation attribute

module/product/src/Application/Controller/Api/Attribute/UpdateProductsAttributesAction.php
=> bugfix(product) Fixed updating product attribute value endpoint

.github/workflows/tests.yml
=> ci: Actions on push feature and release branches

module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductRelationAttributeStrategy.php, module/importer/src/Infrastructure/Exception/MaxImportedRelationsExceededException.php, module/product/src/Domain/Entity/Attribute/ProductRelationAttribute.php, module/product/src/Infrastructure/Provider/Strategy/ProductRelationAttributeValueConstraintStrategy.php
Add import error for import more then 100 relations for product relation attribute value 
Issue #1384
=> feature(importer) add max relation product import error

CHANGELOG.md, module/api/src/Application/HttpKernel/Controller/DTOInputValueResolver.php, module/api/src/Resources/config/services.yml, module/api/tests/Application/HttpKernel/Controller/DTOInputValueResolverTest.php, module/api/tests/Application/HttpKernel/Controller/DTOValueResolverTest.php, module/shared-kernel/src/Application/Api/DTOInputInterface.php
=> feature(api) DTO input value resolving

depfile.yaml
=> bugfix: Removed depfile exception on core coupled with product

UPGRADE-1.1.md, depfile.yaml, module/attribute/composer.json, module/attribute/src/Application/Form/Attribute/Configuration/PriceAttributeConfigurationForm.php, module/attribute/src/Application/Form/Type/CurrencyFormType.php, module/attribute/src/Domain/Query/CurrencyQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalCurrencyQuery.php, module/attribute/tests/Application/Form/Attribute/PriceAttributeFormTest.php, module/core/composer.json
Fix incorrect core->attribute module relation
Issue #1198
=> bugfix(core) remove attribute module relation

CHANGELOG.md, module/grid/src/PostGridConfiguration.php, module/product/features/product-grid-post.feature
=> bugfix (gird, product) filtering relation grid by numeric

module/multimedia/src/Application/Controller/Api/Multimedia/GetMultimediaGridAction.php, module/multimedia/src/Resources/config/services.yml
There was incorrect type hint for gird builder in Multimedia grid controller.
Changed from MultimediaGridBuilder to GridBuilderInterface
Issue #1506
=> bugfix(multimedia) fix incorrect grid builder typehint in multimedia grid controller

CHANGELOG.md, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/CreatedAtSystemAttributeColumnBuilderStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/DateAttributeColumnStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/EditedAtSystemAttributeColumnBuilderStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/PriceAttributeColumnStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/TextAreaAttributeColumnStrategy.php, module/product/src/Infrastructure/Grid/Column/Provider/Strategy/UnitAttributeColumnStrategy.php, module/product/src/Infrastructure/Grid/ProductGridBuilder.php
Fix setting extension parameters in UnitColumn for Product Grid, fix unit value from unit id  to unit symbol. 
Issue  #1510
=> bugfix(grid) fix UnitColumn extension value

UPGRADE-1.1.md, module/importer/src/Infrastructure/Action/MultimediaFromUrlImportAction.php, module/multimedia/features/multimedia.feature, module/multimedia/src/Application/Controller/Api/Multimedia/UploadMultimediaAction.php, module/multimedia/src/Application/Model/MultimediaUploadModel.php, module/multimedia/src/Application/Validator/MultimediaFileExists.php, module/multimedia/src/Application/Validator/MultimediaFileExistsValidator.php, module/multimedia/src/Domain/Entity/AbstractMultimedia.php, module/multimedia/src/Domain/Query/MultimediaQueryInterface.php, module/multimedia/src/Infrastructure/Handler/AddMultimediaCommandHandler.php, module/multimedia/src/Infrastructure/Persistence/Query/DbalMultimediaQuery.php, module/multimedia/tests/Domain/Entity/AbstractMultimediaTest.php
Changing multimedia saving mechanism.
Issue #1506
=> feature(multimedia) - Changing multimedia saving mechanism

module/multimedia/src/Application/Controller/Api/Multimedia/UploadMultimediaAction.php, module/multimedia/src/Domain/Command/AddMultimediaCommand.php, module/multimedia/src/Infrastructure/Handler/AddMultimediaCommandHandler.php, module/multimedia/tests/Domain/Command/AddMultimediaCommandTest.php
Add a file name to the upload command.
=> feature(multimedia) add file name in upload command

CHANGELOG.md, module/api/src/Application/HttpKernel/Controller/DTOInputValueResolver.php, module/api/tests/Application/HttpKernel/Controller/DTOInputValueResolverTest.php
=> bugfix(api) Fixed caught exception in DTOInputValueResolver

CHANGELOG.md, module/account/composer.json, module/importer-ergonode-1/composer.json
=> bugfix: remove composer ramsey/uuid-doctrine

CHANGELOG.md, module/account/composer.json, module/importer-ergonode-1/composer.json
=> bugfix: remove composer ramsey/uuid-doctrine 

CHANGELOG.md, module/authentication/composer.json
=> bugfix(authentication) Opened gesdinet/jwt-refresh-token-bundle dependency

CHANGELOG.md, module/account/composer.json, module/api/src/Application/HttpKernel/Controller/DTOInputValueResolver.php, module/api/tests/Application/HttpKernel/Controller/DTOInputValueResolverTest.php, module/authentication/composer.json, module/importer-ergonode-1/composer.json
=> Master to feature/media-v2

module/multimedia/src/Infrastructure/Service/Metadata/MetadataService.php, module/multimedia/src/Infrastructure/Service/Metadata/Reader/DefaultMetadataReader.php
Extend multimedia metadata endpoint witch file size, file type i file timestamp information 
Issue #1532
=> feature(multimedia) extend multimedia information result

module/account/src/Infrastructure/Strategy/Relationship/RoleUserRelationshipStrategy.php, module/attribute/src/Infrastructure/Strategy/Relationship/AttributeAttributeGroupRelationshipStrategy.php, module/attribute/src/Infrastructure/Strategy/Relationship/AttributeUnitRelationshipStrategy.php, module/category/src/Infrastructure/Strategy/Relationship/CategoryInCategoryTreeRelationshipStrategy.php, module/channel/src/Infrastructure/Strategy/Relationship/ActiveExportRelationshipStrategy.php, module/channel/src/Infrastructure/Strategy/Relationship/ChannelActiveExportRelationshipStrategy.php, module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetAttributeRelationshipStrategy.php, module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetLanguageRelationshipStrategy.php, module/core/src/Infrastructure/Builder/ExistingRelationshipTypeMessageBuilder.php, module/designer/src/Infrastructure/Strategy/Relationship/ProductTemplateRelationshipStrategy.php, module/designer/src/Infrastructure/Strategy/Relationship/TemplateAttributeRelationshipStrategy.php, module/designer/src/Infrastructure/Strategy/Relationship/TemplateMultimediaRelationshipStrategy.php, module/exporter-file/src/Infrastructure/Strategy/Relationship/LanguageErgonodeChannelRelationshipStrategy.php, module/importer/src/Infrastructure/Strategy/Relationship/ActiveImportRelationshipStrategy.php, module/importer/src/Infrastructure/Strategy/Relationship/SourceActiveImportRelationshipStrategy.php, module/product-collection/src/Infrastructure/Relationship/ProductProductCollectionRelationshipStrategy.php, module/product-collection/src/Infrastructure/Strategy/Relationship/ProductCollectionProductCollectionTypeRelationshipStrategy.php, module/product/src/Infrastructure/Processor/BatchAction/ProductDeleteBatchActionProcessor.php, module/product/src/Infrastructure/Strategy/Relationship/ChildrenProductRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductAttributeRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductCategoryRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductMultimediaRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductOptionRelationshipStrategy.php, module/product/src/Infrastructure/Strategy/Relationship/ProductRelationAttributeRelationshipStrategy.php, module/segment/src/Infrastructure/Strategy/Relationship/ConditionSetSegmentRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/ConditionSetWorkflowTransitionRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/DefaultStatusRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusProductRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusWorkflowRelationshipStrategy.php
Fix message show when given element can be removed from system. 
Issue
=> bugfix: fix remove mesages

build.xml, src/Resources/fixtures/e2e/workflow.yaml
Extend fixture for workflow test e2e
=> ci: add fixture workflow

depfile.yaml
Add new configurations to depfile.yaml
Issue #
=> commfiguration: add new configurations to depfile.yml

CHANGELOG.md, module/condition/features/condition-numeric-attribute-value.feature, module/condition/src/Infrastructure/Condition/Configuration/NumericAttributeValueConditionConditionConfigurationStrategy.php, module/core/src/Application/Serializer/SymfonySerializer.php
Extend SymfonySerializer:normalize and SymfonySerializer:denormalize with default format value
Issue #1538
=> bugfix(core) add format to SymfonySerilizer:denormalizer

module/api/src/Resources/translations/api.pl.yaml
Typo fix api translation error.
=> bugfix: api typo fix

module/attribute/tests/Application/Validator/AttributeCodeValidatorTest.php, module/attribute/tests/Application/Validator/AttributeGroupCodeValidatorTest.php, module/category/tests/Application/Validator/CategoryCodeValidatorTest.php, module/category/tests/Application/Validator/CategoryExistsValidatorTest.php, module/category/tests/Application/Validator/CategoryTreeCodeUniqueValidatorTest.php, module/category/tests/Application/Validator/CategoryTreeExistsValidatorTest.php, module/condition/tests/Application/Validator/ConditionSetExistsValidatorTest.php, module/designer/tests/Application/Validator/TemplateExistsValidatorTest.php, module/multimedia/tests/Application/Validator/MultimediaExistsValidatorTest.php, module/product/tests/Application/Validator/NotTheSameProductValidatorTest.php, module/product/tests/Application/Validator/SkuUniqueValidatorTest.php, module/shared-kernel/tests/Application/Validator/SystemCodeValidatorTest.php
=> refactor: Change Validator test add typo

CHANGELOG.md, UPGRADE-1.2.md, module/exporter-file/src/Application/DependencyInjection/ErgonodeExporterFileExtension.php, module/exporter-file/src/Infrastructure/Builder/ExportAttributeBuilder.php, module/exporter-file/src/Infrastructure/Builder/ExportCategoryBuilder.php, module/exporter-file/src/Infrastructure/Builder/ExportHeaderBuilderInterface.php, module/exporter-file/src/Infrastructure/Builder/ExportOptionBuilder.php, module/exporter-file/src/Infrastructure/Builder/ExportProductBuilder.php, module/exporter-file/src/Infrastructure/Builder/ExportTemplateBuilder.php, module/exporter-file/src/Infrastructure/Builder/ExportTemplateElementBuilder.php, module/exporter-file/src/Infrastructure/Handler/Export/StartProcessCommandHandler.php, module/exporter-file/src/Infrastructure/Handler/ProcessExportCommandHandler.php, module/exporter-file/src/Resources/config/services.yml, module/exporter-file/tests/Infrastructure/Handler/Export/StartProcessCommandHandlerTest.php
Refactor Export, add taging to configuration
Issue #1542
=> refactor(exporter-file) Change load configuration

module/completeness/features/product-completness.feature, module/fixture/src/Infrastructure/Faker/TemplateIdFaker.php, module/multimedia/features/multimedia-relation.feature, module/notification/features/notification.feature, module/product-collection/features/product-collections-from-segments.feature, module/product-collection/features/product-collections-from-skus.feature, module/product-collection/features/product-collections.feature, module/product/features/batch-action-get-templates.feature, module/product/features/product-batch-action-change-attribute.feature, module/product/features/product-gallery-attribute-manipulation.feature, module/product/features/simple-product.feature, module/segment/features/segment.feature, module/workflow/features/product-status-attribute.feature, module/workflow/features/workflow-grid.feature, src/Resources/fixtures/test/templates.yaml
optimisation behat tests to use templates from fixture instead of creating new one each time 
Issue  #1365
=> refactor(template) optimisation of template behat tests

CHANGELOG.md, module/account/migrations/Version20210728123000.php, module/account/src/Infrastructure/Handler/CreateUserCommandHandler.php
Fix using redundant using method User:chnagePassword method in CreateUserCommandHandler.
Issue  #1545
=> bugfix(user) fix unnecessary sending password changing email

CHANGELOG.md, module/account/migrations/Version20210728123000.php, module/account/src/Infrastructure/Handler/CreateUserCommandHandler.php
Fix using redundant using method User:chnagePassword method in CreateUserCommandHandler.
Issue  #1545
=> bugfix(user) fix unnecessary sending password changing email (#1546)

CHANGELOG.md, module/importer-ergonode-1/src/Application/DependencyInjection/ErgonodeImporterErgonode1Extension.php, module/importer-ergonode-1/src/Infrastructure/Processor/ErgonodeImportProcess.php, module/importer-ergonode-1/src/Resources/config/services.yml
Add tag support for ErgonodeProcessorStepInterface for easier extension.
Issue #1552
=> refactor(import) add tag support for ErgonodeProcessorStepInterface

module/product/features/product-local-file-attribute-manipulation.feature, module/product/features/product-local-gallery-attribute-manipulation.feature, module/product/features/product-local-multi-select-attribute-manipulation.feature, module/product/features/product-local-numeric-attribute-manipulation.feature, module/product/features/product-local-price-attribute-manipulation.feature, module/product/features/product-local-select-attribute-manipulation.feature, module/product/features/product-local-text-attribute-manipulation.feature, module/product/features/product-local-unit-attribute-manipulation.feature, module/product/src/Application/Model/Product/Attribute/Update/UpdateAttributeValueFormModel.php, module/product/src/Application/Validator/ProductAttribute.php, module/product/src/Application/Validator/ProductAttributeValidator.php
=> feature(product) extend validator 

CHANGELOG.md, UPGRADE-1.2.md, module/batch-action/src/Application/Transport/BatchActionTransport.php, module/batch-action/src/Application/Transport/BatchActionTransportFactory.php, module/batch-action/src/Domain/Command/ProcessBatchActionEntryCommand.php, module/batch-action/src/Infrastructure/Handler/ProcessBatchActionEntryCommandHandler.php, module/batch-action/src/Infrastructure/Handler/StartBatchActionCommandHandler.php, module/batch-action/tests/Domain/Command/ProcessBatchActionEntryCommandTest.php, module/batch-action/tests/Infrastructure/Handler/ProcessBatchActionEntryCommandHandlerTest.php, module/product/features/grouping-product-batch-action-delete.feature, module/product/features/product-batch-action-change-attribute.feature, module/product/features/variable-product-batch-action-delete.feature
Add custom mass action Transport
Issue #1556
=> feature(batch-action) add Custom Transport

module/batch-action/migrations/Version20210809134500.php, module/batch-action/src/Domain/Entity/BatchAction.php, module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Handler/ProcessBatchActionEntryCommandHandler.php, module/batch-action/src/Infrastructure/Persistence/Repository/DbalBatchActionRepository.php, module/batch-action/src/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapper.php, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapperTest.php
Extend Batch action entity and add payload to it
Issue #1556
=> feature(batch-action) add BatchAction payload

module/product/src/Infrastructure/Persistence/Query/DbalProductRelationAttributeQuery.php
=> bugfix(product attribute) fix delete relation attribute strategy

module/attribute/src/Resources/translations/grid.en.yaml, module/attribute/src/Resources/translations/grid.pl.yaml, module/product-collection/src/Resources/translations/grid.en.yaml, module/product-collection/src/Resources/translations/grid.pl.yaml, module/product/src/Resources/translations/product.pl.yaml, module/segment/src/Infrastructure/Grid/SegmentGridBuilder.php, module/segment/src/Resources/translations/grid.en.yaml, module/segment/src/Resources/translations/grid.pl.yaml
=> bugfix(all)Add missing translation

module/product/src/Infrastructure/Persistence/Query/DbalProductRelationAttributeQuery.php
=> bugfix(product attribute) fix delete relation attribute strategy (#1558)

module/batch-action/migrations/Version20210809134500.php, module/batch-action/src/Application/Transport/BatchActionTransport.php, module/batch-action/src/Application/Transport/BatchActionTransportFactory.php, module/batch-action/src/Domain/Repository/BatchActionRepositoryInterface.php, module/batch-action/src/Infrastructure/Handler/BatchActionEndedEventHandler.php, module/batch-action/src/Infrastructure/Handler/ProcessBatchActionEntryCommandHandler.php, module/batch-action/src/Infrastructure/Persistence/Repository/DbalBatchActionRepository.php, module/batch-action/src/Resources/config/services.yml
Change in processing of ending batch action and sensing EndBatchActionEvent
Issue #1556
=> feature(batch-action) refactor end process

module/attribute/src/Resources/translations/grid.pl.yaml, module/designer/src/Resources/translations/grid.en.yaml, module/designer/src/Resources/translations/grid.pl.yaml
=> bugfix(all) Add missing translation

CHANGELOG.md, UPGRADE-1.2.md, module/migration/src/Command/MigrateMigrationCommand.php, module/multimedia/migrations/Version20210810100500.php, module/multimedia/migrations/Version20210811100500.php, module/multimedia/src/Infrastructure/Handler/AddMultimediaCommandHandler.php, module/multimedia/src/Infrastructure/Service/Migration/FileMigrationService.php, module/multimedia/src/Infrastructure/Service/Migration/NameMigrationService.php, module/multimedia/src/Resources/config/services.yml
=> feature(multimedia) Rename file

module/completeness/migrations/Version20210818160000.php, module/completeness/src/Infrastructure/Grid/Builder/Query/CompletenessSystemAttributeDataSetQueryBuilder.php
Fixing migrations for completeness system attribute
=> bugfix(completeness) - Fixing migrations 

module/workflow/migrations/Version20210823112541.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionGridQuery.php
=> refactor(workflow) removed unused collumns

module/api/src/Resources/config/services.yml
Fix ExceptionDebugNormalizer configuration in service.yaml file
=> bugfix(api) fix ExceptionDebugNormalizer service configuration

module/category/features/category-tree.feature, module/category/features/category.feature, module/condition/features/condition-product-belong-category.feature, module/product/features/product-atribute-relation.feature, module/product/features/product-category.feature, module/product/features/product-history.feature, module/product/features/simple-product.feature, src/Resources/fixtures/test/categories.yaml
refactor category behat test and fixture genration
Issue #1556
=> refactor(category) refactor category behat test

module/category/features/category-tree.feature, module/category/features/category.feature, module/condition/features/condition-product-belong-category.feature, module/product/features/product-atribute-relation.feature, module/product/features/product-category.feature, module/product/features/product-history.feature, module/product/features/simple-product.feature, src/Resources/fixtures/test/categories.yaml
=> Master -> branch

CHANGELOG.md, module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php
Fix `Ergonode\Channel\Infrastructure\Persistence\Query\DbalExportQuery:getProfileInfo`
and `Ergonode\Channel\Infrastructure\Persistence\Query\DbalExportQuery:getInformation`
db query performence
Issue #1591
=> bugfix(export) Fix performance of export information endpoints

composer.json, composer.lock, symfony.lock
=> build: Fixed symfony/web-profiler-bundle blocking ci update

CHANGELOG.md, module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php, module/importer/src/Infrastructure/Persistence/Query/DbalImportQuery.php
=> bugfix(export) Fix performance of export information endpoints (#1592)

module/batch-action/migrations/Version20210809134500.php, module/batch-action/src/Application/Transport/BatchActionTransport.php, module/batch-action/src/Application/Transport/BatchActionTransportFactory.php, module/batch-action/src/Test/Infrastructure/Handler/TestCreateBatchActionCommandHandler.php
=> fixt docheader

CHANGELOG.md, module/migration/src/Command/MigrateMigrationCommand.php
=> feature(migration) Add container interface support

CHANGELOG.md, module/migration/src/Command/MigrateMigrationCommand.php
=> feature(migration) Add container interface support (#1611)

CHANGELOG.md, module/segment/src/Infrastructure/Handler/Event/Application/ProductUpdateEventHandler.php, module/segment/src/Infrastructure/Handler/Event/Application/ProductUpdatedEventHandler.php
=> bugfix(segment) Fixed ProductUpdatedEvent handling

config/services_test.yaml, module/batch-action/src/Resources/config/messenger.yaml
=> bugfix(batch-action) Fixed messenger transport name

module/batch-action/migrations/Version20210909142000.php, module/batch-action/src/Application/Controller/Api/CreateBatchAction.php, module/batch-action/src/Application/Form/BatchActionForm.php, module/batch-action/src/Application/Form/Model/BatchActionFormModel.php, module/batch-action/src/Domain/Command/CreateBatchActionCommand.php, module/batch-action/src/Domain/Entity/BatchAction.php, module/batch-action/src/Infrastructure/Handler/CreateBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Persistence/Repository/DbalBatchActionRepository.php, module/batch-action/src/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapper.php, module/batch-action/tests/Domain/Command/CreateBatchActionCommandTest.php, module/batch-action/tests/Domain/Entity/BatchActionTest.php, module/batch-action/tests/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapperTest.php, module/product/features/product-batch-action-delete.feature
Extend batch action entity witch autoEndOnErrors flag
Issue #1556
=> feature(batch action) add autoEndOnError flag to batch action

CHANGELOG.md, module/condition/src/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategy.php, module/condition/tests/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategyTest.php
=> bugfix(condition) Fixed option attribute value condition

module/batch-action/src/Domain/Model/BatchActionInformationModel.php, module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php
Extending mass action endpoint (adding payload)
Issue #1556
=> bugfix(batch-action) - Extending mass action endpoint (adding payload)

CHANGELOG.md, module/channel/src/Application/Form/Model/SchedulerModel.php, module/channel/src/Application/Form/SchedulerForm.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/channel/src/Domain/Entity/Scheduler.php
=> bugfix(channel) Allowed empty values for deactivated scheduler

CHANGELOG.md, config/services_test.yaml, module/batch-action/src/Domain/Model/BatchActionInformationModel.php, module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php, module/batch-action/src/Resources/config/messenger.yaml, module/channel/src/Application/Form/Model/SchedulerModel.php, module/channel/src/Application/Form/SchedulerForm.php, module/channel/src/Domain/Command/UpdateSchedulerCommand.php, module/channel/src/Domain/Entity/Scheduler.php, module/condition/src/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategy.php, module/condition/tests/Infrastructure/Condition/Calculator/OptionAttributeValueConditionCalculatorStrategyTest.php
=> Master -> feature

module/batch-action/features/batch-action.feature, module/batch-action/src/Application/Controller/Api/EndBatchAction.php, module/batch-action/src/Application/Form/BatchActionForm.php, module/batch-action/src/Domain/Command/EndBatchActionCommand.php, module/batch-action/src/Domain/Entity/BatchAction.php, module/batch-action/src/Domain/Model/BatchActionInformationModel.php, module/batch-action/src/Domain/ValueObject/BatchActionStatus.php, module/batch-action/src/Infrastructure/Handler/EndBatchActionCommandHandler.php, module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php, module/batch-action/src/Resources/config/services.yml, module/batch-action/tests/Infrastructure/Persistence/Repository/Mapper/DbalBatchActionMapperTest.php, module/product/features/product-batch-action-delete.feature
Add `/batch-action/{action}/end` endpoirt for ending batch action
Issue #1556
=> feature(batch action) add batch action end endpoint

CHANGELOG.md, module/condition/src/Infrastructure/Condition/Calculator/NumericAttributeValueConditionCalculatorStrategy.php, module/condition/src/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategy.php, module/condition/src/Infrastructure/Condition/Calculator/TextAttributeValueConditionCalculatorStrategy.php, module/condition/tests/Infrastructure/Condition/Calculator/NumericAttributeValueConditionCalculatorStrategyTest.php, module/condition/tests/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategyTest.php, module/condition/tests/Infrastructure/Condition/Calculator/TextAttributeValueConditionCalculatorStrategyTest.php
=> bugfix(condition) Fixed handling null attribute value in conditions

CHANGELOG.md, module/multimedia/src/Infrastructure/Grid/MultimediaGridBuilder.php, module/multimedia/src/Infrastructure/Persistence/Query/DbalMultimediaGridQuery.php
Delete slow subselect relation grid query.
=> bugfix(multimedia) grid acceleration by remove column

module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductFileAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductGalleryAttributeStrategy.php, module/importer/src/Infrastructure/Action/Process/Product/Strategy/ImportProductImageAttributeStrategy.php, module/multimedia/src/Domain/Query/MultimediaQueryInterface.php, module/multimedia/src/Infrastructure/Persistence/Query/DbalMultimediaQuery.php
Ad support to import attribute value for Gallery Image and file attribute
Issue #1637
=> feature(import) add multiemdia attribute support in product import

module/product/features/product-grid-post.feature, module/product/features/product-grid.feature, module/product/src/Infrastructure/Grid/ProductGridBuilder.php
Fix product grid default sorting
=> bugfix(product) fix product grid default sorting

CHANGELOG.md, UPGRADE-1.2.md, module/attribute/features/attribute-validate.feature, module/attribute/src/Application/Validator/AttributeCode.php, module/attribute/src/Domain/ValueObject/AttributeCode.php, module/attribute/tests/Domain/ValueObject/AttributeCodeTest.php
Add attribute code validation
Issue #1644
=> feature(attribute) - Add attribute code validation

CHANGELOG.md, UPGRADE-1.2.md, module/attribute/migrations/Version20211102105000.php, module/attribute/src/Domain/Event/Option/OptionMovedEvent.php, module/attribute/tests/Domain/Event/Option/OptionMovedEventTest.php
Add new relation table `attribute_options` migration
Issue #1685
=> feature(attribute) add new option-attribute relation table migration

CHANGELOG.md, UPGRADE-1.2.md, module/segment/src/Application/Event/ProductExcludedFromSegmentEvent.php, module/segment/src/Application/Event/ProductIncludedInSegmentEvent.php, module/segment/src/Infrastructure/Handler/Command/CalculateSegmentProductCommandHandler.php, module/segment/src/Infrastructure/Service/SegmentProductService.php
=> feature(segment) Product availability events

module/segment/src/Infrastructure/Service/SegmentProductService.php
=> bugfix(segment) Missing parameters bind

module/attribute/migrations/Version20211102105000.php, module/attribute/src/Domain/Event/Attribute/AttributeOptionAddedEvent.php, module/attribute/src/Domain/Event/Attribute/AttributeOptionMovedEvent.php, module/attribute/src/Domain/Event/Attribute/AttributeOptionRemovedEvent.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/AbstractDbalAttributeOptionEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionAddedEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionRemovedEventProjector.php, module/attribute/tests/Domain/Event/Attribute/AttributeOptionAddedEventTest.php, module/attribute/tests/Domain/Event/Attribute/AttributeOptionMovedEventTest.php, module/attribute/tests/Domain/Event/Attribute/AttributeOptionRemovedEventTest.php
Add new attribute domain events for  adding, removing and changing position of attribute options 
Issue #1685
=> feature(attribute) add attribute option sorting events

module/attribute/migrations/Version20211025100000.php
Unification of currency names
Issue #1675
- [] I have added tests that prove my fix is effective or that my feature works
=> feature(attribute) Unification of currency names

module/attribute/migrations/Version20211102105000.php, module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php, module/attribute/src/Domain/Event/Attribute/AttributeOptionAddedEvent.php, module/attribute/src/Domain/Event/Attribute/AttributeOptionMovedEvent.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionAddedEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php, module/attribute/tests/Domain/Entity/Attribute/AbstractOptionAttributeTest.php, module/attribute/tests/Domain/Event/Attribute/AttributeOptionAddedEventTest.php, module/attribute/tests/Domain/Event/Attribute/AttributeOptionMovedEventTest.php
Extended `AbstratOptionAggreate` with methods to manipulate relations with options
Issue #1685
=> feature(attribute) extend AbstractOptionAggregate with option support

CHANGELOG.md, module/attribute/features/attribute-multi-select.feature, module/attribute/src/Application/Form/Model/Option/SimpleOptionModel.php
Fixing option name validation
Issue #1695
=> bugfix(attribute) - Fixing option name validation

CHANGELOG.md, UPGRADE-1.2.md, module/migration/src/Command/GenerateMigrationCommand.php, module/multimedia/migrations/Version20211103071053.php, module/multimedia/src/Application/DependencyInjection/CompilerPass/ThumbnailStorageCompilerPass.php, module/multimedia/src/ErgonodeMultimediaBundle.php, module/multimedia/src/Infrastructure/Handler/DeleteMultimediaCommandHandler.php, module/multimedia/src/Infrastructure/Handler/Event/DeleteThumbnailStorageHandler.php, module/multimedia/tests/Infrastructure/Handler/DeleteMultimediaCommandHandlerTest.php, module/multimedia/tests/Infrastructure/Handler/Event/DeleteThumbnailStorageHandlerTest.php
=> bugfix(multimedia) delete physical files

UPGRADE-1.2.md, module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/migrations/Version20211102105000.php, module/attribute/src/Application/Controller/Api/Option/OptionCreateAction.php, module/attribute/src/Application/Form/Model/Option/SimpleOptionModel.php, module/attribute/src/Application/Form/SimpleOptionForm.php, module/attribute/src/Domain/Command/Option/CreateOptionCommand.php, module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php, module/attribute/src/Infrastructure/Handler/Option/CreateOptionCommandHandler.php, module/attribute/src/Infrastructure/Handler/Option/DeleteOptionCommandHandler.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/AbstractDbalAttributeOptionEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionRemovedEventProjector.php, module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php
Refactor adding endpoit to support sorting options
Issue #1685
=> feature(attribute) refactor add option endpoint

CHANGELOG.md, module/api/src/Application/EventListener/ExceptionListener.php, module/api/src/Application/EventListener/ResponseSubscriber.php, module/api/tests/Application/EventListener/ExceptionListenerTest.php, module/api/tests/Application/EventListener/ResponseSubscriberTest.php, module/category/src/Application/Controller/Api/CategoryTypeConfigurationAction.php, module/channel/src/Application/Controller/Api/ChannelTypeConfigurationAction.php, module/importer/src/Application/Controller/Api/Source/SourceTypeConfigurationAction.php
=> bugfix(api) Fixed API returned Content-Type header

module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php
=> bugfix(attribute) repair many option relation

module/grid/src/Filter/Builder/MultiselectFilterBuilder.php
=> bugfix(grid) - Fixing adding from list to collections

module/product/src/Infrastructure/Persistence/Query/DbalProductChildrenAvailableGridQuery.php
=> bugfix(product) change product children gird

config/services_test.yaml, module/segment/features/segment.feature, module/segment/src/Test/TestSegmentEventHandler.php
=> tests: Restored segment tests

CHANGELOG.md, module/api/src/Application/EventListener/RequestBodyListener.php, module/api/tests/Application/EventListener/RequestBodyListenerTest.php
=> bugfix(api) Fixed handling invalid json request content

module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php
=> refactor(attribute) Change option query

module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/migrations/Version20211102105000.php, module/attribute/src/Application/Controller/Api/Option/OptionMoveAction.php, module/attribute/src/Application/Form/Model/Option/OptionMoveModel.php, module/attribute/src/Application/Form/OptionMoveForm.php, module/attribute/src/Domain/Command/Option/MoveOptionCommand.php, module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php, module/attribute/src/Infrastructure/Handler/Option/MoveOptionCommandHandler.php, module/attribute/src/Infrastructure/Handler/Option/UpdateOptionCommandHandler.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/AbstractDbalAttributeOptionEventProjector.php, module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php, module/attribute/src/Resources/config/nelmio_api_doc.yaml, module/attribute/tests/Domain/Entity/Attribute/AbstractOptionAttributeTest.php
Add sorting option endpoint ```PUT /attributes/{attribute}/options/{option}/move```
Issue #1685
=> feature(attribute) add option sorting endpoint

module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/src/Application/Form/Model/Option/OptionMoveModel.php, module/attribute/src/Application/Form/Model/Option/SimpleOptionModel.php, module/attribute/src/Application/Validator/OptionExists.php, module/attribute/src/Application/Validator/OptionExistsValidator.php
Add position option validation do add and move option endpoints
Issue #1685
=> feature(attribute) add option position validation

composer.json, composer.lock
=> configuration: composer up

CHANGELOG.md, module/attribute/src/Infrastructure/Persistence/Repository/EventStoreAttributeRepository.php, module/category/src/Infrastructure/Persistence/Repository/EventStoreCategoryRepository.php, module/designer/src/Infrastructure/Persistence/Repository/EventStoreTemplateRepository.php, module/event-sourcing/src/Domain/AbstractAggregateRoot.php, module/event-sourcing/src/Infrastructure/Manager/Decorator/EventStoreManagerCacheDecorator.php, module/event-sourcing/tests/Domain/AbstractAggregateRootTest.php, module/product/src/Infrastructure/Persistence/Repository/EventStoreProductRepository.php, module/segment/src/Infrastructure/Persistence/Repository/EventStoreSegmentRepository.php
=> feature(event-sourcing) AbstractAggregateRoot isDirty method

module/attribute/migrations/Version20211117000000.php, module/attribute/src/Infrastructure/Mapper/Strategy/MultiSelectAttributeMapperStrategy.php
Fix incorrect value setting for first multiselect empty value (empty string instead of null)
=> bugfix(product) fix adding multiselec attribute empty value

CHANGELOG.md, module/batch-action/src/Application/Serializer/Normalizer/PayloadCommandNormalizer.php, module/batch-action/tests/Application/Serializer/Normalizer/PayloadCommandNormalizerTest.php, module/core/src/Application/Serializer/Normalizer/AggregateRootNormalizer.php, module/core/src/Application/Serializer/Normalizer/EntityNormalizer.php, module/core/tests/Application/Serializer/Normalizer/AggregateRootNormalizerTest.php, module/core/tests/Application/Serializer/Normalizer/EntityNormalizerTest.php
=> perf: Using Closure API instead of Reflection

module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php, module/attribute/tests/Domain/Entity/Attribute/AbstractOptionAttributeTest.php
Ignoring transfer of options in the same position (prevent redundant event generation)
=> bugfix(attribute) ignoring moving option in the same position

module/importer-ergonode-1/src/Application/Form/DownloadHeaderType.php
Fix header form validation for emtpy headers
=> bugfix(importer) fix ergonode format import header form validation

module/importer-ergonode-1/src/Application/Model/ImporterErgonodeConfigurationModel.php, module/importer-ergonode-1/src/Domain/Entity/ErgonodeZipSource.php
=> refactor(importer-ergonode-1) Extendible ErgonodeZipSource

CHANGELOG.md, module/product/features/variable-product-add-from-sku.feature, module/product/src/Domain/Query/ProductQueryInterface.php, module/product/src/Domain/Query/ProductWithVariantsQueryInterface.php, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php, module/product/src/Infrastructure/Strategy/Relationship/ProductWithVariantsAttributeRelationshipStrategy.php
Relation strategy added for attributes added as bindings
Issue # 
#1731
=> bugfix(multimedia) - Relation strategy added for attributes added as bindings

module/account/src/Domain/Entity/User.php, module/authentication/src/Application/Security/Provider/EmailUserProvider.php, module/authentication/src/Application/Security/Provider/IdUserProvider.php, module/authentication/tests/Application/Security/Provider/EmailUserProviderTest.php, module/authentication/tests/Application/Security/Provider/IdUserProviderTest.php, module/core/src/Application/Security/User/CachedUser.php, module/event-sourcing/src/Infrastructure/Manager/EventStoreManager.php, module/event-sourcing/tests/Infrastructure/Manager/EventStoreManagerTest.php, module/product/src/Infrastructure/Filter/BatchAction/ProductBatchActionFilter.php, module/product/tests/Infrastructure/Filter/BatchAction/ProductBatchActionFilterTest.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
=> refactor: Removed deprecations

CHANGELOG.md, config/packages/test/ergonode_batch_action.yaml, config/packages/test/ergonode_core.yaml, config/packages/test/ergonode_segment.yaml, config/services_test.yaml, module/batch-action/src/Application/DependencyInjection/Configuration.php, module/batch-action/src/Application/DependencyInjection/ErgonodeBatchActionExtension.php, module/batch-action/src/Resources/config/test.yaml, module/core/src/Application/DependencyInjection/Configuration.php, module/core/src/Application/DependencyInjection/ErgonodeCoreExtension.php, module/core/src/Resources/config/test.yaml, module/segment/src/Application/DependencyInjection/Configuration.php, module/segment/src/Application/DependencyInjection/ErgonodeSegmentExtension.php, module/segment/src/Resources/config/test.yaml, module/segment/src/Test/TestSegmentEventHandler.php
=> feature: Test modules config

module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/src/Application/Controller/Api/Option/OptionsReadAction.php, module/attribute/src/Domain/Query/OptionQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php
Extend `GET attribute/{attribute}/options` endpoint with relations flag
Issue #1685
=> feature(attribute) extend GET options endpoint with relation information

module/multimedia/features/multimedia-relation.feature, module/multimedia/features/multimedia.feature
Fix incorrect header send in behat test for multimedia upload
=> bugfix(test): fix behat test for multimedia upload header type

CHANGELOG.md, UPGRADE-1.3.md, module/workflow/src/Application/Controller/Api/Product/ProductWorkflowAction.php, module/workflow/src/Application/Request/ParamConverter/AbstractWorkflowParamConverter.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Domain/Factory/AddStatusToProductFactoryDecorator.php, module/workflow/src/Domain/Provider/WorkflowProvider.php, module/workflow/src/Domain/Provider/WorkflowProviderInterface.php, module/workflow/src/Domain/Query/TransitionQueryInterface.php, module/workflow/src/Infrastructure/Handler/Event/ProductValueChangedEventHandler.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionQuery.php, module/workflow/src/Infrastructure/Strategy/Relationship/DefaultStatusRelationshipStrategy.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusWorkflowRelationshipStrategy.php, module/workflow/tests/Application/Request/ParamConverter/AbstractWorkflowParamConverterTest.php, module/workflow/tests/Domain/Provider/WorkflowProviderTest.php, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
Refactoring of Workflow provider for language context usage
Issue #1752
=> refactoring(workflow) Refactor WorkflowProvider

UPGRADE-1.3.md, module/attribute/features/attribute-multi-select.feature, module/attribute/features/attribute-select.feature, module/attribute/migrations/Version20211102105000.php, module/attribute/src/Domain/Entity/AbstractOption.php, module/attribute/src/Domain/Event/Option/OptionCreatedEvent.php, module/attribute/src/Domain/Query/OptionQueryInterface.php, module/attribute/src/Infrastructure/Handler/Option/CreateOptionCommandHandler.php, module/attribute/src/Infrastructure/Persistence/Projector/Option/DbalOptionCreatedEventProjector.php, module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php, module/attribute/src/Infrastructure/Persistence/Query/DbalOptionQuery.php, module/attribute/tests/Domain/Entity/AbstractOptionTest.php, module/attribute/tests/Domain/Event/Option/OptionCreatedEventTest.php, module/exporter-file/src/Infrastructure/Builder/Option/ExportOptionAttributeBuilder.php, module/exporter-file/src/Infrastructure/Processor/OptionProcessor.php, module/exporter-file/tests/Infrastructure/Processor/OptionProcessorTest.php
=> feature(attribute) Change option relation in db

CHANGELOG.md, UPGRADE-1.3.md, config/packages/ergonode_workflow.yaml, module/condition/src/Domain/Condition/AttributeTranslationExistsCondition.php, module/condition/src/Infrastructure/Condition/Calculator/AttributeTranslationExistsConditionCalculatorStrategy.php, module/condition/src/Infrastructure/Condition/Configuration/AttributeTranslationExistsConditionConfigurationStrategy.php, module/condition/src/Infrastructure/Condition/Validator/AttributeTranslationExistsConditionValidatorStrategy.php, module/condition/src/Resources/config/serialization.yaml, module/condition/src/Resources/translations/condition.en.yaml, module/condition/src/Resources/translations/condition.pl.yaml, module/condition/tests/Infrastructure/Condition/Calculator/AttributeTranslationExistsConditionCalculatorStrategyTest.php, module/workflow/src/Application/Controller/Api/Product/ProductWorkflowAction.php, module/workflow/src/Application/Request/ParamConverter/AbstractWorkflowParamConverter.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Domain/Factory/AddStatusToProductFactoryDecorator.php, module/workflow/src/Domain/Provider/WorkflowProvider.php, module/workflow/src/Domain/Provider/WorkflowProviderInterface.php, module/workflow/src/Domain/Query/TransitionQueryInterface.php, module/workflow/src/Infrastructure/Handler/Event/ProductValueChangedEventHandler.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/src/Infrastructure/Persistence/Query/DbalTransitionQuery.php, module/workflow/src/Infrastructure/Strategy/Relationship/StatusWorkflowRelationshipStrategy.php, module/workflow/tests/Application/Request/ParamConverter/AbstractWorkflowParamConverterTest.php, module/workflow/tests/Domain/Provider/WorkflowProviderTest.php, module/workflow/tests/Persistence/Dbal/Query/DbalStatusQueryTest.php
=> master - feature

composer.json, composer.lock
=> feature(attribute) composer test shopware6 option sorting

module/attribute/migrations/Version20211102105000.php
=> bugfix(attribute)option sort migration

module/workflow/features/transitions.feature, module/workflow/src/Domain/Entity/AbstractWorkflow.php
Fix incorrect use of method getFrom instead of getFrom in Workflow Aggregate
Issue  #1752
=> bugfix(workflow) fix remove trasition event processing in Workflow agregate

UPGRADE-1.3.md, config/packages/ergonode_workflow.yaml, module/workflow/migrations/Version20211208071117.php
=> feature(workflow) limitation workflow condition

UPGRADE-1.3.md, module/workflow/features/workflow.feature, module/workflow/src/Application/Form/Model/Workflow/WorkflowFormModel.php, module/workflow/src/Application/Form/Workflow/WorkflowForm.php, module/workflow/src/Domain/Command/Workflow/CreateWorkflowCommand.php, module/workflow/src/Domain/Command/Workflow/UpdateWorkflowCommand.php, module/workflow/src/Domain/Factory/WorkflowFactory.php, module/workflow/src/Infrastructure/Factory/Command/Create/CreateWorkflowCommandFactory.php, module/workflow/src/Infrastructure/Factory/Command/Update/UpdateWorkflowCommandFactory.php, module/workflow/src/Infrastructure/Handler/Workflow/CreateWorkflowCommandHandler.php, module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowCommandHandler.php, module/workflow/tests/Domain/Command/Workflow/CreateWorkflowCommandTest.php, module/workflow/tests/Domain/Command/Workflow/UpdateWorkflowCommandTest.php, module/workflow/tests/Domain/Factory/WorkflowFactoryTest.php, module/workflow/tests/Infrastructure/Factory/Command/Create/CreateWorkflowCommandFactoryTest.php, module/workflow/tests/Infrastructure/Factory/Command/Update/UpdateWorkflowCommandFactoryTest.php, src/Resources/fixtures/develop/workflow.yaml, src/Resources/fixtures/e2e/workflow.yaml, src/Resources/fixtures/fixture.yaml, src/Resources/fixtures/test/workflow.yaml
Add support for default status set on workflow creation
Issue #1752
=> feature(workflow) add default status support for workflow creation

composer.json, composer.lock
=> configuration: composer.json

module/condition/src/Domain/Query/ConditionSetQueryInterface.php, module/condition/src/Infrastructure/Persistence/Query/DbalConditionSetQuery.php, module/condition/src/Infrastructure/Strategy/Relationship/ConditionSetCategoryRelationshipStrategy.php
=> bugfix(condition set) Add relation resolver to category

module/workflow/src/Infrastructure/Grid/TransitionGridBuilder.php
Fix incorrect transition grid status information (id instead of code)
=> bugfix(workflow) fix incorrect grid status code information

module/core/src/Infrastructure/Service/GuzzleDownloader.php
Add timout configuration parameter to GuzzleDownloader to prevent connection lock. 
Issue #1749
=> feature(core) add timeout support to GuzzleDownloader

CHANGELOG.md, module/completeness/src/Application/Event/ProductCompletenessCalculatedEvent.php, module/completeness/src/Infrastructure/Handler/Command/ProductCompletenessCalculateCommandHandler.php, module/segment/composer.json, module/segment/src/Infrastructure/Handler/Event/Application/ProductCompletenessCalculatedEventHandler.php
=> bugfix(completeness,segment) Fixed not recalculating segment for product on completeness update

module/workflow/features/workflow.feature, module/workflow/migrations/Version20211208071117.php, module/workflow/src/Application/Form/Workflow/WorkflowForm.php, module/workflow/src/Domain/Command/Workflow/UpdateWorkflowCommand.php, module/workflow/src/Infrastructure/Factory/Command/Update/UpdateWorkflowCommandFactory.php, module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowCommandHandler.php, module/workflow/tests/Domain/Command/Workflow/UpdateWorkflowCommandTest.php
=> bugfix(workflow) change transition without default status

CHANGELOG.md
=> bugfix: Fixed changelog version

module/multimedia/features/multimedia-relation.feature, module/multimedia/features/multimedia.feature
Fix - beha tests incorrect headers
=> configuration: fix behat test for multimedia upload header type

composer.json, composer.lock, module/core/src/Infrastructure/Service/GuzzleDownloader.php, module/workflow/src/Domain/Condition/WorkflowConditionInterface.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Domain/Entity/Transition.php, module/workflow/src/Infrastructure/Handler/Event/ProductValueChangedEventHandler.php, module/workflow/src/Infrastructure/Handler/Workflow/AddWorkflowTransitionCommandHandler.php, module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowTransitionCommandHandler.php, module/workflow/tests/Domain/Entity/TransitionTest.php
Remove AbstractEntity support from Transition class
Issue #1752
=> refactor(workflow) change transition entity

module/workflow/src/Domain/Condition/AttributeExistsWorkflowCondition.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Domain/Entity/Transition.php, module/workflow/src/Domain/Event/Transition/TransitionConditionSetChangedEvent.php, module/workflow/src/Domain/Event/Workflow/WorkflowTransitionConditionsChangedEvent.php, module/workflow/src/Resources/config/serialization.yaml, module/workflow/tests/Domain/Event/Workflow/WorkflowTransitionConditionsChangedEventTest.php
Extend Workflow and Transition with support for WorkflwoConditionInterface
=> refactor(workflow) add support for WorkflwoConditionInterface to Workflow/Transition

composer.json, composer.lock
=> build: update shopware

module/workflow/migrations/Version20211214160000.php
Adding index column in status projection table
Issue #1791
=> feature(workflow) - Adding index column in status projection table

module/workflow/features/condition.feature, module/workflow/src/Application/Controller/Api/Condition/WorkflowConditionConfigurationReadAction.php, module/workflow/src/Resources/config/routes.yml, module/workflow/tests/Application/Controller/Api/Condition/WorkflowConditionConfigurationReadActionTest.php
=> feature(workflow) Add condition config endpint

config/packages/ergonode_workflow.yaml, module/workflow/features/condition.feature, module/workflow/src/Application/Controller/Api/Condition/WorkflowConditionConfigurationReadAction.php, module/workflow/src/Application/Controller/Api/Condition/WorkflowConditionReadAction.php, module/workflow/src/Application/DependencyInjection/ErgonodeWorkflowExtension.php, module/workflow/src/ErgonodeWorkflowBundle.php, module/workflow/src/Infrastructure/Provider/WorkflowConditionDictionaryProvider.php, module/workflow/src/Resources/config/routes.yml, module/workflow/src/Resources/config/services.yml, module/workflow/tests/Application/Controller/Api/Condition/WorkflowConditionReadActionTest.php, module/workflow/tests/Infrastructure/Provider/WorkflowConditionDictionaryProviderTest.php
=> feature(workflow) Add condition dictionary

module/workflow/features/condition-attribute-exists.feature, module/workflow/features/condition-product-completeness.feature, module/workflow/features/condition-role-is.feature, module/workflow/features/condition-user-is.feature, module/workflow/features/condition.feature, module/workflow/features/transitions.feature, module/workflow/migrations/Version20211208071117.php, module/workflow/src/Application/Controller/Api/Transition/TransitionChangeAction.php, module/workflow/src/Application/Controller/Api/Transition/TransitionConditionsChangeAction.php, module/workflow/src/Application/Controller/Api/Transition/TransitionConditionsReadAction.php, module/workflow/src/Application/Controller/Api/Transition/TransitionDeleteAction.php, module/workflow/src/Application/Controller/Api/Transition/TransitionReadAction.php, module/workflow/src/Application/DependencyInjection/ErgonodeWorkflowExtension.php, module/workflow/src/Domain/Command/Workflow/UpdateWorkflowTransitionConditionsCommand.php, module/workflow/src/Domain/Entity/AbstractWorkflow.php, module/workflow/src/Infrastructure/Condition/ProductCompletenessWorkflowCondition.php, module/workflow/src/Infrastructure/Condition/Validator/ProductCompletenessWorkflowConditionValidator.php, module/workflow/src/Infrastructure/Handler/Workflow/UpdateWorkflowTransitionConditionsCommandHandler.php, module/workflow/src/Infrastructure/Provider/WorkflowConditionValidatorProvider.php, module/workflow/src/Infrastructure/Validator/WorkflowConditionValidatorBuilder.php, module/workflow/src/Resources/config/serialization.yaml, module/workflow/src/Resources/config/services.yml
Add endpoint for GET and PUT condition for specific transition in worflow
=> feature(workflow) add workflow condition enpoints

module/attribute/src/Application/Form/Model/UpdateAttributeGroupFormModel.php
=> feature(attribute) - Changing category attribute group translation validation

module/workflow/features/status-order.feature, module/workflow/src/Infrastructure/Grid/StatusGridBuilder.php
Status grid changing default sorting
Issue #1791
=> feature(workflow) - Status grid changing default sorting

module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php
=> feature(workflow) Sort widget Status

module/workflow/src/Infrastructure/Persistence/Query/DbalStatusGridQuery.php, module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php
Adding index sorting of status selects
Issue #1791
=> feature(workflow) - Adding index sorting of status selects

module/workflow/src/Application/Controller/Api/Product/ProductWorkflowAction.php
=> bugfix(workflow) Fixed retrieving product statuses for language

module/workflow/src/Infrastructure/Provider/Strategy/StatusAttributeValueConstraintStrategy.php
=> bugfix(workflow) Disallowing to set not existing status

module/completeness/src/Infrastructure/Grid/Builder/Query/CompletenessSystemAttributeDataSetQueryBuilder.php, module/core/src/Infrastructure/Service/GuzzleDownloader.php
Fix incorrect grid presentation for not calculated new completeness (null value).
=> bugfix(completeness) Fix grid return value for completeness

composer.lock
=> build: Bumped Symfony packages

UPGRADE-1.3.md, module/core/src/Infrastructure/Service/GuzzleDownloader.php, module/workflow/src/Application/DependencyInjection/ErgonodeWorkflowExtension.php, module/workflow/src/Application/Transport/StatusTransport.php, module/workflow/src/Application/Transport/StatusTransportFactory.php, module/workflow/src/Domain/Command/Product/SetProductDefaultWorkflowStatusCommand.php, module/workflow/src/Infrastructure/Handler/Product/SetProductDefaultWorkflowStatusCommandHandler.php, module/workflow/src/Resources/config/messenger.yaml
Add new custom Messnger Transport `StatusTransport`.
Setup new receiver `status`. It's required for setting workflow statuses to product when new Language is added in `LanguageTree`
Issue #1752
=> feature(workflow) Workflow status custom transport

CHANGELOG.md, UPGRADE-1.3.md, composer.json, composer.lock, module/attribute/src/Application/Form/Model/CreateAttributeGroupFormModel.php, module/attribute/src/Application/Form/Model/UpdateAttributeGroupFormModel.php, module/category/features/category.feature, module/category/src/Application/Model/CategoryFormModel.php, module/completeness/src/Infrastructure/Grid/Builder/Query/CompletenessSystemAttributeDataSetQueryBuilder.php, module/workflow/src/Application/Controller/Api/Product/ProductWorkflowAction.php, module/workflow/src/Application/DependencyInjection/ErgonodeWorkflowExtension.php, module/workflow/src/Application/Transport/StatusTransport.php, module/workflow/src/Application/Transport/StatusTransportFactory.php, module/workflow/src/Domain/Command/Product/SetProductDefaultWorkflowStatusCommand.php, module/workflow/src/Infrastructure/Handler/Product/SetProductDefaultWorkflowStatusCommandHandler.php, module/workflow/src/Infrastructure/Provider/Strategy/StatusAttributeValueConstraintStrategy.php, module/workflow/src/Resources/config/messenger.yaml
=> Master to feature 

module/workflow/src/Infrastructure/Persistence/Query/DbalStatusQuery.php, module/workflow/src/Infrastructure/Query/ProductWorkflowQuery.php
Adding index sorting to status per product endpoint
Issue #1791
=> feature(workflow) - Adding index sorting to status per product endpoint

CHANGELOG.md
=> docs: Changelog entry

CHANGELOG.md, module/product/migrations/Version20211219110000.php, module/product/src/Application/Handler/AbstractAuditEventHandler.php, module/product/src/Application/Handler/AuditProductCreatedEventHandler.php, module/product/src/Application/Handler/AuditProductDeletedEventHandler.php, module/product/src/Application/Handler/AuditProductUpdatedEventHandler.php, module/product/src/Domain/Factory/ProductFactory.php, module/product/src/Infrastructure/Grid/Builder/Query/CreatedAtSystemAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/CreatedBySystemAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/EditedAtSystemAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/EditedBySystemAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Handler/Attribute/AbstractValueCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/ChangeProductAttributeCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/ChangeProductAttributesCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributeCommandHandler.php, module/product/src/Infrastructure/Handler/Attribute/RemoveProductAttributesCommandHandler.php, module/product/src/Infrastructure/Persistence/Projector/AbstractProductProjector.php, module/product/src/Infrastructure/Persistence/Projector/Binding/DbalBindAddedToProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Binding/DbalBindRemovedFromProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Child/DbalChildAddedToProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/Child/DbalChildRemovedFromProductEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductAddedToCategoryEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductCreatedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductRemovedFromCategoryEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductTemplateChangedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueAddedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueChangedEventProjector.php, module/product/src/Infrastructure/Persistence/Projector/DbalProductValueRemovedEventProjector.php, module/product/src/Infrastructure/Persistence/Query/DbalProductQuery.php, module/product/src/Resources/config/services.yml
=> bugfix(product) fix audit information generation for product

CHANGELOG.md, UPGRADE-1.3.md, module/completeness/src/Infrastructure/Grid/Builder/Query/CompletenessSystemAttributeDataSetQueryBuilder.php, module/completeness/src/Infrastructure/Handler/Event/Application/LanguageTreeUpdatedEventHandler.php, module/completeness/src/Infrastructure/Handler/Event/Application/ProductCreatedEventHandler.php, module/completeness/src/Infrastructure/Persistence/Manager/CompletenessManager.php
=> refactor(completeness) Change completeness first save after create new product

CHANGELOG.md, module/attribute/src/Domain/Query/OptionTranslationQueryInterface.php, module/attribute/src/Infrastructure/Persistence/Query/DbalOptionTranslationQuery.php, module/designer/src/Domain/Builder/Strategy/AttributeViewTemplateElementStrategy.php
Fix Speed of building AttributeViewTemplateElementStrategy for Option attribute. 
Adding nee optimise query for this case.
Issue #1829
=> bugfix(product) fix AttributeViewTemplateElementStrategy db query speed

CHANGELOG.md, module/batch-action/src/Application/DependencyInjection/ErgonodeBatchActionExtension.php, module/product/src/Application/DependencyInjection/ErgonodeProductExtension.php
Fixing configuration tag
Issue #
=> Fixing configuration tag

module/workflow/src/Infrastructure/Query/ProductWorkflowQuery.php
Fix incorrect language in workflow status calculation.
=> fix(workflow) fix incorrect language in workflow status

module/workflow/src/Infrastructure/Condition/Calculator/AttributeExistsWorkflowConditionCalculator.php, module/workflow/tests/Infrastructure/Condition/Calculator/AttributeExistsWorkflowConditionCalculatorTest.php
Fix miising language condition calculatin in AttributeExistWorkflowCondition
Issue #
=> bugfix(workflow) add missing AttributeExistsCondition language context

module/attribute/src/Resources/config/nelmio_api_doc.yaml, module/product/src/Application/Controller/Api/Attribute/DeleteProductsAttributesAction.php, module/product/src/Application/Controller/Api/Attribute/UpdateProductsAttributesAction.php, module/product/src/Resources/config/nelmio_api_doc.yaml
Fixing nelmio documentation
Issue #1765
=> bugfix(product) - Fixing nelmio documentation

module/workflow/src/Infrastructure/Mapper/Strategy/StatusAttributeMapperStrategy.php, module/workflow/tests/Infrastructure/Mapper/Strategy/StatusAttributeMapperStrategyTest.php
Fix incorrect validation when adding Workflow Status to product
=> bugfix(workflow) fix adding status to product validation

CHANGELOG.md, module/product/src/Infrastructure/Grid/Builder/Query/AbstractAttributeDataSetBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/FileAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/GalleryAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/ProductRelationAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php, module/product/tests/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/ImageAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/SelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextareaAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilderTest.php
Optimise Query for product grid query bilders
Issue #1848
=> bugfix(product) Optymise product grid query building

CHANGELOG.md, module/product/src/Infrastructure/Grid/Builder/Query/AbstractAttributeDataSetBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/FileAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/GalleryAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/ProductRelationAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php, module/product/tests/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/ImageAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/MultiSelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/SelectAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/TextareaAttributeDataSetQueryBuilderTest.php, module/product/tests/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilderTest.php
Optimise Query for product grid query builders
Issue #1848
=> bugfix(product) Optymise product grid query building (#1849)

config/packages/test/ergonode_workflow.yaml, module/workflow/src/Application/DependencyInjection/Configuration.php, module/workflow/src/Application/DependencyInjection/ErgonodeWorkflowExtension.php, module/workflow/src/Resources/config/test.yaml, module/workflow/src/Test/TestStatusEventHandler.php
=> feature(workflow) Status test transport

depfile.yaml
=> bugfix: Removed invalid deptrac entry

.github/workflows/tests.yml, module/account/tests/Application/Form/DataTransformer/PrivilegeDataTransformerTest.php
=> ci: Artifacts

module/core/src/Infrastructure/Exception/NotAcceptedHeaderTypeException.php, module/core/src/Infrastructure/Service/CurlDownloader.php, module/core/src/Infrastructure/Service/Decorator/CacheDownloaderDecorator.php, module/core/src/Infrastructure/Service/DownloaderInterface.php, module/core/src/Infrastructure/Service/GuzzleDownloader.php, module/core/src/Test/TestDownloaderDecorator.php, module/importer/src/Domain/Factory/MultimediaFileFactory.php, module/multimedia/src/Infrastructure/Provider/MultimediaExtensionProvider.php, module/multimedia/tests/Infrastructure/Provider/MultimediaExtensionProviderTest.php
=> feature(core) extend downloader at accept types

module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php
Fix Query type casing for large numbers of results.
Issue #1848
=> bugfix(product) fix type casting problme in grid query

module/account/src/Infrastructure/Grid/AccountGridBuilder.php
=> bugfix(account) Fix grid column language

composer.json, composer.lock
Lock fakerphp/faker on 1.17 due to problems with fixture generation on version 1.18
=> configuration: lock fakerphp/faker on 1.17

module/attribute/migrations/Version20211102104000.php
Add migration to clean unused event witch options added to attributes
=> bugfix(option) add migration to clean unnecesery option events

CHANGELOG.md, composer.json, composer.lock, module/product/src/Infrastructure/Grid/Builder/Query/DateAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/NumericAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/PriceAttributeDataSetQueryBuilder.php, module/product/src/Infrastructure/Grid/Builder/Query/UnitAttributeDataSetQueryBuilder.php
Fix "postgress" Query problem after Optimise Query for product grid query builders
Issue #1848
=> Bugfix(grid) fix product grid query builder after optymise

module/grid/src/PostGridConfiguration.php
=> bugfix(grid) - Fixing POST grid filtering by "0"
